### DISCUSSION TITLE
What is the easiest way to migrate from https://pre-commit.com?

### DISCUSSION THREAD

**Discussion by jensenbox** [evilmartians/lefthook#1014] [General]
I am very interested in moving over from https://pre-commit.com - we have a pretty decent set of tasks in our current .pre-commit-config.yaml file - is there a quick path forward to migrating?

This is our current config:

```
default_stages: [pre-commit]
minimum_pre_commit_version: "3.2.0"

default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.23.1'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '5.0']

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

```

Any guidance would be helpful!
