### DISCUSSION TITLE
i get a git index lock error since a few days...

### DISCUSSION THREAD

**Discussion by ar4hc** [evilmartians/lefthook#1020] [Q&A]
whenever i commit something i get this message since a while:

The file mentioned is gone as soon as i have the shell again, so i assume that lefthook, or one of its hooks, is too fast and outpaces itself somewhere...

But why? And where?
And how to debug this?

Output of a `git  commit`. slightly anonymized:

```
┃  check-branch.sh ❯


│  eslint (skip) no files for inspection
│  biome (skip) no files for inspection
┃  merge_conflict ❯


┃  ruff_format ❯

1 file left unchanged

┃  ruff_check ❯

Found 1 error (1 fixed, 0 remaining).

│  > git add [...]/tests/routers/conftest.py
│    fatal: Unable to create '/[...]/.git/next-index-98994.lock.lock': File exists.
│    Another git process seems to be running in this repository, e.g.
│    an editor opened by 'git commit'. Please make sure all processes
│    are terminated then try again. If it still fails, a git process
│    may have crashed in this repository earlier:
│    remove the file manually to continue.
│
│  Couldn't stage fixed files:error in batch 0: exit status 128

  ────────────────────────────────────
summary: (done in 0.08 seconds)
✔️ check-branch.sh
✔️ merge_conflict
✔️ ruff_check
✔️ ruff_format
[use_post_in_submit d87c44a8] style: ruff
```

The commit is fine as in git has it, not sure what fails, i thinks, it's the fixed file (by ruff?) that's not committed / staged correctly, so only "my" version before the fixes is in git.

**Comment by mrexox** [comment]
Thank you for reporting this! Could you share your config? Or a minimal config (e.g. specific command that triggers this error)? I want to try reproducing this bug

**Comment by ar4hc** [comment]
i think i found a lead:
It occurs on any `git commit`, but it seems only if my Intellij is open too.
Which makes some sense (kinda) as IntelliJ/Idea has/is a Git client...
I'll test this a bit more (tomorrow...)

I hae a git repo with two "projects" in subdirs of the git repo root: gui and api.
gui is js, api is python.
Inetllij is set up to use the subdirs as root for its (sub)projects.


For completeness my hook definition:
```yaml
output:
    # - meta           # Print lefthook version
    - summary # Print summary block (successful and failed steps)
    # - empty_summary  # Print summary heading when there are no steps to run
    - success # Print successful steps
    - failure # Print failed steps printing
    - execution # Print any execution logs (but prints if the execution failed)
    - execution_out # Print execution output (but still prints failed commands output)
    # - execution_info # Print `EXECUTE > ...` logging
    - skips # Print "skip" (i.e. no files matched)

commit-msg:
    run: commitlint --edit {1}

pre-commit:
    parallel: true
    commands:
        # JS, css etc.
        biome:
            tags: gui style
            root: "gui/"
            glob: "*.{svelte,js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
            exclude: "mockServiceWorker.js  "
            run: biome check --write --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {staged_files}
            stage_fixed: true
        eslint:
            tags: gui style
            root: "gui/"
            glob: "src/**/*.{svelte}"
            run: eslint --cache --fix {staged_files}
            stage_fixed: true
        # Python stuff
        ruff_format:
            tags: api style
            root: "api"
            glob: "*.py"
            run: ruff format {staged_files}
            stage_fixed: true
        ruff_check:
            tags: api
            root: "api"
            glob: "*.py"
            run: ruff check --fix {staged_files}
            stage_fixed: true
        # generic stuff
        merge_conflict:
            run: ( ! rg '^<<<<<<< ' {staged_files} )
    scripts:
        check-branch.sh:
            runner: bash
    skip:
        - merge
        - rebase

pre-push:
    parallel: true
    commands:
        test_js:
            root: "gui/"
            glob: "*.{js,svelte,ts,jsx,tsx}"
            run: pnpm test --silent
            only:
                - ref: develop
        test_python:
            root: "api"
            glob: "*.{py}"
            # run: python -m pytest -q --log-level=WARNING -o log_cli=false
            run: poetry run -- python -m pytest -q --log-level=WARNING -o log_cli=false
            only:
                - ref: develop

```
