### DISCUSSION TITLE
Skip command unless, modified files match glob pattern

### DISCUSSION THREAD

**Discussion by JoyceBabu** [evilmartians/lefthook#353] [Ideas]
We are running static analysis on the code, in `pre-push` hook. This takes a few minutes to complete.

I want to skip running static analysis on PHP files, unless the modified files contains files matching the pattern `{*.php,composer.lock,phpstan.neon}`.

Is it possible to skip running a command, unless the modified files list matches a glob pattern? I tried setting the `glob` setting to the above pattern, but it did not skip the command.

**Comment by mrexox** [comment]
Hey! Thank you for the issue! Could you provide your `lefthook.yml`?

The skipping happend when you provide `{files}`, `{push_files}`, `{staged_files}`, or `{all_files}` in `run` option. Otherwise lefthook just executes the `run` command. 

Also if you provide a `files` option which is a git command to get the desired files, lefthook will skip execution if the result of this command is empty.

Anyway, you can send your `lefthook.yml`, and I will tell you more concrete ways to fix this. Of course, it can be a lefthook bug :)

**Comment by JoyceBabu** [comment]
Thank you for the explanation. Here is my `lefthook.yml`

```yaml
pre-commit:
  scripts:
    pre-commit-hook:
      runner: bash

post-checkout:
  scripts:
    post-checkout-hook:
      runner: bash

pre-push:
  scripts:
    phpstan-check:
      glob: "{*.php,composer.lock,phpstan.neon}"
      runner: bash
```
