### DISCUSSION TITLE
remote config does not respect ref changes

### DISCUSSION THREAD

**Discussion by JuliusHenke** [evilmartians/lefthook#358] [Q&A] [answered]
First of all, thanks for the new `remote` config feature. In most cases it works quite well and feels like magic 😃 

I found an issue were lefthook will not respect the `ref` part of the `remote` config. I tried following steps with private Gitlab repos:
1.  Add a `remote` config to `lefthook.yml` like the following:
  ```yaml
  remote:
    git_url: git@github.com:evilmartians/lefthook
    config: examples/ruby-linter.yml
  ```
2. Run `lefthook install` once.
3. Now add a `ref` config to target a tag or branch:
  ```yaml
  remote:
    git_url: git@github.com:evilmartians/lefthook
    ref: v1.0.0
    config: examples/ruby-linter.yml
  ```
4. Run `lefthook install` again.
5. The downloaded repo in  `.git/info/lefthook-remotes/` has not been updated properly and lefthook will run the previous remote configuration.
