### DISCUSSION TITLE
pre-commit hook command doesn't work with prettier

### DISCUSSION THREAD

**Discussion by yurkimus** [evilmartians/lefthook#359] [Q&A]
I have this in my `lefthook.yml`:
```
pre-commit:
  commands:
    prettier:
      run: npx prettier -w {staged_files}
```

Then I edit my `.js` file and stage it:
```
git add .
```

After it I am testing lefthook to run pre-commit commands with `lefthook run pre-commit` and I get:
```
RUNNING HOOKS GROUP: pre-commit
⠦ waiting [error] No files matching the pattern were found: "'src/pages/news/[id]/index.js'".

  EXECUTE > prettier
 lefthook.yml 34ms


SUMMARY: (done in 0.83 seconds)
🥊  prettier
```

What I do wrong and how to fix this behavior?

**Comment by bennycode** [comment]
I think the problem here is Prettier's exit code. I was able to fix this problem with a workaround by using [pretty-quick](https://www.npmjs.com/package/pretty-quick):

**lefthook.yml**

```yml
pre-commit:
  parallel: true
  commands:
    prettier:
      run: yarn pretty-quick --staged --ignore-path .gitignore
```

**Comment by bennycode** [comment]
**Update:** Because [pretty-quick](https://www.npmjs.com/package/pretty-quick) doesn't work yet with Prettier 3 (_TypeError: prettier.resolveConfig.sync is not a function_), I decided to replace it with plain `prettier` in combination with a glob. The "No files matching the pattern" error usually occures when passing files to Prettier that it isn't prepared for. By supplying a glob with only the extensions I care about, I could prevent this problem on my end:

**lefthook.yml**

```yml
pre-commit:
  parallel: true
  commands:
    config:
      glob: '*.{css,html,json,less,md,scss,yaml,yml}'
      run: npx prettier --write --log-level error {staged_files}
    code:
      glob: '*.{js,jsx,ts,tsx}'
      run: npx eslint {staged_files} --fix
```

P.S. I found this by reading [this article](https://evilmartians.com/chronicles/lefthook-knock-your-teams-code-back-into-shape).
