### DISCUSSION TITLE
prepush runs all on setting upstream

### DISCUSSION THREAD

**Discussion by mhozhynewscorp** [evilmartians/lefthook#394] [Q&A]
I will not say that the problem is with Lefthook.
But the examples you can find in the documentation are just that.

I would like to ask for advice or a solution to this situation.

-----------

Suppose we have a mono repository.

We have set up something like this

```yml
pre-push:
  commands:
    a:
      root: "libs/a/"
      files: git diff --name-only HEAD @{push}
      run: npm run test
    b:
      root: "libs/b/"
      files: git diff --name-only HEAD @{push}
      run: npm run test
```

The problem is that when I create a new branch and make changes only for `a` and push it, all the tests run.
In subsequent pushes, this behavior is not observed.

Perhaps there is a more robust way to get the names of the changed files then `git diff --name-only HEAD @{push}`, taking into account `root`.

**Comment by mrexox** [comment]
Hey! Try passing the files to the `npm` if the `test` script supports arguments

```yaml
pre-push:
  commands:
    a:
      root: "libs/a/"
      files: git diff --name-only HEAD @{push}
      run: npm run test {files}
    b:
      root: "libs/b/"
      files: git diff --name-only HEAD @{push}
      run: npm run test {files}
```

**Comment by mhozhynewscorp** [comment]
hey!
you provided an extremely specific option. 
1) what if I only changed `package.json`? (and need to test all to check that let's say new version of dependency doesn't break anything)
2) how to handle files like `package.json` via test script -- assuming that it fail for non existing test or non-test file. Okay, let's add `glob` (like `*.spec.*`) to filter, but then how to handle 1st point

**Comment by mhozhynewscorp** [comment]
Ok, so I came up with such inline bash

if no upstream branch get diff from branch to be pushed head and main branch (origin/HEAD)
otherwise get changes between local and remote branches

```yml
a:
  root: "lib/any/"
  files: if [[ $(git name-rev @{u}) ]]; then return $(git diff --name-only HEAD @{push}); else return $(git diff --name-only origin/HEAD HEAD); fi
  run: npm test
```

but it isn't working and seems not running
1) Is this allowed to put bash here? 
2) Or even more would be good to extract it to separate file to reuse for each `files`:

```yml
a:
  root: "lib/any/"
  files: ./scripts/get-filenames-on-push.sh
  run: npm test
```

As I got lefthook docs you can only provide scripts to `run` and then you should provide `runner`

**Comment by mrexox** [comment]
Hey!

1. No, you can use sh syntax, but not bash here. 
2. This sounds cool but I find it a bit complicated :thinking: 

What if you try this `git diff` filter? Would it help?

```yaml
pre-push:
  commands:
    a:
      root: "lib/a/"
      files: git diff-tree -r --name-only --diff-filter=CDMR HEAD origin/master # the changed files
      run: npm test {files} # this is important, otherwise it will just run tests without arguments
```
