### DISCUSSION TITLE
Skip post-rewrite on git commit --ammend

### DISCUSSION THREAD

**Discussion by ixti** [evilmartians/lefthook#412] [Ideas]
I have a config:

``` yaml
post-checkout:
  commands:
    ctags:
      run: git-ctags

post-commit:
  commands:
    ctags:
      run: git-ctags
      skip:
        - rebase
        - merge

post-merge:
  commands:
    ctags:
      run: git-ctags

post-rewrite:
  commands:
    ctags:
      run: git-ctags
```

git-ctags is just a shell script:

``` bash
#!/bin/bash

set -euo pipefail

worktree=$(git rev-parse --show-toplevel)
tmp_file=${worktree}/"$$.tags"

trap 'rm -f "${tmp_file}"' EXIT

# Why not?: `fd --type f --base-directory "${worktree}" | ctags ...`
# Because: https://cj.rs/blog/git-ls-files-is-faster-than-fd-and-find/
git ls-files --cached --modified --others --exclude-standard \
  | ctags --quiet=yes --tag-relative=yes --extras=+f -L - -f "${tmp_file}"

mv "${tmp_file}" "${worktree}/tags"
```

Everything nice, except it runs twice on `git commit --amend`, as it causes rewrite. I want to run it on rewrite, so that it runs after rebase, thus having `skip: [commit]` in `post-rewrite`, or `skip: [..., rewrite]` in `post-commit` would be awesome!
