### DISCUSSION TITLE
Future remote options

### DISCUSSION THREAD

**Discussion by jcook-uptycs** [evilmartians/lefthook#420] [Ideas]
Thank you for adding the `remote` option. It has been very helpful. However there are a few things that could make it even more powerful. 

- Is there any plan to allow for multiple remotes? 
- The option to extend from the remote config? The last time I tested the `extend` option in a `remote` config it tried to include from the local directory. 
- Any plan to allow for scripts from a `remote` config/repo? The last time I tested, lefthook assumed the script file was from the local directory.

**Comment by mrexox** [comment]
Hey! Good question! I'd like to discuss this feature, since I am not using it myself, but it seems useful.

1. How do you mean to use multiple remotes? And why it would be useful? The main trouble for me is the merge the hooks from different remotes - the change of order may reflect on commands executed. I guess it is more clear to have just one remote config. But this is arguable.
2. Actually I've added this functionality. Did you notice a bug? Can you provide the steps to reproduce it?
3. This should have been implemented also. Both local and remote paths should be used for scripts (assuming you don't have different `source_dir` option in confiigs. If it doesn't - I'd be glad to fix it. Just file a bug.

Anyway, could you tell how you use this feature? It is useful for me to understand what use cases can be applied to remote configs. Thank you!

**Reply by jcook-uptycs** [reply]
How I plan to use the feature.

In each code repo I plan to have a `lefthook.yaml` file that only has `remote:` configured in it. 

This would point to a single file (as designed). That remote file would include many `extends:` files that are in the remote repo. The reason for breaking these files up is for easier maintenance of them, instead of having a 1000 line config file. 

Perfect world I would also use scripts from that remote repo so then I can lint the code.

I'll setup a new test and verify #2&3.

Thanks

**Reply by jcook-uptycs** [reply]
You say it supports 
> The option to extend from the remote config? The last time I tested the extend option in a remote config it tried to include from the local directory.

lefthook version  
1.3.3

I have tried and can't get it to work. The remote file is what is shown below.

```
extends: 
  - lefthook_test.yaml
``` 

Errors with 
> Error: open /Users/jcook/github/local-test/lefthook_test.yaml: no such file or directory
So this is looking locally for the extend. 


```
extends: 
  - .git/info/lefthook-remotes/test/lefthook_test.yaml
``` 
In an attempt to force getting from the `lefthook-remotes` directory

Errors with 
> Error: open .git/info/lefthook-remotes/test/.git/info/lefthook-remotes/test/lefthook_test.yaml: no such file or directory


What is the correct path to use in the `extends` config to get the correct file?

**Reply by mrexox** [reply]
Hey @jcook-uptycs. I guess the problem is that you try to reference the remote extension in the local config.
If you had the remote `lefthook.yml` configured this way, then it should work.
```yml
# remote lefthook.yml
extends:
  - lefthook_test.yaml
```
 
I designed it that way so you can reference remote `extends` only in remote config (and things should work). I can suggest to use multiple configs for the remote that use some of the extends or not. Like this:

### Remote

```
extends/
  ruby.yml
  js.yml
  python.yml
lefthook-ruby.yml
lefthook-ruby-js.yml
lefthook-python-js.yml
```

```yml
# lefthook-python-js.yml
extends:
  - extends/python.yml
  - extends/js.yml
```

### Local

```yml
# lefthook.yml that uses a remote
remote:
  git_url: ...
  config: lefthook-python-js.yml
```

Does it make sense? If not, could you describe your problem? I might consider adding a feature to fit in your use case (or maybe I can come up with a workaround solution)

**Comment by jcook-uptycs** [comment]
The only thing in the file that calls the repo is the remote. Just like your example. 
In the remote file if I only use the file name in extend lefthook tries to find the file in it's local path.

Do you have a working example I can look at?

**Reply by mrexox** [reply]
Oh yes, I got the issue. Sorry about that, I haven't tested it for a long time. I'll prepare a fix soon.

**Reply by mrexox** [reply]
Please, try **`v1.3.4`**

With this version this should work:

```yml
# lefthook.yml
remote:
  git_url: https://github.com/mrexox/lefthook-configs
  config: lefthook-3.yml
```

```bash
$ lefthook install
$ lefthook run pre-commit
...
  EXECUTE > test3
test3
```

All hooks for lefthook-1.yml, lefthook-2.yml, lefthook-3.yml are defined in extends/, see: https://github.com/mrexox/lefthook-configs

**Comment by jcook-uptycs** [comment]
The update from v1.3.3 to v1.3.4 made my configs work. 

Thanks!

**Comment by carhartl** [comment]
I'm using v1.4.6 and am getting the same problem.. here's my setup: https://github.com/carhartl/lefthook-config

Using for instance

```yaml
# lefthook.yml
remote:
  git_url: https://github.com/carhartl/lefthook-config
  config: go.yml
```

```yaml
# go.yml in remote config
extends:
  - base.yml
pre-commit:
  parallel: true
  commands:
    golangci-lint:
      tags: lint go
      glob: "*.go"
      run: for file in {staged_files}; do golangci-lint run $file; done
pre-push:
  parallel: true
  gotest:
    tags: test go
    glob: "*.go"
    run: gotest ./...
```
I'm getting "Error: open /Users/klaus/Workspace/sandbox/base.yml: no such file or directory". I must be overlooking something?
