### DISCUSSION TITLE
Provide some lefthook env vars to the running command

### DISCUSSION THREAD

**Discussion by jcook-uptycs** [evilmartians/lefthook#422] [Ideas]
It would be helpful to have lefthook pass some lefthook related env vars to the command. 

The first examples I have include
- `LEFTHOOK_HOOK` the hook that is running (ie pre-commit, commit-msg)
- `LEFTHOOK_COMMAND` the name/key of the command being run

**Comment by mrexox** [comment]
Hey! I think that you can use more explicit [`env`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#env) option, so you always know where the ENV comes from.

**Comment by jcook-uptycs** [comment]
Here is a sample example. I find I am using the command name (ex `goimports`) often in a log file. 

```yaml
pre-commit:
  commands:

    goimports:
      glob: "{*.go}"
      env:
        GIT_PAGER: cat
      run: |
        go run golang.org/x/tools/cmd/goimports@latest -l -e -w {files}
        git diff {files} > goimports.diff
        git diff-files --quiet {files} ## fail if diff
```

This could be used like either of these.

```
git diff {files} > {name}.diff
git diff {files} > ${LEFTHOOK_COMMAND}.diff
```

I understand my use case may be odd.

Thanks
