### DISCUSSION TITLE
unclear on exclude and glob

### DISCUSSION THREAD

**Discussion by lxnagel** [evilmartians/lefthook#431] [Q&A] [answered]
I ran lefthook to format files before committing
```
 commands:
  clang-formater:
    root: "source/app/"
    glob: "*.{c,cpp,h}"
    exclude: ".*$(?<!_evt\\.[h|c])"
    run: clang-format-9 --style=file -i {staged_files}
```

This left lefthook 1.2.9 still believing files ending in "_evt.c" should be passed to clang? Why?
In the meantime I was playing around with glob, solving it. Yet I would like to understand what my false assumtion was. 
This works:
```
commands:
  clang-formater:
    root: "source/app/"
    glob: "*[!_evt].{c,cpp,h}"
    run: clang-format-9 --style=file -i {staged_files}
```

Just want to make sure I'm prepared for future challenges.

**Comment by mrexox** [comment]
Hey! This `exclude` value doesn't look like a regular expression :thinking: 

You can try this:

```
exclude: ".*_evt\.(h|c)"
```

Please note [`exclude`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#exclude) expects a regular expression, not a glob. I hope this helps.

**Reply by lxnagel** [reply]
well, I tried the single backslash and it complained the yml itself. `Error: While parsing config: yaml: line n: found unknown escape character`
Even with a simple expression like
`    exclude: "\."`

**Reply by mrexox** [reply]
Ah, I see. It's because of double quotes. If used with double quotes, you should escape the backslash. Agree, this is weird

**Reply by lxnagel** [reply]
I also tried no quotes with single backslash - also running into this. As I spent some more time with glob, I noticed I can do it differently. Yet I fear I need exclude soon... X-D

**Reply by mrexox** [reply]
Well, then try using single quotes, and please come back if something goes wrong :)

**Reply by lxnagel** [reply]
exclude: '.*$(?<!_evt\.[h|c])'

Still doesnt work.
```
func filterExclude(vs []string, matcher string) []string {
	if matcher == "" {
		return vs
	}

	vsf := make([]string, 0)
	for _, v := range vs {
		if res, _ := regexp.MatchString(matcher, v); !res {
			vsf = append(vsf, v)
		}
	}
	return vsf
}
```
it really should be simple, right? I mean the root-filter can be removed and won't be an issue.

**Reply by mrexox** [reply]
I think it doesn't work because the regexp is wrong:

It doesn't compole. You can test it here: https://regex101.com/
```
'.*$(?<!_evt\.[h|c])'
```

Try this:
```
'.*_evt\.(h|c)'
```

**Reply by mrexox** [reply, marked as answer]
So, the config would look like this:

```yml
 commands:
  clang-formater:
    root: "source/app/"
    glob: "*.{c,cpp,h}"
    exclude: '.*_evt\.(h|c)'
    run: clang-format-9 --style=file -i {staged_files}
```
