### DISCUSSION TITLE
How do I run a command only on a specific branch?

### DISCUSSION THREAD

**Discussion by nottmey** [evilmartians/lefthook#432] [Q&A] [answered]
Usecase: When directly pushing to `main` I want to execute tests/lints/etc. which are normally handled in my PR checks.

I imagined something like this:
```
pre-push:
  commands:
    test:
      skip:
        - ref: ??? # skip on any branch which is not main
      run: fvm flutter test
```

**Comment by mrexox** [comment, marked as answer]
Well, in that case I'd recommend using something like this

```yml
pre-push:
  commands:
    test:
      run: [[ $(git rev-parse --abbrev-ref HEAD) != "main" ]] && true || fvm flutter test
```

Currently there is no other way to do so :thinking: but you can create a feature request (just create a new issue) and describe how it would be convenient to configure.

**Reply by nottmey** [reply]
Ah yes, ofc, that's a way too. Thank you!

I think ideally it would look something like this:
```yml
pre-push:
  commands:
    test:
      ref: main
      run: fvm flutter test
```
or maybe fit the skip mechanic with an `only` tag:
```yml
pre-push:
  commands:
    test:
      only:
        - ref: main
      run: fvm flutter test
```
or maybe only extend the skip mechanic with a regex feature:
```yml
pre-push:
  commands:
    test:
      skip:
        - ref: feat/*
      run: fvm flutter test
```

Just some inspirations. Do you like any of those?
