### DISCUSSION TITLE
Achieve this behaviour with the "skip" option

### DISCUSSION THREAD

**Discussion by PointSingularity** [evilmartians/lefthook#463] [Q&A] [answered]
I am migrating from lint-staged/husky, and I am on Windows.

I have this post-merge hook defined:

```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

IFS=$'\n'
PACKAGE_LOCK_REGEX="(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
PACKAGES=("$(git diff --name-only HEAD@{1} HEAD | grep -E "$PACKAGE_LOCK_REGEX")")

# If there are any package-lock.json files, run npm install in the directory of the package-lock.json file
if [[ ${PACKAGES[@]} ]]; then
  for package in $PACKAGES; do
    echo "📦 $package was changed. Running npm install. "
    DIR=$(dirname package)
    cd "$DIR" && npm install
  done
fi
```

Is it possible to achieve this behavior in lefthook using the skip option.
I've tried this, but it's definitely not correct:
```yaml
post-merge:
  commands:
    run-install:
      skip: |
        PACKAGE_LOCK_REGEX="(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
        PACKAGES=("$(git diff --name-only HEAD@{1} HEAD | grep -E "$PACKAGE_LOCK_REGEX")")
         if [[ ${PACKAGES[@]} ]]; then
           return 0
         else
           return 1
         fi
      run: npm install
```

**Comment by mrexox** [comment, marked as answer]
Hey! There is a [`files`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#files) option that allows to [skip execution](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#files:~:text=for%20run%20setting.-,If%20the%20result%20of%20this%20command%20is%20empty%2C%20the%20execution%20of%20commands%20will%20be%20skipped.,-This%20option%20overwrites) if the result of `files` is empty. I think it can fit your case:

> Haven't tested this, so the command may need some edits

```yml
# lefthook.yml

post-merge:
  commands:
    run-install:
      files: git diff --name-only HEAD@{1} HEAD | grep -E "(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
      run: npm install
```

**Reply by PointSingularity** [reply]
This works, thank you 👍

**Reply by PointSingularity** [reply]
@mrexox 
One more question, is there a way to choose how lefthook is executed? 
Some shell scripts work on Windows, some don't depending on what you have installed.
Choosing git bash in this command would, for example, provide a greater compatibility with POSIX systems.

**Reply by mrexox** [reply]
Hey! Now we use `sh` without a way to configure this. Do you feel it would be convenient to add a global-level option for all shell-like interactions? I must say that there are also implicit calls to `git` executable used in lefthook.

Maybe it would be useful to specify a shell for `files` and `run` options :thinking: What do you think?

**Reply by PointSingularity** [reply]
Hey!
Here is my current conundrum, if I run this under WSL it works, but it fails under normal Windows: 
```
# lefthook.yml

post-merge:
  commands:
    run-install:
      files: git diff --name-only HEAD@{1} HEAD | grep -E "(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
      run: npm install
```
with the following error:
```bash
RUNNING HOOK: post-merge
error replacing {files}: exit status 128
run-install: (skip) error
```

Running this command with CMD or PowerShell fails, because there is no grep on Windows:
```bash
git diff --name-only HEAD@{1} HEAD | grep -E "(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
```
But it works with git bash (that comes included when you install git for windows).


Now the shell script in my original question works with both normal windows and WSL, but I am not really sure how husky works, that is if it actually uses the git bash under the hood.

So being able to set the shell would make this easier, but of course it would still fail if the git bash isn't installed on Windows.

Sadly, Windows is always the problem child when it comes to stuff like this :\

If you have any ideas how to proceed, that would really be helpful!

**Reply by mrexox** [reply]
By the way, how do you run it? Do you run it manually with `lefthook run post-merge` or implicitly with `git merge ...`? It is important because git hooks are actually shell scripts, and they trigger lefthook from the shell, so it should be working OK in implicit flow.

I don't have a general solution for such an issue right now and I can't find one obvious solution to support both Powershell/cmd and bash shells  :confused:. But anyway it's good to know there is such an issue and maybe we will come up with a solution later.

**Reply by PointSingularity** [reply]
Ok, here is my 'workflow', on standard Windows 11: 


https://user-images.githubusercontent.com/56246797/230586023-85ad9aca-f1ed-43db-b657-af306488e9e6.mp4




But I tried running it again under WSL (Ubuntu) and it also fails now, but grep works. 

![image_2023-04-07_11-20-26](https://user-images.githubusercontent.com/56246797/230583111-3e325e0e-be27-4239-96cc-1708f77a2b22.png)


Git output: 
![image_2023-04-07_11-24-15](https://user-images.githubusercontent.com/56246797/230583576-2b5c9cc5-6f0f-4e7d-8e16-fbb49e1698fe.png)

So now I am really confused  😅

**Reply by mrexox** [reply]
Wow, I guess I know what is the issue here. In a latest version of lefthook there were added positional arguments to `files` command. See https://github.com/evilmartians/lefthook/pull/461. So, `HEAD@{1}` probably transforms to `HEAD@` which raises an error. I'd suggest a workaround:

```yml
# lefthook.yml

post-merge:
  commands:
    run-install:
      files: git diff --name-only HEAD@{1\} HEAD | grep -E "(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
      run: npm install
```

This escape of `\}` should probably work well. But if not, you could try this:

```yml
# lefthook.yml

post-merge:
  commands:
    run-install:
      files: git diff --name-only HEAD~1 HEAD | grep -E "(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
      run: npm install
```

Hope this helps!

Also, try running git commands with `LEFTHOOK_VERBOSE=true` ENV variable, so you can see actual commands executed.

**Reply by PointSingularity** [reply]
Hey, both commands work on WSL, thank you!

Both still fail on Windows, here is the output with the LEFTHOOK_VERBOSE=true:
![image](https://user-images.githubusercontent.com/56246797/230873255-8f02d141-406f-499a-9e77-fc5c6b924d34.png)

It is the same for both versions.

**Reply by mrexox** [reply]
Oh I see, the problem is that for Windows we [pass the plain command](https://github.com/evilmartians/lefthook/blob/master/internal/git/exec.go#L56-L60) instead of wrapping it into a `sh -c` call.

I'm not sure if it's safe to change this since Windows doesn't require `sh` to be installed for Git (or does it?).

There is a workaround: you can add a small script `post-merge-files.sh`

```bash
# post-merge-files.sh

git diff --name-only HEAD@{1} HEAD | grep -E "(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
```

And then use the following way to reference it in `files`:

```yml
# lefthook.yml

post-merge:
  commands:
    run-install:
      files: sh post-merge-files.sh
      run: npm install
```

This doesn't look cool since it adds an extra file to your project, but I'm not sure about changing the current behavior. It might break flow for existing Windows users that use `files` option without a pipe and don't have `sh` installed.

Maybe adding a global option for all commands wrapper might help :thinking:

WDYT?
