### DISCUSSION TITLE
Opt-in to auto-corrections? Custom fix commands that are different than the run command?

### DISCUSSION THREAD

**Discussion by technicalpickles** [evilmartians/lefthook#469] [Q&A] [answered]
Is there a way to let users opt in/out of autofixing globally? I'm migrating our teams from https://github.com/gusto/committer which has a flag to run the pre-commit hook with a fix.

We can also configure a separate command for fixing, with autostage, ie:

```yaml
  - name: SVGO
    command: script/committer-svgo.sh
    files: '\.svg$'
    fix:
      command: yarn run svgo -i
      output: '\n'
      autostage: true
```

From what I'm seeing, the convention is to add the fix  flags to the `run` command, and then `auto_stage` if you want it. I could imagine using a lefthook-local.yml for some of it, but it might involve a bunch of copy & paste.

**Comment by mrexox** [comment]
Hey! There is [`stage_fixed`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#stage_fixed) option for commands that work only for `pre-commit` hook now. You can enable it for commands where you want to do `git add` for files that were changed after the command finished. There's no global option for that yet, but it probably makes sense to add one :thinking: 

Is it the thing you were looking for?

**Reply by technicalpickles** [reply]
Not exactly. I'm asking to be able to make it user-configurable if fixes are attempted to be made. That may or not be separate from configuring allowing auto-staging per user.

This might be a moot question, since most people I've talked to so far are anti fix and stage anyways.

**Reply by mrexox** [reply, marked as answer]
I guess I got it. So, you want to control these steps:
1. Run the linter
2. If it fails, run a fixing command
3. Control whether to stage changes or not

If that's correct I can suggest a workaround since this flow is not usual. The idea is to call call lefthook from within itself.

```yml
# lefthook.yml

pre-commit:
  commands:
    lint:
      run: yarn lint || ([ -n "${AUTOFIX}" ] && lefthook run lint-fix || exit 1)
      # in case fixing command triggers git hooks (and then lefthook)
      # env:
      #   LEFTHOOK: 0 

lint-fix:
  commands:
    lint-fix:
      run: yarn run lint --fix
      # stage_fixed: true
```

```bash
# Run with no auto fixing
git commit

# Run with auto fixing
AUTOFIX=true git commit
```

The only notice: this requires `lefthook` to be available from PATH. Does it look like a solution?

And yes, there's `lefthook-local.yml` which would be a better option for user-specific configuration.

```yml
# lefthook.yml

pre-commit:
  commands:
    lint:
      run: yarn lint
    # some other commands maybe
```

```yml
# lefthook-local.yml

# This hook is "merged" into hook configuration defined in lefthook.yml, so you can overwrite only desired settings (only 'run' option for example)
pre-commit:
  commands:
    lint:
      run: yarn lint --fix
```
