### DISCUSSION TITLE
Re-use commands and scripts between hooks

### DISCUSSION THREAD

**Discussion by technicalpickles** [evilmartians/lefthook#470] [Q&A] [answered]
Is there a way to share commands between the different hooks? I'm trying to support pre-commit while also evaluating moving most of those to pre-push, and ended using YAML anchors and references initially, ie:

```yaml
# lefthook.yml
pre-commit:
  commands:
    rubocop: &rubocop
      tags: backend style
      glob: "{Rakefile,Brewfile,Gemfile,*.{rb,rake,rabl,arb}}"
      run: bin/rubocop --color --force-exclusion --format simple --autocorrect {staged_files}
      auto_stage: true

pre-push:
  skip: true
  commands:
    rubocop:
      <<: *rubocop
```

I use `skip: true` so I don't run it in both places. I'm able to test pre-push locally using:

```yaml
pre-commit:
  skip: true

pre-push:
  skip: false
```

This works for pre-commit, I just got a report from someone testing it that the push didn't actually match anything. It turns out there is a difference between `{staged_files}` and `{push_files}` 😓 

Some initial ideas I am considering:
- switch to using `files`, and see if can figure out a command to detect which git hook is firing?
- change the command to a script, so it's only the `{staged_files}` vs `{pushed_files}` that is different... but I don't see a way to configure the passed options?

**Comment by mrexox** [comment]
Hey! If I correctly understood your question, you want to have similar commands for both `pre-commit` and `pre-push` hooks. But you need to have different commands selecting files. I guess you can use hook's global [`files`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#files-global) option.

```yml
# lefthook.yml
pre-commit:
  files: git diff --name-only --cached --diff-filter=ACMR
  commands:
    rubocop: &rubocop
      tags: backend style
      glob: "{Rakefile,Brewfile,Gemfile,*.{rb,rake,rabl,arb}}"
      run: bin/rubocop --color --force-exclusion --format simple --autocorrect {files}
      auto_stage: true

pre-push:
  files: git diff --name-only HEAD @{push}
  commands:
    rubocop:
      <<: *rubocop
```

**Reply by technicalpickles** [reply]
Thanks, this seems to work!

Although, I think I came across a bug with pre-push... When I am on a new branch that hasn't run, the `git diff --name-only HEAD @{push}` doesn't work:

```
[lefthook] err: exit status 128
[lefthook] out: fatal: ambiguous argument '@{push}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

error replacing {files}: exit status 128
```

I confirmed on the command line too. Once pushed, it does work.

edit: can't actually reproduce that, but will open an issue if I see it again

**Reply by mrexox** [reply]
Yes,  lefthook itself actually tried two commands for push_files. You can have this command which won't be failing:

```
git diff --name-only HEAD @{push} || git diff --name-only HEAD main # or 'master', depends on the primary branch name you have
```

**Comment by technicalpickles** [comment, marked as answer]
Final answer, based on @mrexox's initial message and followup:

```yaml
# lefthook.yml
pre-commit:
  files: git diff --name-only --cached --diff-filter=ACMR
  commands:
    rubocop: &rubocop
      tags: backend style
      glob: "{Rakefile,Brewfile,Gemfile,*.{rb,rake,rabl,arb}}"
      run: bin/rubocop --color --force-exclusion --format simple --autocorrect {files}
      auto_stage: true

pre-push:
  files: git diff --name-only HEAD @{push} || git diff --name-only HEAD main # or 'master', depends on the primary branch name you have
  commands:
    rubocop:
      <<: *rubocop
```
