### DISCUSSION TITLE
How to run a command that doesn't take a list of files?

### DISCUSSION THREAD

**Discussion by sanmai-NL** [evilmartians/lefthook#504] [Q&A]
```yaml
---
pre-push:
  parallel: true
  commands:
    pylint:
      glob: "*.py"
      run: pylint --enable-all-extensions --output-format=colorized src/
```

```console
$  lefthook run pre-push
Lefthook v1.4.2
RUNNING HOOK: pre-push
pylint: (skip) no files for inspection
```

**Comment by sanmai-NL** [comment]
It only works if the job name doesn't refer to a Git stage. But then I don't have the guarantee these hooks are run.

**Comment by mrexox** [comment]
By default `pre-push` hook (as well as `pre-commit` hook) is skipped if there's no matching files to push/commit. You have a `glob` filter, and it looks like after applying the glob no `*.py` files are being pushed, that's why the command is skipped.

Do you want pylint to run always before push?

**Reply by sanmai-NL** [reply]
Yes, and in particular, I want to be able run the pre-push hook manually as well.

**Reply by mrexox** [reply]
Ok, so if you want to always run pylint event if no Python files were touched, I can suggest you removing `glob` option. 

Running the hook manually can always be done this way: `lefthook run pre-push` however it checks pushed files and skips executing if there's nothing to push. So, yes, you can use your own "hook" for that:

```yml

lints: &lints
  parallel: true
  commands:
    pylint:
      run: pylint ...
    prettier:
      run: ...
    ...

pre-push:
  <<: *lints
```

So, for manual run use `lefthook run lints`, and for `pre-push` git hook it will be executed automatically (skip rules for pre-push hook will be applied).

Does it sound good?

**Comment by sanmai-NL** [comment]
A workaround to include hooks that don't take a list of files in a quasi-pre-push hook, DRY:
`Lefthook.yaml`:

```yaml
---
pre-push:
  parallel: true
  commands: &pre-push
    prettier:
      glob: '*.{css,js,html,jsx,md,toml,ts,yml,yaml}'
      run: prettier --ignore-unknown --list-different {all_files}
pre-push-plus:
  commands:
    <<: *pre-push
    pylint:
      run: pylint --enable-all-extensions --output-format=colorized src/
    creosote:
      run: creosote --exclude-deps python-multipart uvicorn --verbose
    gitdiffcheck:
      run: git diff --check
```
