### DISCUSSION TITLE
-Flutter & Windows & lefthook "git commit" command fails

### DISCUSSION THREAD

**Discussion by vojte** [evilmartians/lefthook#518] [General]
I have a very specific issue. I am working on a Flutter project which uses lefthook. So there is no /npm folder for example. 

And this project currently doesn't work with the newest version of lefthook. It's working with version 1.2.6. 

Therefore I've installed this specific lefthook version 1.2.6. When I run lefthook commands from lefthook.yml individually, everything looks fine, command line uses version 1.2.6. 

The main issue is when I run "git commit" command. Then for some reason it runs few npm exec commands and uses version 1.4.3. instead. Then my git commit fails. I had to uninstall lefthook on this project as a workaround to be able to at least commit.

Do you have any idea how could I solve it and force to use lefthook version 1.2.6. within "git commit"?

I am using Windows, even tried to add lefthook path to my PATH variable but maybe in a wrong way.

This is output of my git commit command
```shell
git commit -m "[GR-3370] Better formatting, removed unused import"
Lefthook v1.4.3
RUNNING HOOK: pre-commit

  EXECUTE > pretty
Formatted 2 files (0 changed) in 0.20 seconds.

exit status 0xc0000005
SUMMARY: (done in 5.36 seconds)
``` 

And this is lefthook.yml

```
pre-commit:
  commands:
    pretty:
      glob: "*.dart"
      run: fvm flutter format {staged_files} && git add {staged_files}

lint:
  parallel: true
  commands:
    lint_code:
      glob: "*.dart"
      run: dart fix --apply lib && git add .

pre-push:
  commands:
    #    tests:
    #      run: flutter test
    #    exclude: "*.g.dart"
    linter:
      run: fvm flutter analyze
```

Thanks for any advice.

**Comment by mrexox** [comment]
Hey! You see different version probably because you have different global lefthook and lefthook from npm package. Could you please clarify a few things?

1. What is your global `lefthook version`? Where does it belong - `which lefthook` or `whereis lefthook`
2. What version is in your `package.json`?
3. What is the error you get when you just `git commit`? Lefthook is supposed to be backward compatible :thinking:, so it's surprising for me and I'd like to fix that.

**Reply by vojte** [reply]
Thank you for checking that! Actually my apologies, I was able to run `git commit` with global installed version - it was about wrong Windows PATH variable, I had to put the whole path to executable, in my case `C:\Users\Vojte\AppData\Roaming\npm\node_modules\lefthook\node_modules\lefthook-windows-x64\bin`

So issue name should be renamed.

BUT... it didn't solve the issue with commit. I am still unable to run `git commit`. Getting the same output as written above with `exit status 0xc0000005` 

I'll answer your questions:
1. `which lefthook` shows `/c/Users/Vojte/AppData/Roaming/npm/lefthook` so that's fine I guess
2. project `package.json` doesn't exist as it's Flutter project, global `package.json` not sure where is it on Windows
3. the same error as mentioned above, like this, as you can see I've downgraded lefhook version but it did not help. Interesting is that if I run `lefhook run pre-commit` it's working no problem. Output also shows `pretty` not sure what that means. I think it might be related to Win git version somehow...
```
git commit
Lefthook v1.2.6
RUNNING HOOK: pre-commit

  EXECUTE > pretty
Formatted 1 file (0 changed) in 0.14 seconds.
exit status 0xc0000005

SUMMARY: (done in 5.92 seconds)
🥊  pretty
```
4. As addition I also include my versions of win, npm, node, git...
Windows 11
npm 9.6.1
node 18.15.0
git version 2.41.0.windows.1
Flutter 3.3.10
Dart 2.18.6

**Reply by mrexox** [reply]
Ok, let's stick with the latest version and try fixing the exit status issue. Could you edit your config file a little bit. Lefthook now supports auto staging fixed files, so maybe this will help:

```yml
# lefthook.yml

pre-commit:
  commands:
    pretty:
      glob: "*.dart"
      run: fvm flutter format {staged_files}
      stage_fixed: true
```

Also please send the output when running `LEFTHOOK_VERBOSE=true git commit`
