### DISCUSSION TITLE
how to skip pre-commit commands on merge commits?

### DISCUSSION THREAD

**Discussion by technicalpickles** [evilmartians/lefthook#567] [Q&A]
Currently, we use things like rubocop and other ruby commands for pre-commit hook. One problem we often run into when merging main into a branch is:

1. changes to `Gemfile.lock` mean that the pre-commit can't run unless you've bundled
2. if it is a sufficiently large merge, these can take an extra long amount of time if there were lots of changes, and are more likely to fail

Is there any way to not run a command when it's a merge-commit? Bonus points for being able to skip specific branches (ie main).

It does not seem like the pre-commit hook doesn't have any arguments (based on [git help githooks](https://git-scm.com/docs/githooks)), but maybe there is another way to check?

**Comment by technicalpickles** [comment]
I swear I looked before, but was pointed to these options:

```yaml
pre-commit:
  commands:
    lint:
      skip:
        - merge
        - rebase
      run: yarn lint
```

It seems you can skip on specific refs, but not merges from specific refs:

```yaml
pre-commit:
  skip:
    - ref: main
  commands:
    lint:
      run: yarn lint
    text:
      run: yarn test
```
