### DISCUSSION TITLE
no matching push files

### DISCUSSION THREAD

**Discussion by trobrock** [evilmartians/lefthook#603] [Q&A] [answered]
I just set up a pre-push hook to run my tests and I'm having some trouble. Most of the time it works, but it seems like when I do my first push to a new branch `git push -u some-branch` I get the following output:

```
 % gp -u origin weekly-upgrade 
╭────────────────────────────────────╮
│ 🥊 lefthook v1.5.5  hook: pre-push │
╰────────────────────────────────────╯
│  rspec (skip) no matching push files
                                      
  ────────────────────────────────────
summary: (skip) empty                 
```

My lefthook config is pretty simple:

```
pre-push:
  parallel: true
  commands:
    rspec:
      run: bundle exec rspec
```

Am I doing something wrong? I just want my tests to always run on a push.
