### DISCUSSION TITLE
change only the files template

### DISCUSSION THREAD

**Discussion by hituzi-no-sippo** [evilmartians/lefthook#619] [Q&A] [answered]
Thanks for creating this great tool.

I would like to change only the files template such as `{satged_files}`, `{all_files}`.
Please let me know if there is a good way.

I write all the same scripts except for the files templates, as in the following YAML configuration:

``` YAML
---
pre-commit:
  commands:
    hoo: &staged
      run: echo {staged_files}

pre-push:
  commands:
    hoo:
      run: echo {push_files}

pre-merge-commit:
  commands:
    hoo: *staged

lint:
  commands:
    hoo:
      run: echo {all_files}
```

The files templates, which I would like to use is as follows:

- pre-commit / pre-merge-commit
  `{staged_files}`
- pre-push
  `{push_files}`
- Others (e.g. `lint`)
  `{all_files}`

Thanks.

**Comment by mrexox** [comment, marked as answer]
Hey! I think in this case you can use custom `files` for each hook like this:

```yml
lint:
  files: git ls-files --cached # all files
  commands:
    hoo: &hoo
      run: echo {files}

pre-merge-commit:
  files: git diff --name-only --cached --diff-filter=ACMR
  commands:
    hoo: *hoo

pre-commit:
  files: git diff --name-only --cached --diff-filter=ACMR
  commands:
    hoo: *hoo

pre-push:
  files: git diff --name-only HEAD @{push}
    commands:
      hoo: *hoo
```

Please, write back if it helps!
