### DISCUSSION TITLE
Allow to repeat commands once per file

### DISCUSSION THREAD

**Discussion by reitzig** [evilmartians/lefthook#631] [Ideas]
Consider this config:

```yaml
pre-commit:
  commands:
    vet:
      glob: "*.go"
      run: go vet {staged_files}
```

Looks reasonable, but does not work: if you stage two files from different directories, we get

> named files must all be in one directory

Now, one could argue all day whether that's reasonable behaviour, but it's unlikely to change that standard tool.

Now, repeating the desired command is not hard:

```yaml
pre-commit:
  commands:
    vet:
      glob: "*.go"
      run: for f in {staged_files}; do go vet "${f}"; done
```

But wouldn't something like this be nicer?

```yaml
pre-commit:
  commands:
    vet:
      glob: "*.go"
      run: go vet {staged_file}
      iterate: true
```

Not sure about the best way of combining flags and template variables here, so that is just an idea.
