### DISCUSSION TITLE
How can I generate configs for multiple directories?

### DISCUSSION THREAD

**Discussion by allanlewis** [evilmartians/lefthook#633] [Q&A]
I have a monorepo with a number of components, each in its own directory. The hooks I want to fun for each component are similar; for the purpose of this discussion let's say they're the same but with the name of the component/service templated-in somehow. Can Lefthook support this?

**Comment by mrexox** [comment]
Hey! Lefthook has [`root`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#root) option made exactly for monorepos.

So, I guess it will look something like this:

```yml
pre-commit:
  commands:
    component1:
      root: project1/
      run: make component1
    component2:
      root: project2
      run: make component2
```

If you have the same command to run you can use YAML anchors

```yml
_: # this custom hook is used only to provide the anchor
  commands:
    command: &command
      run: yarn lint
      glob: "*.js"
      stage_fixed: true

pre-commit:
  commands:
    component1:
      *command
      root: project1/
    component2:
      *command
      root: project2
```

**Reply by VanTanev** [reply]
The above YAML is incorrect. The way to reference and expand another reference is with `<<: *var`, not `*var` by itself. So, for posterity:

```yaml
_: # this custom hook is used only to provide the anchor
  commands:
    command: &command
      run: yarn lint
      glob: "*.js"
      stage_fixed: true

pre-commit:
  commands:
    component1:
      <<: *command
      root: project1/
    component2:
      <<: *command
      root: project2
```
