### DISCUSSION TITLE
How to display a message when a developer try to push

### DISCUSSION THREAD

**Discussion by MatteoGauthier** [evilmartians/lefthook#654] [Q&A]
Hey ! I'm trying to implement a simple lefthook config to show a message of recommendation when a developer of my team try to git push.

Does someone can help me achieve that ?

**Comment by mrexox** [comment]
Hey! Do you want to just show the recommendation or you want to wait for the confirmation of a developer?

A simple `echo` can be used for this:

```yml
# lefthook.yml

pre-push:
  commands:
    show-message:
      run: echo 'Please make sure your code is tested'
```
