### DISCUSSION TITLE
pre-commit checks that fail on unstaged files

### DISCUSSION THREAD

**Discussion by technicalpickles** [evilmartians/lefthook#679] [Q&A]
We are using [sorbet](https://sorbet.org/) as a pre-commit, and a problem I've come across is that:

1. it needs to consider the whole code base, since changing typing info in one place has others
2. it can fail on unstaged/untracked files
3. it appears that it take a list of files, but it doesn't seem to work in practice

I originally had thought that lefthook stashes unstaged changes for some reason, but that doesn't seem to be the case.

Does anyone else have similar type of linters, and if so, how do you configure them to avoid false positives on staged changes?

**Comment by mrexox** [comment]
Hey, lefthook must respect unstaged changes and fix only staged changes. Could you share the config please? If you notice that unstaged changes are not hidden when calling commands please submit an issue with Bug label.

**Reply by technicalpickles** [reply]
Here's the relevant config for sorbet. I'll try to make a smaller reproducible case.

```yaml
pre-commit:
  parallel: true
  # copy what {staged_files} does, so we can use {files}, and re-use them in pre-push
  files: git diff --name-only --cached --diff-filter=ACMR
  commands:
    sorbet: &sorbet
      tags: [backend, typing, pre-commit-and-pre-push]
      glob: "*.{rb,rbi}"
      run: bin/srb tc
      # NOTE: don't think about using stage_fixed, because sorbet's autocorrect generally has false positives
```

Note that we don't give `bin/srb tc` files to run on, because the type checking needs to consider the whole repo, not just the ones that changed.

What I think is happening is that the unrelated files are still being picked up by sorbet because of how it is configured to pick up anything .rb. If that is the case, I could plausibly use `git ls-files --others --exclude-standard` to get a list to tell `srb` to ignore (it has an option for that).

**Reply by technicalpickles** [reply]
Here's a smaller case:

```yaml
pre-commit:
  commands:
    contents_problem:
      run: bash -c 'if grep problem uncommitted.rb; then echo contents problem detected; exit 1; fi'
```

And then:

```
$ echo problem > uncomittted.rb
$ git commit -a -m "test"
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.6.4  hook: pre-commit │
╰──────────────────────────────────────╯
sync hooks: ✔️ (pre-commit)
┃  contents_problem ❯

problem
contents problem detected


  ────────────────────────────────────
summary: (done in 0.09 seconds)
🥊  contents_problem
```
