### DISCUSSION TITLE
is skip option available for post-commit git hook?

### DISCUSSION THREAD

**Discussion by jessicatarra** [evilmartians/lefthook#682] [Q&A] [answered]
Hello everyone, I have a question regarding the validity of the following yaml configuration, specifically the 'skip' option part. Could someone please confirm if these settings are indeed valid for post-commit hook? Thank you in advance.

```yaml
post-commit:
  parallel: true
  scripts:
    "analyze-packages-diff-filter":
      skip:
        - merge
        - rebase
      runner: bash
      use_stdin: true

```

**Comment by mrexox** [comment, marked as answer]
Hey! Yes, these settings are valid. But if you want to ignore the whole hook you can place the `skip` option right under the hook name like this:

```yml
post-commit:
  parallel: true
  skip:
    - merge
    - rebase
  scripts:
    "analyze-packages-diff-filter":
      runner: bash
      use_stdin: true
```
