### DISCUSSION TITLE
Priorities ignored, scans seemingly running alphabetically

### DISCUSSION THREAD

**Discussion by createchange** [evilmartians/lefthook#683] [General]
Hi there, I want to assign tasks to run in a certain order, but it seems like the priority is ignored. I'm curious if I am doing something wrong.

Config:
```yaml
pre-commit:
  # parallel: true
  piped: true
  scripts:
    "gitleaks.sh":
      priority: 1
      runner: bash
    "black.sh":
      priority: 2
      runner: bash
    "flake.sh":
      priority: 3
      runner: bash
    "semgrep.sh":
      priority: 4
      runner: bash
    "dependencies.sh":
      priority: 5
      runner: bash
    "confirmation.sh":
      priority: 0
      interactive: true
      runner: bash
```

Output:
```bash
[nix-shell:~/lefthook_test_6]$ git commit -m test
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.6.1  hook: pre-commit │
╰──────────────────────────────────────╯
┃  black.sh ❯


┃  confirmation.sh ❯

Are you sure you want to commit? [Y/n]: n
Confirmation declined. Exiting.
│  dependencies.sh (skip) broken pipe
│  flake.sh (skip) broken pipe
│  gitleaks.sh (skip) broken pipe
│  semgrep.sh (skip) broken pipe

  ────────────────────────────────────
summary: (done in 1.49 seconds)
✔️  black.sh
🥊  confirmation.sh
```
