### DISCUSSION TITLE
How to get list of all changed files or current working directory in hook or run hook in current working directory

### DISCUSSION THREAD

**Discussion by jremus** [evilmartians/lefthook#697] [Q&A]
I am working on custom Git prepare-commit-msg and commit-msg hook scripts that both need to process the complete list of changed files. This must work for commit, amend, and reword and for both prepare-commit-msg and commit-msg hooks.

I am facing the following issues:
- `git diff --staged --name-only` returns the list of changed files only for "normal" commits. For amend it returns only the additional changed files. For reword it returns nothing.
- `git diff-tree --no-commit-id --name-only -r $SHA1` returns only the list of changed files of an existing commit. This would allow to collect existing changes during amend in a prepare-commit-msg hook. But due to the lack of a SHA1 it does not work in a commit-msg hook.

Therefore I have resorted to parsing the comments about changed files generated by Git into the commit message. This works well when invoking Git from the toplevel directory of the working tree. When invoking Git from a subdirectory the paths of the changed files in the comments are relative to the current working directory.

In theory it would be easy to convert those paths relative to the current working directory back to paths relative to the toplevel directory of the working tree:
```shell
GIT_TOPLEVEL="$(git rev-parse --show-toplevel 2>/dev/null)"
...
file="$(realpath --relative-to="$GIT_TOPLEVEL" "$file")"
```
But Lefthook apparently invokes Git hook scripts from the toplevel directory of the working tree. Therefore I don't have access to the current working directory the user invoked Git in from within my hook script.

I tried to get Lefthook to execute my hook from the current working directory without success:
```yaml
prepare-commit-msg:
  commands:
    myhook:
      #root: "$."
      #root: "$(pwd)"
      #root: "$(realpath --relative-to=$(git rev-parse --show-toplevel) $(pwd))"
      run: .lefthook/prepare-commit-msg/myhook.sh {0}
  scripts:
    "myhook.sh":
      runner: bash
      skip: true
```

To resolve my issue I either need a mean to:
- get the complete list of changes files using some Git command,
- get the current working directory the user invoked Git from within my hook script, or
- have Lefthook invoke my hook script from the current working directory instead of the toplevel directory of the working tree.

Thanks in advance!
