### DISCUSSION TITLE
Wildcard support for `extends`

### DISCUSSION THREAD

**Discussion by yungvldai** [evilmartians/lefthook#700] [Ideas]
Hello! I am using lefthook in PNPM monorepo and now I have to specify every package in root config:

```
extends:
    - packages/a/lefthook.yml
    - packages/b/lefthook.yml
    - packages/c/lefthook.yml
    ...

pre-push:
    parallel: true

pre-commit:
    parallel: true
```

What do you think about allowing the path to be specified with a wildcard. Seems like this would be useful for monorepos.

Smth like this:

```
extends:
    - packages/*/lefthook.yml

pre-push:
    parallel: true

pre-commit:
    parallel: true
```
