### DISCUSSION TITLE
Is it possible to skip the install and synchronization of certain hooks?

### DISCUSSION THREAD

**Discussion by ardelato** [evilmartians/lefthook#715] [General]
**TL;DR** Is it possible to run a `lefthook` hook without the `.git/hooks` directory being modified? 

----

We've recently switched from using `git hooks` combined with `lint-staged` to solely using `lefthook` in our monorepo. This change was implemented to streamline managing and executing multiple linters simultaneously during our CI process. Which by using `lefthook` has made it very easy and clean to do! 🙌 

We then encountered a problem where our CI runners were inadvertently syncing the `git hooks` that affected the auto-commit linter fixes, leading to failures. 

![image](https://github.com/evilmartians/lefthook/assets/22064420/91945ff3-70df-4495-b948-3412dc505ae6)

To address this, we configured `lefthook` to skip all hooks in the CI environment except for the specific ones needed, using a `skip` option in the `run` settings.

```yaml
pre-commit:
    parallel: true
    skip:
        - rebase
        - merge
        - run: test ${CI:-false} = true

post-commit:
    skip:
        - rebase
        - run: test ${CI:-false} = true
    piped: true
    commands: *clear_git_cache

ci:
    parallel: true
    files: git diff origin/master --name-only
```

Despite solving the issue, we are curious if there is a simpler solution. Specifically, we want to know if there's a way selectively execute certain hooks in a CI environment without triggering the entire install script. https://github.com/evilmartians/lefthook/blob/1d100c61a28454d9bcdfa7045958dce1e5d8cab1/internal/lefthook/install.go#L111-L191
