### DISCUSSION TITLE
How can I abort git commit by checking specific string inside command logs?

### DISCUSSION THREAD

**Discussion by aniketmalandkar** [evilmartians/lefthook#728] [Q&A]
Hello Team, 

I have the following yml config:
```
pre-commit:
  commands:
    atlas-lint:
      run: make atlas-lint
 ```

I'm looking for aborting commit if there is an error or if it matches a specific string in the logs of make atlas-lint. Is it possible?

**Comment by mrexox** [comment]
@aniketmalandkar , sure, you can use `grep` and bash syntax for exiting 1 which will prevent the commit. In you case it could be:

```yml
pre-commit:
  commands:
    atlas-lint:
      run: make atlas-lint | grep -v 'specific string'
```
