### DISCUSSION TITLE
How to make an "extends" file in a subdirectory not include its path in the repo

### DISCUSSION THREAD

**Discussion by noamraph** [evilmartians/lefthook#752] [Ideas]
I'm working in a sort of monorepo, where there are multiple projects in a larger repository. I want the tests for a subproject to be defined in the project's subdirectory.

This is how I made it work: in the main directory, I have a `lefthook.toml` file with `extends` referring to a `lefthook.toml` file in the subdirectory. The file `path/to/subproject/lefthook.toml` looks like this:

```toml
[pre-commit.commands.ruff]
root = "path/to/subproject/"
glob = "*.py"
run = ".venv/bin/ruff check --fix --exit-non-zero-on-fix {all_files}"

[pre-commit.commands.ruff-fmt]
root = "path/to/subproject/"
glob = "*.py"
run = "if ! .venv/bin/ruff format --check {all_files}; then .venv/bin/ruff format {all_files}; false; fi"

[pre-commit.commands.pylint]
root = "path/to/subproject/"
glob = "*.py"
run = ".venv/bin/pylint -rn -sn {all_files}"

[pre-commit.commands.mypy]
root = "path/to/subproject/"
glob = "*.py"
run = ".venv/bin/mypy --strict {all_files}"
```

I don't like having to specify the subdirectory (`path/to/subproject/`) in each entry, since the subproject should not be affected by its place in the hierarchy.

I thought of a way to fix this: Allow writing a variable, say `{mydir}`, in `root`, which will be replaced with the directory containing the source config file. Then, I would be able to have just `root = "{mydir}"` for each entry, instead of repeating the subdir.

WDYT?
