### DISCUSSION TITLE
glob not filtering in post-merge

### DISCUSSION THREAD

**Discussion by mustafa0x** [evilmartians/lefthook#759] [Q&A] [answered]
config:

```yaml
post-merge:
  commands:
    install-deps:
      glob: "package.json"
      run: pnpm install
```

problem: `install-deps` runs after `git pull` even when `package.json` doesn't have changes.

**Comment by mrexox** [comment, marked as answer]
Hey @mustafa0x! For the `post-merge` hook there is no implicit git command to get the changed files. To fix this you can add a `files` option with the git command that gets the files for filtering:

```yml
post-merge:
  commands:
    install-deps:
      files: git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD
      glob: "package.json"
      run: pnpm install
```
