### DISCUSSION TITLE
Possible performance issues with lefthook v1.6.18

### DISCUSSION THREAD

**Discussion by korrat** [evilmartians/lefthook#764] [Q&A] [answered]
After updating `lefthook` (installed from `nixpkgs`) from `v1.6.10` to `v1.6.18`, I'm seeing a 100x slow-down (0.1s to 10s) of my pre-commit hook. The pre-commit hook only has a single command, `treefmt --fail-on-change {staged_files}`.

So far, I've run the `treefmt` command by hand, which is fast (~microseconds).

Furthermore, lefthook leaves some output on the next prompt.

I'd love any help or suggestions to get to the bottom of this.

**Comment by mrexox** [comment]
This is interesting. Could you share you `lefthook.yml` config, so I could try reproduce?

**Reply by korrat** [reply]
Here's the raw `lefthook.yml`.

```yaml
commit-msg:
  commands:
    conform:
      run: '[[ "$(head -n 1 {1})" =~ ^WIP(:.*)?$|^wip(:.*)?$|fixup\!.*|squash\!.*
        ]] ||

        /nix/store/2ml0ywjwfvzd7af0jm7dm3ni291l6l0q-conform-0.1.0-alpha.29/bin/conform
        enforce --commit-msg-file {1}'
      skip:
      - merge
      - rebase
pre-commit:
  commands:
    treefmt:
      run: /nix/store/ivwycrcmgxlka73wi4a43l8dyfnld57g-treefmt-2.0.2/bin/treefmt --fail-on-change
        {staged_files}
      skip:
      - merge
      - rebase
```
