### DISCUSSION TITLE
What is the behavior when there are multiple `stage_fixed` commands and `parrallel: true` is used?

### DISCUSSION THREAD

**Discussion by VanTanev** [evilmartians/lefthook#779] [Q&A]
Hey,

Before trying to experimentally determine this, I thought I'd ask - what is the behavior of lefthook when we have something like the following configuration that uses bot `parallel: true` and `stage_fixed: true` commands:

```yaml
pre-commit:
  parallel: true
  commands:
    lint:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx}" 
      run: pnpm eslint --fix {staged_files}
      stage_fixed: true
    prettier:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx}" 
      run: pnpm prettier --fix {staged_files}
      stage_fixed: true
```

It is possible for the above configuration for both commands to change the same file, so I wanted to know what would lefthook do?
