### DISCUSSION TITLE
Ability to reuse commands between hooks and tasks

### DISCUSSION THREAD

**Discussion by silvenon** [evilmartians/lefthook#797] [Ideas]
I have a `validate` task that lints, checks types etc., and I'd like to reuse that in my `pre-push` hook as well, but I have to settle for:

```yml
validate:
  commands:
    # validation commands

pre-push:
  commands:
    validate: npx lefthook run validate
```

which doesn't provide a command-by-command experience that I would have seen if I had written each command individually. What I'm looking for is something like this:

```yml
validate:
  commands:
    # validation commands

pre-push:
  extends: validate
  commands:
    typescript: null # disable type checking on pre-push because it's slow
```

This way lefthook can copy over the entire configuration, and I can also run it in `npm run validate` if I wanted to etc.

**Comment by mrexox** [comment]
You can use YAML anchors for this purpose: 
- https://github.com/evilmartians/lefthook/discussions/470
- https://github.com/evilmartians/lefthook/discussions/633#discussioncomment-10112421

Or you can explicitly call custom hooks:

```yml
# lefthook.yml

validate:
  commands:
    # ...

pre-push:
  commands:
    validate:
      run: lefthook run validate
```
