### DISCUSSION TITLE
Running some commands in parallel, and some piped, inside a single hook

### DISCUSSION THREAD

**Discussion by silvenon** [evilmartians/lefthook#799] [Ideas]
To me this would be a huge thing for lefthook if you've considered adding it.

I'm aware that I can always split commands across multiple tasks, but running `lefthook run <task>` inside a lefthook command unfortunately results in seeing the command's name until all the subcommands are complete, I don't see the spinners for subcommands, only the summary at the end. I think this is the correct experience considering the circumstances, but not the one I'm looking for.

I was thinking of an API, and the only reasonable one I can come up with is being able to specify _sub-tasks_:

```yml
pre-push:
  piped: true
  commands:
    setup:
      priority: 1
      run: echo "Setting up pre-push"
    validate:
      priority: 2
      parallel: true
      commands:
        eslint:
          run: npx eslint .
        prettier:
          run: npx prettier --check .
        typescript:
          run: npx tsc
```

What do you think?

EDIT: Or, to simplify the schema, it could be something like:

```yml
run:
  parallel: true
  commands:
    eslint:
      run: npx eslint .
    # ...
```

This way you get to keep `run`. It results into more nesting, but I find it cleaner.
