### DISCUSSION TITLE
Better monorepo support

### DISCUSSION THREAD

**Discussion by VanTanev** [evilmartians/lefthook#852] [Ideas]
Hey there!

I have been adopting lefthook in a relatively-large monorepo, but unfortunately it's very unergonomic in terms of configuration. The best I have come up with so far is this:

```yaml
# /lefthook.yml
__shared__:
  commands:
    tsc: &tsc
      run: pnpm tsc --noEmit
    lint: &lint
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx}"
      run: pnpm eslint --max-warnings=0 --report-unused-disable-directives --no-warn-ignored {staged_files}
   # more shared commands here
   
pre-commit:
  parallel: true
  commands:
    "@monorepo-packages/database:tsc": { root: packages/database, <<: *tsc }
    "@monorepo-packages/database:lint": { root: packages/database, <<: *lint }
    # more commands per-package here

    "@monorepo/frontend-nextjs:tsc": { root: apps/frontend-nextjs, <<: *tsc }
    "@monorepo/frontend-nextjs:lint": { root: apps/frontend-nextjs, <<: *lint }

    "@monorepo/frontend-vite:tsc": { root: apps/frontend-vite, <<: *tsc }
    "@monorepo/frontend-vite:lint": { root: apps/frontend-vite, <<: *lint }  
```

I am not aware of a more compact way to define scripts here. 

The above wouldn't be so bad if not for the fact that every time a new package is added the root configuration must be updated. So, even though we have a template for creating packages, we must also manually edit `lefthook.yml`

An ideal solution would probably be to be able to define multiple pattern-matching options in `extends`

```yaml
# /lefthook.yml
extends
 - "apps/*/lefthook.yml"
 - "packages/*/lefthook.yml"
```

```yaml
# /package/database/lefthook.yml
pre-commit:
  parallel: true
  commands:
    tsc:
      run: pnpm tsc --noEmit
    lint:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx}"
      run: pnpm eslint --max-warnings=0 --report-unused-disable-directives --no-warn-ignored {staged_files}
```

And then have those configs merged at runtime.

Does an API like that make sense, and is if so, @mrexox would you be open to patches introducing it?
