### DISCUSSION TITLE
How to exclude specific files/folders from lefthook  or its hooks?

### DISCUSSION THREAD

**Discussion by trabati** [evilmartians/lefthook#880] [Q&A] [answered]
I have a file/folder that I want to commit to git that is also ignored by my Eslint config.
I also have a strict rule, which prevents commits with Eslint warnings. `--max-warnings=0`

My `lefthook.yml` config:
```
pre-commit:
  commands:
    lint:
      glob: "**/*.{js,ts,jsx,tsx}"
      run: npx eslint --max-warnings=0 {staged_files}

```

The issue is, this will produce a Eslin warning:
 ` warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override`

And here I end up in a deadlock, since Eslin warnings are forbidden.

Is there a way to tell lefthook to ignore staged files in specific folders?
Or is there a way to tell Eslint to allow warnings for specific folders or not to throw them at all?

Or any other ideas on how to solve this?

My interim solution is to disable git hooks every time I commit within the ignored folder.
