### DISCUSSION TITLE
how to include a file?

### DISCUSSION THREAD

**Discussion by ianzone** [evilmartians/lefthook#910] [Q&A]
```yml
pre-commit:
  commands:
    typescript:
      glob: "*.{ts,tsx}"
      run: tsc {staged_files} --noEmit
```
this tsc won't read `tsconfig.json`, how to include it?
