### DISCUSSION TITLE
Two separate lefthook.yml

### DISCUSSION THREAD

**Discussion by rado31** [evilmartians/lefthook#949] [Q&A]
There are two folder ```frontend``` and ```backend```. And each of them has own ```lefthook.yml``` file with own commands. I don't want to run fronted's commands in backend and vice versa. I know about ```lefthook-local.yml```, but I could't do that

**Comment by mrexox** [comment]
You should consider [`root`](https://lefthook.dev/configuration/root.html) option which was added right for such cases. Share your configs and I can help you build one lefthook.yml with separated commands for backend and frontend folders.

**Reply by rado31** [reply]
1. lefthook.yml (in the root of the repository)

```yml
pre-commit:
  parallel: true
```

2. lefthook-local.yml (in frontend folder)

```yml
pre-commit:
  commands:
    lint:
      root: # frontend
      run: # command
```

2. lefthook-local.yml (in backend folder)

```yml
pre-commit:
  commands:
    lint:
      root: # backend
      run: # command
```

**Reply by mrexox** [reply]
You can have something like this:

```yml
pre-commit:
  parallel: true
  commands:
    backend-lint:
      root: backend
      run: command
    frontend-lint:
      root: frontend
      run: command
```
