### DISCUSSION TITLE
Fail if files were modified

### DISCUSSION THREAD

**Discussion by WhyNotHugo** [evilmartians/lefthook#954] [Q&A] [answered]
I need `lefthook` to exit non-zero if a hook modified a file. I tried using:

```yaml
pre-commit:
  parallel: true
  commands:
    ruff:
      glob: "*.py"
      run: tox -e ruff
    unchanged:
      run: git diff --exit-code
    …
```

But this is racey, since the last hook needs to run strictly after the others.

Running all hooks without `parallel` could potentially work, but dramatically increases runtime for all hooks.

Is there a way for lefthook to exit non-zero if files have been altered during the execution process? This is actually the default behaviour for py3-pre-commit

**Comment by mrexox** [comment, marked as answer]
I can suggest you using [jobs](https://lefthook.dev/configuration/jobs.html) and [groups](https://lefthook.dev/configuration/group.html) for that:

```yml
# lefthook.yml

pre-commit:
  jobs:
    - group:
        parallel: true
        jobs:
          - glob: "*.py"
             run: tox -e ruff
          - ... # other jobs you want to run in parallel
    - run: git diff --exit-code
```
