### DISCUSSION TITLE
How to avoid git commit if one sub command in parallel a command fails

### DISCUSSION THREAD

**Discussion by OnkarRuikar** [evilmartians/lefthook#961] [Q&A] [answered]
### :zap: Summary

I want to run multiple linters in parallel in pre-commit. But I want to fail the pre-commit if one of the liners fails and git commit won't happen in this case. Consider the following config file:

```yml
pre-commit:
  parallel: true

  commands:
    format-non-md:
      glob: "*.{js,json,yml,yaml,css,html}"
      run: yarn prettier --ignore-unknown --write {staged_files}

    yarn-filecheck:
      glob: "*.{svg,png,jpeg,jpg,gif}"
      run: yarn filecheck {staged_files}

    markdown:
      glob: "*.md"
      run: |
        node scripts/front-matter_linter.js --fix true {staged_files}
        yarn markdownlint-cli2 --fix {staged_files}
        yarn prettier --write {staged_files}
        yarn node scripts/update-moved-file-links.js --check
      fail_text: "Please fix the lining errors before committing."
```

In this case, if `markdownlint-cli2` fails, the commit still happens because, I think, the last subcommand doesn't exit with an error. I want the git commit to happen only if all the linters are completed without an error.

The equivalent shell script of what I want is the following:
```sh
# 'set -e' tells the shell to exit if any of the foreground commands fails
set -eu

pids=()

node scripts/front-matter_linter.js --fix true {staged_files}
pids+=($!)
yarn markdownlint-cli2 --fix {staged_files}
pids+=($!)
yarn prettier --write {staged_files}
pids+=($!)
yarn node scripts/update-moved-file-links.js --check
pids+=($!)

# Wait for each specific process to terminate.
# Instead of this loop, a single call to 'wait' would wait for all the jobs
# to terminate, but it would not give us their exit status.
for pid in "${pids[@]}"; do

  # Waiting on a specific PID makes the wait command return with the exit
  # status of that process. Because of the 'set -e' setting, any exit status
  # other than zero causes the current shell to terminate with that exit
  # status as well.
  wait "$pid"
done
```

Is there an option or setting combination to achieve the above? Or do I have to handle this in a shell script and run the script in the command?

I've tried the following, but I am not sure it is full proof:
```yml
markdown:
      glob: "*.md"
      run: |
        node scripts/front-matter_linter.js --fix true {staged_files}; status1=$?
        yarn markdownlint-cli2 --fix {staged_files}; status2=$?
        yarn prettier --write {staged_files}; status3=$?
        yarn node scripts/update-moved-file-links.js --check; status4=$?
        exit $((status1 + status2 + status3 + status4))
      stage_fixed: true
      fail_text: "Please fix the errors before committing."
```

Is the above approach correct?

**Comment by mrexox** [comment, marked as answer]
@OnkarRuikar , I think you can use `jobs` for this and split your multi-commands into separate jobs:

```yml
pre-commit:
  parallel: true

  jobs:
    - name: format-non-md
      glob: "*.{js,json,yml,yaml,css,html}"
      run: yarn prettier --ignore-unknown --write {staged_files}

    - name: yarn-filecheck
      glob: "*.{svg,png,jpeg,jpg,gif}"
      run: yarn filecheck {staged_files}

    - name: markdown
      glob: "*.md"
      group:
        piped: true
        jobs:
          - run: node scripts/front-matter_linter.js --fix true {staged_files}
          - run: yarn markdownlint-cli2 --fix {staged_files}
          - run: yarn prettier --write {staged_files}
          - run: yarn node scripts/update-moved-file-links.js --check
```

In this case if one job fails the whole group will fail and the pre-commit hook will also fail

**Comment by OnkarRuikar** [comment]
@mrexox Thanks for the info!
The `piped: true` doesn't execute all the linters. It'll force contributors to attempt commit multiple times till they satisfy all the linters _one by one_.

```log
...

|  yarn markdownlint-cli2 --fix {staged_files} (skip) broken pipe
│  yarn prettier --write {staged_files} (skip) broken pipe
│  yarn node scripts/update-moved-file-links.js --check (skip) broken pipe
                                      
  ────────────────────────────────────
summary: (done in 0.32 seconds)       
✔️ format-non-md
🥊 markdown
  🥊 node scripts/front-matter_linter.js --fix true {staged_files}
```

Using `parallel: true` in your code gives me what I wanted: it executes all the linters and prevents commit if any one of the linter fails.


```yml
pre-commit:
  parallel: true

  jobs:
    - name: format-non-md
      glob: "*.{js,json,yml,yaml,css,html}"
      run: yarn prettier --ignore-unknown --write {staged_files}

    - name: yarn-filecheck
      glob: "*.{svg,png,jpeg,jpg,gif}"
      run: yarn filecheck {staged_files}

    - name: markdown
      glob: "*.md"
      group:
        parallel: true         <---------- switched from piped to parallel
        jobs:
          - run: node scripts/front-matter_linter.js --fix true {staged_files}
          - run: yarn markdownlint-cli2 --fix {staged_files}
          - run: yarn prettier --write {staged_files}
          - run: yarn node scripts/update-moved-file-links.js --check
```
Logs:
```log
...

summary: (done in 0.52 seconds)       
✔️ format-non-md
🥊 markdown
  ✔️ yarn prettier --write {staged_files}
  ✔️ yarn node scripts/update-moved-file-links.js --check
  🥊 node scripts/front-matter_linter.js --fix true {staged_files}
  🥊 yarn markdownlint-cli2 --fix {staged_files}

```
