### DISCUSSION TITLE
Monorepo of python projects with pytest

### DISCUSSION THREAD

**Discussion by dbrtly** [evilmartians/lefthook#986] [Q&A] [answered]
I have a monorepo with multiple projects. Let’s assume each uses python and has tests in pytest. 

If any of the py files in a python project has changed, i want to run pytest for that project. 

AND

If there are python projects with zero changed python files, i don't want to run pytest for that project.

Is there a clean lefthook abstraction to handle this scenario?

**Comment by mrexox** [comment, marked as answer]
Hey! Good question. I think you can use a few approaches:

1. Use one lefthook config in the root of the monorepo
2. Use one config in the monorepo root and other configs in subfolders. Import them to the main config

For the first approach I think you can have something like this:

```yml
# lefthook.yml

pre-commit:
  jobs:
    - name: pytest
      glob: "*.py"
      group:
        parallel: true
        jobs:
          - root: 'subfolder1'
            run: pytest
          - root: 'subfolder2'
            run: pytest
          - root: 'subfolder3'
            run: pytest
```

For the second approach:

```yml
# lefthook.yml

extends:
  - subfolder1/lefthook.yml
  - subfolder2/lefthook.yml
```

```yml
# subfolder1/lefthook.yml

pre-commit:
  jobs:
    - run: pytest
      glob: "*.py"
      root: 'subfolder1'
```

```yml
# subfolder2/lefthook.yml

pre-commit:
  jobs:
    - run: pytest
      glob: "*.py"
      root: 'subfolder2'
```

---

I think the first approach is more convenient, since you don't have to duplicate the `glob` and you have pretty similar structure of the subprojects.
