### DISCUSSION TITLE
How to supress `fatal: no upstream configured for branch` error

### DISCUSSION THREAD

**Discussion by ninebolt6** [evilmartians/lefthook#993] [Ideas]
Hello.

I am trying to replace husky with lefthook.
I've encountered one issue and would like to know if there's a possible solution.

Here is my lefthook.yml:
```yaml
pre-push:
  jobs:
    - name: typecheck
      root: "frontend/"
      glob: "*.{ts,tsx}"
      run: npm run tsc # tsc --noEmit
```

When I run `npx lefthook run pre-push`, the execution itself completes without any issues, but I receive the following error log:

```sh
│  > git diff --name-only HEAD @{push}
│    fatal: no upstream configured for branch '(branch name)'
```

https://github.com/evilmartians/lefthook/blob/f07bf6bd4495728cbe81910b7cb1e2d9f2e2db0d/internal/git/command_executor.go#L90-L97

If I use `{all_files}` in `run` command (like `npm run tsc {all_files}`), this error log does not appear. However, the typecheck job then fails, so I would prefer not to use this option.

Could you please let me know if there is a solution to prevent this error log without using {all_files}?
