### DISCUSSION TITLE
How to detect the platform lefthook is running on (Linux/Windows/MacOS), and run scripts specific for each platform?

### DISCUSSION THREAD

**Discussion by cezarlamann** [evilmartians/lefthook#999] [Q&A] [answered]
The question from the title.

So, I have a couple of scripts to check for BOM presence, line length enforcement, copying some files around, etc, and I have Bash and PowerShell versions of each script.

I work with .NET/C# projects, so it is very common for these projects to be open and worked on both Windows and Linux. Given this, I'd like to run the PS scripts only on Windows, and the Bash ones on Linux/MacOS.

I didn't manage to find anything of the sort in the docs, hence the question: Is there a way of identifying the platform that Lefthook is running on, and then, based on this information, run a set of scripts or another?

Thank you!

**Comment by dbrtly** [comment]
Related

https://github.com/evilmartians/lefthook/discussions/991

**Comment by mrexox** [comment, marked as answer]
You can use a workaround I think

```yml
pre-commit:
  jobs:
    - only: 
        - run: uname # only on linux/macos
      script: your-shell-script.sh
    - only: 
        - run: cmd /c ver # only on windows
      script: your-powershell-script.ps1
```

Or with commands

```yml
pre-commit:
  jobs:
    - only: 
        - run: uname # only on linux/macos
      run: echo 'Hello from *nix'
    - only: 
        - run: cmd /c ver # only on windows
      run: echo 'Hello from Windows'
```

You can check the docs on [`skip`](https://lefthook.dev/configuration/skip.html) option, the `only` has similar configuration.

**Reply by cezarlamann** [reply]
I believe this will work. However, on Linux I'll get this error saying "sh: line 1: cmd: command not found". I suppose on Windows I'll get the same with "uname". Is there a way to hide these errors?

**Reply by mrexox** [reply]
Could you file a bug please? I think we shouldn't print such errors to STDERR

**Reply by cezarlamann** [reply]
Hi @mrexox . I'll open a bug.

However, I ended up doing something like [this "hook runner script"](https://github.com/cezarlamann/lefthook-git-hooks/blob/master/.lefthook/hook_runner.sh). This way, it works using the regular Git Bash on Windows, and using regular Bash on other systems.

I don't know how to make it cleaner than this... I tried adding that switch-case statement inside the YAML for each script, but beyond making the script ugly and very verbose, it was throwing some bizarre errors on Git Bash (Windows)

Then, I call it on my YAML like this:

```yaml
output:
  - meta
  - summary
  - empty_summary
  - success
  - failure
skip_lfs: true
pre-commit:
  jobs:
  - name: Check BOM
    run: bash .lefthook/hook_runner.sh pre-commit/check-bom
  - name: Check line lengths
    run: bash .lefthook/hook_runner.sh pre-commit/check-line-length
```
