### ISSUE TITLE
When attempting to execute multi-platform hooks with "only", errors from non-existent commands end up in STDOUT

### ISSUE THREAD

**Issue by cezarlamann** [evilmartians/lefthook#1002]
### :wrench: Summary

When attempting to execute multi-platform hooks with "only", errors from non-existent commands end up in STDOUT

Discussed in #999 

### Lefthook version

1.11.8 fb6a35fc3242654deb3837f1a04a8c786bf3fd11

### Steps to reproduce

Create a YAML file like the one below.

```
pre-commit:
  jobs:
    - only: 
        - run: uname # only on linux/macos
      run: echo 'Hello from *nix'
    - only: 
        - run: cmd /c ver # only on windows
      run: echo 'Hello from Windows'
```

### Expected results

Output from the commands that are supposed to fail on distinct platforms, when they are run with the `only` option, should not appear in the console output

### Actual results

When running on Linux, I get this message in the output:
`sh: line 1: cmd: command not found`

### Possible Solution

Maybe hide the output of commands that are executed inside `only` clauses, when they return anything that is not "success". Maybe add a flag for outputting the outcome of the command, but default it to false
