### ISSUE TITLE
Environment Variables usage in config not detected

### ISSUE THREAD

**Issue by jcnavarrete-konfio** [evilmartians/lefthook#1025]
### **:wrench: Summary**

Environment variables used within path configurations (`source_dir`, `extends`) in `lefthook.yml` are not being expanded or interpreted, preventing the correct loading of configurations and installation of hooks.

### Lefthook version

- `1.11.3 9ee6a56928e128cc224a713c228aca9f145fadd6`

### Steps to reproduce

1.  Create a `lefthook.yml` file in the project root with `source_dir` and/or `extends` directives that use environment variable expansion syntax, e.g.:
    ```yaml
    source_dir: '${LEFTHOOK_CONFIG_DIR:-.konfio/lefthook}'

    extends:
      - '${LEFTHOOK_CONFIG_DIR:-.config/lefthook}/templates/lefthook.nodejs.yml'
    ```
2.  Create the directory structure corresponding to the paths defined, including a dummy extended config file (e.g., `.config/lefthook/templates/lefthook.nodejs.yml`) containing some simple hook definition (e.g., a basic `pre-commit` hook).
3.  Set the environment variable used in the configuration (e.g., `export LEFTHOOK_CONFIG_DIR=".config/lefthook"`).
4.  Run `lefthook install` in the project root.

### Expected results

Lefthook should expand the environment variable `${LEFTHOOK_CONFIG_DIR}` in both the `source_dir` and `extends` paths, locate the extended configuration file (`.config/lefthook/templates/lefthook.nodejs.yml` in this example), and install the hooks defined within it.

### Actual results

Lefthook runs the `install` command, but reports that hooks are synced without any being configured or installed, indicating that the paths specified using the environment variable were not correctly resolved.

```bash
➜ lefthook install
sync hooks: ✔️
````

### Possible Solution

Support for environment variable expansion within path configuration options like `source_dir` and `extends` would allow for more flexible and dynamic configuration based on the project environment or user preferences.

### Logs / Screenshots

Please run the install command with verbose logging and paste the output below:

```bash
➜     LEFTHOOK_VERBOSE=true lefthook install
│ [lefthook] cmd:    [git version]
│ [lefthook] stdout: git version 2.49.0
                                     
│ [lefthook] cmd:    [git rev-parse --path-format=absolute --show-toplevel --git-path hooks --git-path info --git-dir]
│ [lefthook] stdout: /Users/juan.navarrete/dev/konfio/organization/scope/shared/core/konf.io
/Users/juan.navarrete/dev/konfio/organization/scope/shared/core/konf.io/.git/hooks        
/Users/juan.navarrete/dev/konfio/organization/scope/shared/core/konf.io/.git/info         
/Users/juan.navarrete/dev/konfio/organization/scope/shared/core/konf.io/.git              
                                                                                          
│ Searching config in:/Users/juan.navarrete/dev/konfio/organization/scope/shared/core/konf.io
sync hooks: ✔️ 
```

**Comment by mrexox** [comment]
Hey! This looks more like a feature request. But could you please tell more about why you want ENVs to be expanded in the paths? Do you have different paths for LEFTHOOK in different projects?

**Comment by strazto** [comment]
+1 to this-

My use case:
- Team uses some common hooks, and some repo speciific hooks
- for common hooks, there's a centralized hooks repo
- prev system used a simple vanilla git config for hooks (`core.hooksPath` ) 

For each repo, I want to reference common hooks by
```yml
extends:
  - ~/.config/common_git_hooks/branch_names.yml
  # or maybe:
  - "${HOME}/.config/common_git_hooks/jira_prefix_commit_msgs.yml"
  # etc

# as well as repo-specific conventions:
pre-commit:
  # Run sequentially, because it's important to format before linting
  parallel: false
  jobs:
    - name: prettier
      run: yarn prettier --write {staged_files}
      stage_fixed: true
      glob: "*.{js,ts,jsx,tsx}"
      tags:
        - codestyle
        - autofix
    - name: eslint
      run: yarn eslint {staged_files} --fix
      stage_fixed: true
      glob: "*.{js,ts,jsx,tsx}"
      tags:
        - codestyle
        - autofix
```
