### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by just-ads** [evilmartians/lefthook#1029]
It runs too slowly. A simple task that only submits one file takes 20 seconds. Here is the task I configured:
```
pre-commit:
  parallel: true
  jobs:
    - name: '提交处理'
      glob: 'src/**/*.{js,ts,jsx,tsx,json}'
      group:
        jobs:
          - name: '自动修复ESLint问题'
            run: npx eslint --fix {staged_files}
            stage_fixed: true

          - name: '提交检查'
            exclude: '*.json'
            run: npx eslint --rule 'no-console:[error,{allow:[warn,error]}]' {staged_files}
```

This is the running time：

![Image](https://github.com/user-attachments/assets/757ad4bd-60c7-457a-994b-2bec1a5ab5ad)
You can see that it took about 20 seconds to run after submitting only one file.
