### ISSUE TITLE
Some commands clear terminal output

### ISSUE THREAD

**Issue by Tobbe** [evilmartians/lefthook#1047]
### :wrench: Summary

Some commands clear terminal output

### Lefthook version

1.11.14 cae61732d9579feadb8383803c2ea1f54c7aeba0

### Steps to reproduce

```yml
pre-push:
  jobs:
    - run: yarn lint
    - run: yarn format:check
    - run: yarn check
```

### Expected results

All output from all commands + previous output in terminal should remain visible after lefthook finish running

### Actual results

Previous terminal output is cleared. Some of lefthook's output is also gone from the screen

### Logs / Screenshots

This is all I see after the command finishes running

![Image](https://github.com/user-attachments/assets/04f54eb3-130b-4b43-b4df-760dc05ce40d)
