### ISSUE TITLE
Continue with error

### ISSUE THREAD

**Issue by ianzone** [evilmartians/lefthook#1051]
### :zap: Summary

Some jobs may fail but shouldn't block hooks.

### Value

provide `continue` option for each job

### Behavior and configuration changes

```yml
jobs:
  - name: audit
    run: bun audit
    continue: true
```

If run fails, other jobs won't be affected, and there should be warnings about this job in the summary.

**Comment by otg996** [comment]
Just providing some feedback here.

From a UX perspective I support adding a `continue` option.
From my personal biases I don't support it and think it should be the user's responsibility to define this kind of behavior.

In the meantime, you can create non-blocking steps using shell command grouping. This will force a command to succeed while still printing its failure message.

```yaml
# lefthook.yml
  jobs:
    - name: audit
      # Fails with a warning but allows other hooks to run.
      run: bun audit || { echo "⚠️ bun audit failed, but continuing..."; true; }
```

The limitation is that the summary will show `success`.
