### ISSUE TITLE
Environment variables at group level

### ISSUE THREAD

**Issue by paduszyk** [evilmartians/lefthook#1053]
### :zap: Summary

Currently, environment variables can be set at a single command or job level. This issue requests to allow defining them at group level. Then the variables would be accessible for all the group's jobs.

For example:

```yaml
pre-commit:
  jobs:
    # ...
    - name: django
      group:
        jobs:
          - run: |
              uv run python -m django check --fail-level=ERROR
          - run: |
              uv run python -m django makemigrations --check
          - run: |
              uv run python -m django makemessages --all --no-location --no-obsolete
        env:  # <-- this is the group-level declaration
          DJANGO_SETTINGS_MODULE: conf.settings
```

### Value

Solving this issue would improve configuration as allowing to avoid repeated `env` declarations like:

```yaml
pre-commit:
  jobs:
    # ...
    - name: django
      group:
        jobs:
          - run: |
              uv run python -m django check --fail-level=ERROR
            env:
              DJANGO_SETTINGS_MODULE: conf.settings
          - run: |
              uv run python -m django makemigrations --check
            env:
              DJANGO_SETTINGS_MODULE: conf.settings
          - run: |
              uv run python -m django makemessages --all --no-location --no-obsolete
            env:
              DJANGO_SETTINGS_MODULE: conf.settings
```

### Behavior and configuration changes

This would require an update in schema. I believe that this would not be a breaking change.
