### ISSUE TITLE
Feature: scripts: parameters: +

### ISSUE THREAD

**Issue by bbros-dev** [evilmartians/lefthook#121]
Thank you for all the effort you have put into `lefthook`.  It is a great tool - I'm growing to love it.

This would be useful:

```yaml
  scripts:
    "lefthook_terraform_format.sh":
      tags: backend style
      glob:  '*.tf'
      parameters: {staged_files}
```

Current workaround is to have to build the list of staged files in _every_ script.

**Comment by Arkweid** [comment]
Hi, @bbros-dev 
> Current workaround is to have to build the list of staged files in every script.

Is it a slow opetarion in your case?

> parameters

What `parameters` should to do?

**Comment by bbros-dev** [comment]
Thanks for taking the time to look at this.

> Is it a slow opetarion in your case?

Rather a high maintenance issue & inellegant.  One has to re-implement the staged files logic as well as the file extension filter/glob logic.

> What parameters should to do?

Anything you want - they get passed verbatim to the script.
Taking the example above:
```bash
  scripts:
    "lefthook_terraform_format.sh":
      tags: backend style
      glob:  '*.tf'
      parameters: {staged_files}
      runner: bash
```
Would be the same as executing:

```bash
bash lefthook_terraform_format.sh file1.tf file2.tf file3.tf
```

This would also work:

```bash
  scripts:
    "lefthook_terraform_format.sh":
      tags: backend style
      glob:  '*.tf'
      parameters: -p=4 {staged_files} --debug
      runner: bash
```

**Comment by sanmai-NL** [comment]
@bbros-dev What do you mean with build the list? Do you mean adding the placeholder `{staged_files}` to every `run` command?
If `run` value were of type list instead of string in YAML, users could use anchors to create the list per command. That solves a more general problem of repetition.

**Comment by inful** [comment]
It would be nice just to be able to _not_ run the script there are no files for inspection.

**Comment by mrexox** [comment]
I think for this case you can convert the script into a command like this:

**Before**

```yml
# lefthook.yml

pre-commit:
  scripts:
    "lefthook_terraform_format.sh":
      tags: backend style
      glob:  '*.tf'
      runner: bash
```

**After**

```yml
# lefthook.yml

pre-commit:
  commands:
    terraform_format:
      run: bash .lefthook/pre-commit/lefthook_terraform_format.sh {staged_files}
      tags: backend style
      glob:  '*.tf'
```

Why? Some hooks accept parameters from Git. We can't simply replace those parameters with custom parameters because we want the scripts to act like real hook. But those scripts can be executed manually with no issues.

**Comment by joevin-slq-docto** [comment]
Hello @mrexox !
> ```yaml
> # lefthook.yml
> 
> pre-commit:
>   commands:
>     terraform_format:
>       run: bash .lefthook/pre-commit/lefthook_terraform_format.sh {staged_files}
>       tags: backend style
>       glob:  '*.tf'
> ```
This workaround works but it's not convenient in all situations.

In commands, you have to provide the path (`.lefthook/pre-commit/` in the example above).
And in case of a remote hook you have to **guess** the `ref` like:
```yaml
run: bash .git/info/lefthook-remotes/eb5c2b725aeb327d515d59d7eb6edbe00cf8a550/lefthook_terraform_format.sh {staged_files}
```
Which is error prone.
Providing this path is not required when using `script`, but `staged_files` is mandatory to have a fast hook.

**Comment by sanmai-NL** [comment]
It's also not cross-OS compatible.

**Comment by mrexox** [comment]
OK, it makes sense. However there're some implicit arguments for example, for `pre-push` hook, provided by Git itself. I'm afraid simply override the arguments is not convenient too. Appending them to the end will behave differently for `pre-commit` and `pre-push`, so it can be confusing.

Could you tell me more about the use cases? I wonder if there's some other workaround 🤔

**Comment by joevin-slq-docto** [comment]
I've detailed the use case through two branches on a repository :
- https://github.com/joevin-slq-docto/remote-lefthook-hooks/tree/using-script
- https://github.com/joevin-slq-docto/remote-lefthook-hooks/tree/using-run

In a large codebase, prettier in the `using-script` variant will behave very slowly as `{staged_files}` is missing, whereas the variant `using-run` will run fast, but the way the remote mise configuration file is reached is less elegant. See [script](https://github.com/joevin-slq-docto/remote-lefthook-hooks/blob/using-script/.lefthook/pre-commit/prettier.sh#L3C1-L3C56) vs [run](https://github.com/joevin-slq-docto/remote-lefthook-hooks/blob/using-run/lefthook.yml#L14-L15).

**Comment by owpac** [comment]
Hello, is there any news about @joevin-slq-docto's comments? 🙏

**Comment by mrexox** [comment]
OK, looks like there is a need for the feature. I will consider adding `args` option which will overwrite the Git args if present.

Something like this:

```yml
# lefthook.yml

pre-commit:
  scripts:
    "lefthook_terraform_format.sh":
      glob:  '*.tf'
      runner: bash
      args: {staged_files}
```

WDYT?
