### ISSUE TITLE
Support interactive commands

### ISSUE THREAD

**Issue by dotterian** [evilmartians/lefthook#125]
When I try to add [commitizen](https://github.com/commitizen/cz-cli) to `prepare-commit-msg` hook I encounter following problem:
Commitizen is interactive program awaiting input from user into stdin and Lefthook uses `pty` which doesn't  support passing stdin.

Is there any real reason to use `pty` instead of `exec.Command`? ([found this solution here](https://github.com/creack/pty/issues/49))
Anyway, it would be great to have `interactive` option to specify that executing hook should get stdin.
Also, `interactive` shouldn't be mixed with `parallel`, since there can't be several simultaneous interactive processes in one cli.

Alas, I don't know Go and can't write Pull Request myself.

**Comment by chandu-ex** [comment]
Is this feature in the roadmap? I couldn't find options in full-guide to see if there is a way to make it work with commitizen

**Comment by chandu-ex** [comment]
Thanks @mrexox I will try this later tonight and let you know.

**Comment by Chandu** [comment]
@mrexox Please find the repo to replicate the issue @ https://github.com/Chandu/lefthook-commitizen-issue
Here is the recording that depicts the issue I am facing:
 
![Animation](https://user-images.githubusercontent.com/261027/195172591-d116fb75-e3c8-4002-9840-f5e2e21474e6.gif)

You will notice that when I run the git commit, though prepare-commit-msg hook is defined in the lefthook.yml, it is not called by lefthook.
I have called the hook explicitly by issuing the command `npx lefthook run prepare-commit-msg`

**Comment by mrexox** [comment]
Oh, thank you! I will try fixing this, but I can't say when. I hope to get to it within a week or two.

**Comment by mrexox** [comment]
Hey! I am planning to release this feature in 1.2.0. I need to finish a few more tasks before that. Please, feel free to install lefthook from master and check if it works for you.

@Chandu , for your [repo](https://github.com/Chandu/lefthook-commitizen-issue) I had to change lefthook.yml, so it doesn't recursively call `prepare-commit-msg`:

```yml
pre-commit:
  commands:
    test:
      run: npm run test
prepare-commit-msg:
  commands:
    commitzen:
      interactive: true
      run: LEFTHOOK=0 npm run cz-commit # otherwise we fall into endless recursion
commit-msg:
  commands:
    commitlint:
      run: npx commitlint --edit {1}
```

**Comment by Chandu** [comment]
Thanks @mrexox
Could you guide me on hownto install this from master in a nodejs project?
I haven't worked with go, hence need one help here.

**Comment by mrexox** [comment]
@Chandu I am going to release a new version 1.2.0 next week. I think the most convenient way would be to wait until release :)

But if you want to test it for your local environment, you can just do the following:

```bash
# make sure you have go >= 1.19
go version #=> go version go1.19.1 linux/amd64
git clone git@github.com:evilmartians/lefthook
cd lefthook
make
cp lefthook /usr/local/bin # copy to any folder under $PATH
```

**Comment by Chandu** [comment]
Thanks a lot @mrexox

**Comment by Jordan-Hall** [comment]
@mrexox I've tried this on windows and it just ends straight away

```
# Use this to build commit messages
prepare-commit-msg:
  commands:
    commitzen:
      interactive: true
      run: LEFTHOOK=0 && npx cz

# Use this to validate commit messages
commit-msg:
  commands:
    "lint commit message":
      run: npx --no -- commitlint --edit ${1}

pre-push:
  commands:
    packages-audit:
      tags: frontend security
      run: npm audit


# pre-commit:
#   parallel: true
#   commands:
#     eslint:
#       glob: "*.js"
#       run: npm lint -- --fix {staged_files} && git add {staged_files}
```

![image](https://user-images.githubusercontent.com/2092344/218208089-7628ff8d-1795-4c28-a10f-b333af10832c.png)

**Comment by mrexox** [comment]
Hmm, unfortunately I don't have a windows machine to debug this on. Looks like `npx cz` returns an error. Does it return an error without lefthook? What if you try calling it like `lefthook run prepare-commit-msg --verbose`?

**Comment by snorreks** [comment]
I have also this problem on windows, doing `git commit` makes commitzen run and complete instantly.
But running `lefthook run prepare-commit-msg --verbose` works.

**Comment by SIOFOYER** [comment]
Hello, I have the same issue with the last version 1.6.7 (Windows)

- I run `lefthook run prepare-commit-msg` it works
- I run `git commit`, prompt appear without being interactive

Also, I'm not sure why we use `env: LEFTHOOK: 0` ?

Do you have a solution ?

Here is my lefthook.yml
```
prepare-commit-msg:
  commands:
    commitizen:
      interactive: true
      run: cz
      env:
        LEFTHOOK: 0
commit-msg:
  commands:
    commit-lint:
      run: commitlint --edit {1}
pre-commit:
  commands:
    linter:
      run: eslint {staged_files} --fix
      stage_fixed: true
    prettier:
      run: prettier {staged_files} --write
      stage_fixed: true

```

Thanks for your help
