### ISSUE TITLE
Feature request: runner prefixes in local configs

### ISSUE THREAD

**Issue by palkan** [evilmartians/lefthook#127]
We use Lefthook in hybrid development environments: some engineers use local setup, some use [Docker/Dip]().

The base configuration is local-first, so Docker devs use `lefthook-local.yml` with the following contents:

```yml
pre-commit:
  commands:
    rubocop:
      runner: dip {cmd}
    reek:
      runner: dip {cmd}
    slimlint:
      runner: dip {cmd}
    yamllint:
      runner: dip {cmd}
    prettier:
      runner: dip {cmd}
    eslint:
      runner: dip {cmd}
    scsslint:
      runner: dip {cmd}
```

I would like to have something like:

```yml
runner_prefix: "dip "

# or at the group level
pre-commit:
  commands:
    runner_prefix:
       prefix: "dip"
       except:
          - some-non-psrefixable-command
```

Or similar.

@Arkweid What do you think?

**Comment by Arkweid** [comment]
Looks good. But I have my doubts. A new configuration word is being put into config, plus 2 subset words. Three new keywords to achieve some visual improvement.
Potential range of users quite narrow = docker + dip users + "visual beauty requirement".

**Comment by palkan** [comment]
Well, that's the price for flexibility. Putting this declaration into a top-level namespace wouldn't cause any problems due to keywords usages.

I have a crazier idea which could also help to solve this particular issue (but not only): configuration parameters.

```yml
# lefthook.yml
parameters:
  prefix: ""
  something_else: "bla"

pre-commit:
  commands:
    rubocop: "{prefix} bundle exec rubocop"
    # this one doesn't need a prefix
    gitlint: "gitlint"

# lefthook-local.yml
parameters:
  prefix: "dip"
```

More explicit and more flexible at the same time. WDYT?

**Comment by Arkweid** [comment]
Yea, that second variant look awesome. It look cleaner and potentially has a wider range of users.

**Comment by fobiasmog** [comment]
For someone, who like me tryin to make it right now (for hybrid dip/non-dip env's)

```yaml
run: "( [[ -f $(command -v dip) ]] && echo 'dip bundle' || echo 'bundle' ) | xargs -t -I % bash -c '% exec rubocop -c .rubocop.yml --force-exclusion {staged_files}'"
```

if you can rewrite it more elegantly, feel free

**Comment by mrexox** [comment]
From lefthook 1.10.8 you can use [`templates`](https://evilmartians.github.io/lefthook/configuration/templates.html) setting.

```yml
# lefthook.yml

templates:
  prefix: ""

pre-commit:
  commands:
    rubocop: 
      run: "{prefix} bundle exec rubocop"

# lefthook-local.yml
parameters:
  prefix: "dip"
```

**Comment by mrexox** [comment]
@vokshirg , just a little nitpick, your example has a small typo:

```yml
# lefthook-local.yml
pre-commit:
  jobs:
    - name: rubocop
      run: dip bash -c "{cmd}"

# lefthook.yml
pre-commit:
  jobs:
    - name: rubocop
      glob: "*.rb"
      run: "bin/rubocop --force-exclusion --autocorrect {staged_files}"
```

Could you explain in more details, how to you expect the config to work? For this configuration lefthook should merge the `rubocop` commands into one

```yml

# `lefthook dump` result
pre-commit:
  jobs:
    - name: rubocop
      run: dip bash -c "bin/rubocop --force-exclusion --autocorrect {staged_files}"
      glob: '*.rb'
```

**Comment by vokshirg** [comment]
@mrexox Thanks for the quick response. And apologies — I didn’t fully describe the situation.

Our team is split 50/50 between developers working in Docker and on native OS.  
So the configs need to work in both environments. Currently, the `template` works as a prefix:

```yaml
templates:
  wrapper: "dip bash -c"

pre-commit:
  jobs:
    - name: rubocop
      glob: "*.rb"
      run: "{wrapper} bin/rubocop --force-exclusion --autocorrect {staged_files}"
```

In the example above, I’d like to define the wrapper once,  
but I can't do it like this because the actual command also needs to be wrapped in quotes  
so that the final command looks like:

```sh
dip bash -c "bin/rubocop --force-exclusion --autocorrect {staged_files}"
```

Right now it ends up like this:

```sh
dip bash -c bin/rubocop --force-exclusion --autocorrect {staged_files}
```

Which causes the arguments `--force-exclusion --autocorrect {staged_files}` to be passed to `dip` itself.

It might be slightly more convenient to define it like this:

```yaml
templates:
  dip: dip
wrappers:
  wrapper: '{dip} bash -c "{cmd}"'

pre-commit:
  jobs:
    - name: rubocop
      glob: "*.rb"
      wrapper: wrapper
      run: "bin/rubocop --force-exclusion --autocorrect {staged_files}"
```

By the time I got to this version, I had already figured out a working solution.  
Right now, it works like this:

```yaml
# lefthook-local.yml
templates:
  dip: dip
```

```yaml
# lefthook.yml
templates:
  dip: ""

pre-commit:
  jobs:
    - name: rubocop
      glob: "*.rb"
      run: '{dip} bash -c "bin/rubocop --force-exclusion --autocorrect {staged_files}"'
```

This works, but it's a bit noisy — I have around 10 commands like this scattered across the config:

```yaml
run: '{dip} bash -c "bin/rubocop --force-exclusion --autocorrect {staged_files}"'
```
