### ISSUE TITLE
Documentation/Feature request: `git stash` on `pre-commit` and `pre-push`

### ISSUE THREAD

**Issue by 0xCLARITY** [evilmartians/lefthook#131]
I love how fast `lefthook` is, but a problem I'm running into is that my hooks will sometimes fail locally even though they should pass, or pass locally but fail on our CI server because `lefthook` doesn't automatically stash uncommitted changes before running the hooks.

Is there an easy way to configure this manually? (I didn't see one in the examples) Ideally I'd still be able to have `parallel: true`, so wouldn't rely on an order of operations.

**Comment by Arkweid** [comment]
Hi @hbergren 
Take a look at this Discourse examples.
Config:
https://github.com/discourse/discourse/blob/master/lefthook.yml
CI:
https://github.com/discourse/discourse/blob/0872a1182d5702cf24bfce8958fc7cf12339c5ae/.travis.yml#L77

**Comment by hbergren** [comment]
I see. So the only way to do this is to write custom linting scripts in `lefthook.yml` that only run on `staged_files` or some custom selection of files?

I was hoping for an easy way to stash uncommitted changes before and after a hook so that I could let my script functionality live in `package.json` and do something like this:

```yml
pre-push:
  parallel: true
  commands:
    eslint:
      tags: style
      run: npm run lintNoFix
      ...
```

where in package.json: `"lintNoFix": "eslint . --ext .ts --max-warnings 0 && prettier --check '**/*.{md,json}'",`.

But it sounds like the only solution as of right now is to write out something like this:
```yml
pre-push:
  parallel: true
  commands:
    prettier:
      tags: style
      files: git diff --name-only HEAD @{push}
      glob: '*.{md,json}'
      run: npx prettier {files}

    eslint:
      tags: style
      files: git diff --name-only HEAD @{push}
      glob: '*.ts'
      run: npx eslint --max-warnings 0 {files}
```

Is that correct?

**Comment by Arkweid** [comment]
Yea, for my point of view it very strange to commit something after `auto-fixers` without observing changes. A lot of them could broke your code or provide unexpected behaviour.
That is why lefthook doesn't provide that behavior out of the box.

**Comment by oldnote** [comment]
<details>
<summary>Did not understand what you mean re</summary>

> Yea, for my point of view it very strange to commit something after auto-fixers without observing changes. A lot of them could broke your code or provide unexpected behaviour.
That is why lefthook doesn't provide that behavior out of the box.

</details>

Wanna add another example into this conversation.

Often I make a lot of changes in my golang project and then I construct separate commits from them. I want each commit to be a working application, so I've configured pre-commit hook to run unit tests before commit. When I commit a new test but forget to include some modules that this test depends on in the commit then I get false-positive pass from pre-commit hook since those files are available as non-staged changes:
```yml
pre-commit:
  commands:
    task-test:
      glob: "*_test.go"
      run: go test {staged_files}
```

I tried doing stashing manually:
```yml
pre-commit:
  commands:
    task-test:
      glob: "*_test.go"
      run: |
        git stash push -k -u -m "pre-commit stash"
        go test {staged_files}
        git stash pop
```

But it doesn't seem to do anything. Any ideas what I may be doing wrong?

**Comment by oldnote** [comment]
Found a working solution. Not sure about downsides, probably it doesn't run commands in parallel:
```yml
pre-commit:
  commands:
    git-stash:
      priority: 1
      run: git stash push -k -u  # Stash non-staged files

    task-test:
      priority: 2
      glob: "*_test.go"
      run: go test {staged_files}

    git-stash-pop:
      priority: 0  # Run last
      run: git stash pop
```
