### ISSUE TITLE
{cmd} is blank in runner defined in local config

### ISSUE THREAD

**Issue by Envek** [evilmartians/lefthook#145]
Lefthook 0.7.2 installed from npm via `yarn add @arkweid/lefthook --dev`

`lefthook.yml`:

```yml
pre-commit:
  parallel: true
  commands:
    eslint:
      glob: "*.{js,ts}"
      run: yarn run eslint {staged_files}
```

`lefthook-local.yml`:

```yml
pre-commit:
  commands:
    eslint:
      runner: echo dip run {cmd} wtf
```

**Reproduction steps**:

 1. Change some relevant file:

    ```sh
    echo 'whatever' > nevermind.js
    ```

 2. Stage it:

    ```sh
    git add nevermind.js
    ```

 3. Try to commit

    ```sh
    git commit
    ```

**Expected result**:

```
  EXECUTE > eslint
dip run yarn run eslint nevermind.js wtf
```

**Actual result**:

```
  EXECUTE > eslint
dip run wtf
```
