### ISSUE TITLE
Config key `skip_output` not working

### ISSUE THREAD

**Issue by addiebarron** [evilmartians/lefthook#162]
Maybe I'm missing something integral here, but it seems like modular output options are being ignored for my setup. Details here:

`lefthook.yml` at project root: 
```
pre-commit:
  commands:
    commit-colors:
      run: commit-colors $(git rev-parse HEAD)
skip_output:
  - meta
```

sample output after `git commit` or `npx lefthook run pre-commit`:
```
Lefthook v0.7.2
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > commit-colors

       
        Your commit color is Picton Blue
       
#55a9ea


SUMMARY: (done in 0.04 seconds)
✔️  commit-colors
```

The project in question is up-to-date over [here](https://github.com/addiebarron/bananacamp).

Expected behavior is that the version number and hook details would not be displayed. Thank you!!
