### ISSUE TITLE
pre-push hook doesn't  work

### ISSUE THREAD

**Issue by RomanPakhomov** [evilmartians/lefthook#165]
Hello everyone!  I have little issue connected wtih lefthook.  Some information:
1. NodeJS envoirement
2. Version **"@arkweid/lefthook": "^0.7.2"**
3.  My lefthook.yml contains next content `pre-push:
  commands:
    test:
      run: npx cypress run`
4. Then I tryed to trigger lefthook manualy, I see next result (I change some files in src directory):
![image](https://user-images.githubusercontent.com/43703877/110797262-f5bf0880-8289-11eb-8742-602ac7195be1.png)
5. Command **npx cypress run** work correctly

I think that issue connected with git setup maybe, but I checked .git/hooks directory, and see correct pre-push file.
 ```
#!/bin/sh

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

if [ -t 1 ] ; then
  exec < /dev/tty ; # <- enables interactive shell
fi


cmd="lefthook run pre-push $@"

if lefthook -h >/dev/null 2>&1
then
  eval $cmd
elif bundle exec lefthook -h >/dev/null 2>&1
then
  bundle exec $cmd
elif npx lefthook -h >/dev/null 2>&1
then
  npx $cmd
elif yarn lefthook -h >/dev/null 2>&1
then
  yarn $cmd
else
  echo "Can't find lefthook in PATH"
fi

```

**Comment by DmitryTsepelev** [comment]
Hi @RomanPakhomov! Did you check out the [Troubleshooting guide](https://github.com/evilmartians/lefthook/wiki/Troubleshooting#skip-no-files-for-inspecting)? What is the output of `lefthook -v run pre-commit`?

**Comment by mrexox** [comment]
Hey @ShPakvel , now lefthook wants push files to exist or skips the check. Could you share your config and explain your use case with more details?

**Comment by ShPakvel** [comment]
Hey @mrexox! It can be simple like this:
```yml
pre-push:
  follow: true
  piped: true
  commands:
    1_pronto:
      run: bundle exec pronto run --exit-code -c origin/master
    2_rspec:
      run: bundle exec rspec
    3_rswag:
      run: bundle exec rails rswag
    4_open_api_validation:
      run: bundle exec rails openapi:validate
    5_bundler_audit:
      run: bundle exec bundle-audit check --update
```
And it skips even with option `skip_empty: false` like this:
 ```yml
 pre-push:
  follow: true
  piped: true
  commands:
    1_pronto:
      skip_empty: false
      run: bundle exec pronto run --exit-code -c origin/master
    2_rspec:
      skip_empty: false
      run: bundle exec rspec
    3_rswag:
      skip_empty: false
      run: bundle exec rails rswag
    4_open_api_validation:
      skip_empty: false
      run: bundle exec rails openapi:validate
    5_bundler_audit:
      skip_empty: false
      run: bundle exec bundle-audit check --update
 ```
 
 Idea is that we want to be able to run all these check with the same single command `lefthook run pre-push` instead of doing it manually one by one even during development process (when files is not in stage yet nor committed).
 As I wrote, we created separate group `code-quality` that runs the same commands as `pre-push`. And we use it during development.
 The topic I raise here is: why we have to do duplication and remember to adjust all checks in several groups? It is against DRY principle. And in terms of Single Responsibility, it is the same responsibility / feature of "code-quality checks". We just want to be flexible enough to run it not only as protection before push (in `pre-push` hook), but also reuse it during development at any moment.
