### ISSUE TITLE
`npm: not found` when using a git client and nvm

### ISSUE THREAD

**Issue by leettaylor** [evilmartians/lefthook#178]
Since `v0.7.3` it appears Lefthook is struggling to find npm when using a git client (e.g. GitHub Desktop/SmartGit) while using `nvm`. 

_It works as expected when making a commit directly from the command line ~~or when using `v0.7.2`~~._

OS: Ubuntu

## Error
```bash
Commit failed - exit code 1 received, with output: 
Lefthook v0.7.3
RUNNING HOOKS GROUP: pre-commit
⠋ waiting 
1_stylelint (SKIP. NO FILES FOR INSPECTION)
  EXECUTE > 2_eslint
 sh: 1: npm: not found
 3_prettier (SKIP BY BROKEN PIPE)
SUMMARY: (done in 0.01 seconds)
🥊  2_eslint
```

## `lefthook.yml`
```yml
pre-commit:
  piped: true
  commands:
    1_stylelint:
      tags: frontend linting styles
      glob: "*.{scss,vue}"
      run: npm exec -- stylelint {staged_files} --quiet --fix
    2_eslint:
      tags: frontend linting javascript
      glob: "*.{js,vue}"
      run: "npm exec -- eslint {staged_files} --quiet --fix"
    3_prettier:
      tags: frontend formatting styles javascript
      glob: "*.{scss,css,js,vue}"
      run: "npm exec -- prettier --check {staged_files} --write --ignore-unknown"
```

## NPM

We are currently using `nvm` to manage our `npm` installation.

```
❯ which npm
/home/lee/.nvm/versions/node/v15.14.0/bin/npm
```

If we use the standard `npm` package (`sudo apt install nodejs npm`) it works fine.

```
❯ which npm
/usr/bin/npm
```

**Comment by Envek** [comment]
Can you please tell us a bit more details?
 - Which git client you're using and (that's important) how you have installed it (using what package manager: deb, snap, etc).
 - How you have installed lefthook itself? (npm, brew, direct download?)
 - Add one more step to your configto debug things and tell what it outputs:
   ```yaml
     commands:
       0_debug:
         run: echo $PATH 
         # Also try this:
         run: sh -c 'echo $PATH'
   ```

I believe that problem is in environment set up by your git client when it executes git commands (probably with `PATH`)
