### ISSUE TITLE
Monorepos and relative root

### ISSUE THREAD

**Issue by boojum** [evilmartians/lefthook#195]
I'm trying to get `lefthook` to play with my monorepo as per #72. My project structure is as follows:
```sh
├── client
│   ├── const.config.js
│   ├── dist
│   ├── node_modules
│   ├── package.json
│   ├── package-lock.json
│   ├── postcss.config.js
│   ├── prettier.config.js
│   ├── README.md
│   ├── src
│   ├── stylelint.config.js
│   ├── svelte.config.js
│   ├── tsconfig.json
│   ├── webpack.config.js
│   └── webpack.parts.js
├── worker
|   ├── dist
|   ├── node_modules
|   ├── package.json
|   ├── package-lock.json
|   ├── src
|   ├── worker
|   └── wrangler.toml
├── lefthook.yml
├── node_modules
├── package.json
├── package-lock.json
├── README.md

```

The `lefthook` config at the root of the repo:
```yml
skip_output:
  - meta
  - success

pre-commit:
  parallel: true
  commands:
    svelte-check:
      root: 'client/'
      glob: 'src/**/*.{ts,svelte}'
      run: npm run validate {staged_files}
    eslint:
      root: 'client/'
      glob: 'src/**/*.{js,jsx,ts,tsx,json,svelte}'
      run: npm run lint:ts:check {staged_files}
    stylelint:
      root: 'client/'
      glob: 'src/**/*.{css,html,js,md,mjs,svelte,svg,ts}'
      run: npm run lint:css:check {staged_files}
    prettier:
      root: 'client/'
      glob: 'src/**/*.{js,ts,css,json,md,svelte,html}'
      run: npm run format:check {staged_files}
```

When I edit any of the listed files (`js`, `ts`, `svelte`, `css` etc etc), and then try to commit them `lefthook` is not kicking in. When I run `npx lefthook run pre-commit` - with staged relevant files - `lefthook` comes back to me with:
```sh
SUMMARY: (SKIP EMPTY)
```
Any idea what I might be missing here?

**Comment by skryukov** [comment]
Hi, @boojum! Could you provide some additional output:
1) `npx lefthook version`
2) `npx lefthook run pre-commit -v`
3) and maybe `git status` if this is appropriate =)

**Comment by smac89** [comment]
I also had the same problem. The only way to get it to work is to prefix any of the globs with `**/`

**Comment by smac89** [comment]
@skryukov 

> Hi, @boojum! Could you provide some additional output:
> 
>     1. `npx lefthook version`
> 
>     2. `npx lefthook run pre-commit -v`
> 
>     3. and maybe `git status` if this is appropriate =)

```
➜ npx @arkweid/lefthook version
0.7.7
```
```
➜ npx @arkweid/lefthook run pre-commit -v

Lefthook v0.7.7
RUNNING HOOKS GROUP: pre-commit
⠋ waiting 
Files before filters: 
[project/package.json project/src/pages/Dashboard/pets/PetsManager.tsx project/yarn.lock lefthook.yml otherproject/package.json otherproject/yarn.lock]
Files after filters: 
[./src/pages/Dashboard/pets/PetsManager.tsx]
Files after escaping: 
[./src/pages/Dashboard/pets/PetsManager.tsx]

EXECUTE > format-project
/home/user/company/projects/project
project/src/pages/Dashboard/pets/PetsManager.tsx


SUMMARY: (done in 2.10 seconds)
✔️  format-project
```

This is my `pre-commit`:

```yml
pre-commit:
  parallel: true
  commands:
    format-project:
      root: "project/"
      glob: "**/{src,cypress}/**/*.{js,tsx,ts,jsx}"
      run: npx git-format-staged --formatter 'pwd >&2 && echo {} >&2' {staged_files}
```
