### ISSUE TITLE
template_checker script doesn't seem to run when I commit.

### ISSUE THREAD

**Issue by sostenesgomes** [evilmartians/lefthook#199]
lefthook.yml
```
commit-msg:
  scripts:
    "template_checker":
      runner: bash

pre-push:
  parallel: true
  commands:
    tests:
      run: flutter test
    linter:
      run: flutter analyze

pre-commit:
  commands:
    pretty:
      glob: '*.dart'
      run: flutter format {staged_files} && git add {staged_files}
```

.lefthook/commit-msg/template_checker
```
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^(build|ci|docs|feat|fix|perf|refactor|revert|style|test)+: "
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo -e "Invalid commit message.\nCommit message must start with '(build|ci|docs|feat|fix|perf|refactor|revert|style|test):'"
  exit 1
fi

```

When I run commit

```
sostenes@desk:~/source/app$ git commit -m "haha bad commit text"
Lefthook v0.6.3
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > pretty
Unchanged lib/app/core/pages/main/main_page.dart

SUMMARY: (done in 1.02 seconds)
✔️  pretty



[lefthook e26d66e6] haha bad commit text
 2 files changed, 2 insertions(+), 9 deletions(-)

```
