### ISSUE TITLE
Feels kinda slow on Mac mini M1

### ISSUE THREAD

**Issue by muuvmuuv** [evilmartians/lefthook#210]
I switched to an Mac mini M1 and latest Node (16) in our project recently and now lefthook feels really slow when making commits. It is installed through npm. Could it be some binary which is executed through Rosetta?

My config:

```yaml
# https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md

pre-commit:
  parallel: true
  commands:
    # lint-scripts:
    #   glob: "*.{ts,js,html}"
    #   run: node_modules/.bin/eslint {staged_files}
    lint-styles:
      # glob: "*.scss"
      run: node_modules/.bin/stylelint {staged_files}

commit-msg:
  commands:
    lint-commit-msg:
      run: node_modules/.bin/commitlint --edit
```

I have removed some things and tried different configs variations, but it still needs time to boot up and start the hooks. Or.. it is just git ^^?
