### ISSUE TITLE
Parallel doesn't seem to work with scripts

### ISSUE THREAD

**Issue by emersonsiega** [evilmartians/lefthook#211]
Hi

I'm facing an issue... It seems like parallel do not have effect for scripts on pre-push...

```yaml
source_dir: "./.lefthook"

pre-push:
  parallel: true
  scripts:
    "tests_runner":
      runner: bash
    "analyze_runner":
      runner: bash
pre-commit:
  commands:
    pretty:
      glob: '*.dart'
      run: flutter format {staged_files} && git add {staged_files}
commit-msg:
  scripts:
    "template_checker":
      runner: bash
```

Running `lefthook run pre-push` the log shows me a sequential execution.

Console:
```text
Lefthook v0.7.6
RUNNING HOOKS GROUP: pre-push

  EXECUTE > analyze_runner
running analyze in ./base_app
Analyzing base_app...                                                   
No issues found! (ran in 7.3s)
running analyze in ./core
Analyzing core...                                                       
No issues found! (ran in 4.2s)
running analyze in ./dependencies
Analyzing dependencies...                                               
No issues found! (ran in 3.4s)
running analyze in ./onboarding
Analyzing onboarding...                                                 
No issues found! (ran in 3.2s)


  EXECUTE > tests_runner
running tests in ./base_app
00:30 +1: All tests passed!                                                                                                                                                                            
running tests in ./core
00:02 +1: All tests passed!                                                                                                                                                                            
running tests in ./onboarding
00:03 +1: All tests passed!                                                                                                                                                                            


SUMMARY: (done in 45.95 seconds)
✔️  analyze_runner
✔️  tests_runner
```
