### ISSUE TITLE
Lefthook not running hooks when called from sub-directory

### ISSUE THREAD

**Issue by jamiek-acl** [evilmartians/lefthook#215]
My lefthook.yml is in the root, so when I run `lefthook run pre-commit` from the root, all the hooks run:

```
~/$ lefthook run pre-commit
Lefthook v0.7.6
RUNNING HOOKS GROUP: pre-commit
prettier (SKIP. NO FILES FOR INSPECTION)
eslint (SKIP. NO FILES FOR INSPECTION)
```

But when I run it from a subfolder, it seems to not be finding the config file so it is not linting my files when I do a commit:
```
~/client/apps/xxx$ lefthook run pre-commit
Lefthook v0.7.6
RUNNING HOOKS GROUP: pre-commit
SUMMARY: (SKIP EMPTY)

~/client/apps/xxx$ lefthook run asdfghjk1234
Lefthook v0.7.6
RUNNING HOOKS GROUP: asdfghjk1234
SUMMARY: (SKIP EMPTY)
```

How does lefthook look for the config file? I dont want to have to create aliases all over the place. My directory structure is like this:

```
.git/
  hooks/
    commit-msg
    prepare-commit-msg
    pre-commit
.lefthook/
  commit-msg/
    story_number
lefthook.yml
client/
  apps/           # many react apps under here
```

My lefthook.yml looks like this:
```
commit-msg:
  scripts:
    "story_number":
      runner: sh
pre-commit:
  parallel: true
  commands:
    eslint:
      root: "client/"
      glob: "client/apps/**/*.js"
      run: yarn lint {staged_files}
    prettier:
      root: "client/"
      glob: "client/apps/**/*.js"
      run: yarn prettier --check {staged_files}
```

Thanks.
