### ISSUE TITLE
Skip command in pre-commit if no files were changed

### ISSUE THREAD

**Issue by Zebradil** [evilmartians/lefthook#228]
I'm trying to figure out if it's possible to skip a command if no files matching a glob to be committed.

For example:

```yaml
pre-commit:
  commands:
    check-encrypted:
      glob: "*.secret.{yaml,yml}"
      run: ./check-encrypted
```

```console
$ git status --short
 M README.md
 M lefthook.yml
?? README.md.temp

$ lefthook run pre-commit
Lefthook v0.7.5
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > check-encrypted
All *.secret.yaml files are encrypted


SUMMARY: (done in 0.10 seconds)
✔️  check-encrypted
```

Actual behaviour: lefthook invokes the command even if no matching files are changed.
Desired behaviour: lefthook skips the command.
