### ISSUE TITLE
Executable file not found

### ISSUE THREAD

**Issue by bbodenmiller** [evilmartians/lefthook#237]
Trying to run this simple command on Windows but getting the error `exec: "if": executable file not found in %PATH%`

```yml
pre-commit:
  commands:
    passwords:
      glob: "*.{config}"
      run: if grep -c 'password' {staged_files}; then exit 1; fi
```
