### ISSUE TITLE
Blocking execution

### ISSUE THREAD

**Issue by Windrushfarer** [evilmartians/lefthook#238]
Is it possible to set up blocking execution for hooks? For example, I have this config:

```yml
pre-commit:
  parallel: false
  commands:
    lint:
      glob: "*.{js,jsx}"
      run: yarn eslint {staged_files}
   format:
      glob: "*.{js,jsx}"
      run: yarn prettier --write {staged_files}
   add-files:
     run: git add {staged_files}
```

I want these commands to execute in the order I placed them. So if for example, `lint` command fails, the next two won't execute. Right now all commands will be executed even if some of them fail. Is that possible? 

Workaround to this is to place all three scripts into 1 command

```yml
pre-commit:
  parallel: false
  commands:
    check-files:
      glob: "*.{js,jsx}"
      run: yarn eslint {staged_files} && yarn prettier --write {staged_files} && git add {staged_files}
```

But I don't like this approach, the first option is more declarative and there are clear steps of what happening, instead of reading a long script.

Sorry if I missed that information in your full guide.
