### ISSUE TITLE
run hook against changed content only

### ISSUE THREAD

**Issue by bbodenmiller** [evilmartians/lefthook#239]
Lefthook seems focused on running commands against changed files. Unfortunately this causes issues when a user stages some changes then makes more changes but does not stage them then commits the previously staged changes. This can lead to both false positives and false negatives.

For example:
1. Install Lefthook and Sourcetree and create a repo
1. Create `.lefthook.yml in repo`:
  ```yml
  pre-commit:
    commands:
      passwords:
        glob: "*.{config}"
        run: if grep -c 'password' {staged_files}; then exit 1; fi
  ```
1. Create `some.config` file
1. In `some.config` add the word `password`
1. In Sourcetree stage the changes
2. Try to make a commit in Sourcetree and see that it properly fails
3. Remove the word password from `some.config` 
4. Try to make a commit in Sourcetree. Notice that commit works (not desired) and that it commits the word `password` because it was staged before it was removed from `some.config`
