### ISSUE TITLE
Command not found on run

### ISSUE THREAD

**Issue by tomkys144** [evilmartians/lefthook#253]
Hi,
when running pre-commit hook (either by `git commit` or by `lefthook run`) I get "command not found" error although in command line and in shell scripts everything works just fine...

config:
```yml
pre-commit:
  piped: true
  commands:
    1_lint_code:
      glob: '*.dart'
      run: dart fix --apply lib && git add .
    2_format_code:
      glob: '*.dart'
      run: flutter format {staged_files} && git add {staged_files}
```

Shell output:
```bash
Lefthook v0.7.7
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > 1_lint_code
 sh: line 1: dart: command not found


 2_format_code (SKIP BY BROKEN PIPE)

SUMMARY: (done in 0.01 seconds)
🥊  1_lint_code
```

And in none-pipe mode:
```bash
Lefthook v0.7.7
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > 1_lint_code
 sh: line 1: dart: command not found


  EXECUTE > 2_format_code
 sh: line 1: flutter: command not found


SUMMARY: (done in 0.02 seconds)
🥊  1_lint_code
🥊  2_format_code
```

**Comment by mrexox** [comment]
Hey! Do you edit your PATH env in .bashrc or something? Or maybe you have an alias? How are `dart` and `flutter` installed on your system?

**Comment by art-solopov** [comment]
I'm having a similar problem. I've aliased `docker-compose` to `docker compose` but it still doesn't work. Does lefthook not respect aliases?

**Comment by mrexox** [comment]
@art-solopov, did you write an alias in `.bashrc` or `.zshrc`? Lefthook uses `sh` as a shell, this might be a reason.

**Comment by qasim90** [comment]
@mrexox I can print PATH contents from `sh` with `echo $PATH` and it outputs all paths correctly but still Lefthook gives this error `sh: flutter command not found` when trying to commit. What is the solution?

**Comment by mrexox** [comment]
@qasim90 , could you provide more context?

- Where does `flutter` locate?
- What is your `lefthook.yml`?
- What is your `lefthook` version?

Maybe you have a public project, so I could reproduce the issue?

**Comment by mrexox** [comment]
I guess that the issue is related to some $PATH env var tweaks. Try setting [`rc`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#rc) for newest version of lefthook and feel free to open a new issue/discussion if it doesn't help. I am closing this issue.

**Comment by nerder** [comment]
The problem with this is that probably most people define their `.lefthookrc` they do something like that.

`PATH="$PATH:$USER/flutter/bin"`

this will not work with the `"` in the RC files, without the double quotes instead it will work. This is probably an issue with lefthook and how is running commands in a sub-shell. 

@mrexox

**Comment by mrexox** [comment]
@nerder , can you please provide your `lefthook.yml` and .lefthookrc file? It will help me better understand the issue.

**Comment by nerder** [comment]
*lefthook.yml*

```yml
rc: ~/.lefthookrc

pre-push:
  parallel: true
  commands:
    linter:
      run: flutter analyze
    tests:
      interactive: true
      run: flutter test --coverage

pre-commit:
  parallel: true
  commands:
    check-secrets:
      interactive: true
      run: bash -c '${TALISMAN_HOME}/talisman_hook_script pre-commit'
    pretty:
      glob: '*.dart'
      exclude: '.*freezed\.dart|.*g\.dart|.*mocks\.dart'
      run: dart format -l 100 {staged_files} && git add {staged_files}
```

*.lefthook.rc*
```bash
PATH="$PATH:$USER/flutter/bin"
```

This wasn't working while running on latest Ubuntu

**Comment by mrexox** [comment]
@nerder, thank you for the example. Have your tried doing something like `echo $PATH` in one of the `run` options? How does the result change with double quotes and without them?

```yml
# lefthook.yml
...
pre-commit:
  parallel: true
  commands:
    pretty:
      glob: '*.dart'
      exclude: '.*freezed\.dart|.*g\.dart|.*mocks\.dart'
      # print $PATH -- how does this differ with and without quotes?
      run: |
        echo $PATH 
        dart format -l 100 {staged_files} && git add {staged_files}
```
Also, do you have paths like `$USER/flutter/bin`? Shouldn't it be `$HOME/flutter/bin`?
