### ISSUE TITLE
pre push long running tests ends up with remote push errors

### ISSUE THREAD

**Issue by MassivDash** [evilmartians/lefthook#255]
Hello

For pre push hook, I have a build and run tests steps. Everything seemed fine at first but as the tests grew in numbers, I got the following error 

```
SUMMARY: (done in 359.17 seconds)
✔️  tests
✔️  build
Enumerating objects: 99, done.
Counting objects: 100% (72/72), done.
Delta compression using up to 12 threads
Compressing objects: 100% (36/36), done.
Writing objects: 100% (36/36), 280.76 KiB | 3.95 MiB/s, done.
Total 36 (delta 24), reused 0 (delta 0), pack-reused 0
client_loop: send disconnect: Broken pipe
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
```

git push --no-verify works as expected, and changes get pushed. 

I tried using the parallel flag, but this way the actual push cmd does not get triggered at the end at all.

Node 16, Windows and Mac systems

**Comment by MassivDash** [comment]
This is still an issue with 1.05 version 
```
SUMMARY: (done in 354.58 seconds)
✔️  build
✔️  tests
✨  Done in 354.95s.
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 6 threads
client_loop: send disconnect: Broken pipe
send-pack: unexpected disconnect while reading sideband packet
Compressing objects: 100% (10/10), done.
fatal: the remote end hung up unexpectedly
```

I tried to resolve this issue with these stackoverflow answers but with no luck, https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet

**Comment by mrexox** [comment]
Hey! Could you share your code and/or `lefthook.yml` file?

**Comment by MassivDash** [comment]
```
pre-push:
  parallel: false
  commands:
    build:
      tags: Projects builds
      run: npm run build
    tests:
      tags: Run project tests and eslint for whole project
      run: npm run ci:jest

pre-commit:
  parallel: true
  commands:
    linter:
      files: git diff --name-only HEAD @{push}
      glob: '*.{js,ts,jsx,tsx}'
      run: npx eslint {staged_files} --fix
    tests:
      files: git diff --name-only HEAD @{push}
      glob: '*.{js,ts, jsx, tsx}'
      run: jest --findRelatedTests {staged_files} --passWithNoTests

commit-msg:
  commands:
    validate:
      run: npx commitlint  --edit
```
