### ISSUE TITLE
skip_output summary doesn't work

### ISSUE THREAD

**Issue by syabro** [evilmartians/lefthook#258]
STR:
1. Install lefthook
2. `cd tmp; mkdir test; git init; lefthook install`
3. Add `lefthook.yml`
```
# https://github.com/evilmartians/lefthook/
skip_output:
  - summary
test:
  commands:
    frontend-linter:
      run: echo 123
```

see

```
lefthook run test
Lefthook v0.7.7
RUNNING HOOKS GROUP: test

  EXECUTE > frontend-linter
123


SUMMARY: (done in 0.01 seconds)
✔️  frontend-linter
```
