### ISSUE TITLE
Skip merge is not working

### ISSUE THREAD

**Issue by rmachado-studocu** [evilmartians/lefthook#259]
## Issue 
The 
```yml
skip:
  - merge
  - rebase
 ```
does not work as intended.

------
My architecture:
* OS: Darwin (MacOS)
* CPU: arm64
------

I have the following `lefthook.yml`:

```yml
pre-commit:
  parallel: true
  commands:
    exclude-gherkins:
      run: "<command>"
      skip:
        - merge
        - rebase
    eslint:
      glob: "*.{js,ts,jsx,tsx}"
      run: "<command>"
      skip:
        - merge
        - rebase
    stylelint:
      glob: "*.scss"
      run: "<command>"
      skip:
        - merge
        - rebase
    phplint:
      glob: "*.php"
      run: "<command>"
      skip:
        - merge
        - rebase
    shellcheck:
      glob: "*.sh"
      run: "<command>"
      skip:
        - merge
        - rebase

pre-push:
  parallel: true
  commands:
    js-tests:
      skip:
        - merge
        - rebase
      files: git diff --name-only HEAD..master
      glob: "*.{js,ts,jsx,tsx}"
      run: "<command>"
    php-tests:
      skip:
        - merge
        - rebase
      files: git diff --name-only HEAD..master
      glob: "*.php"
      run: "<command>"
    remove-gherkins-label:
      skip:
        - merge
        - rebase
      files: git diff --name-only HEAD..master
      run: "<command>"
```

When installing via `yarn` or via `brew` and having a `merge commit` the binary seems to ignore the `.git/MERGE_HEAD` verification (in the code) and runs the pre-commit commands (all of them have the skip).

However, I forked the repo - to add some logs and try to pinpoint the issue - and made `go build main.go` which created the lefthook binary.
Then I ran the lefthook using the `main` executable (doing `main run pre-commit` and the logs were indeed hitting the right places and it was skipping.

So it seems there must be something going wrong with how the binary is created or how it identifies the git directory...
