### ISSUE TITLE
Feature request: Custom failure message

### ISSUE THREAD

**Issue by bholtbholt** [evilmartians/lefthook#266]
In some cases, especially front-end tools, lint failures can be automated. It would be nice to append a custom failure message when a particular tool fails.

For example:
```yml
pre-commit:
  parallel: true
  commands:
    eslint:
      tags: frontend javascript
      glob: "*.{js,jsx,ts,tsx}"
      runner: yarn eslint {staged_files}
      fail: Try running yarn lint:js --fix to automatically fix these errors
```

Output could look like
``` sh
SUMMARY: (done in 9.76 seconds)
✔️  ujs-limit
✔️  jquery-limit
✔️  prettier
🥊  eslint
    Try running yarn lint:js --fix to automatically fix these errors
✔️  typecheck
```
