### ISSUE TITLE
Skip hook if no subfolder changes

### ISSUE THREAD

**Issue by teodor-appd** [evilmartians/lefthook#272]
I'm trying to skip the `foo` command if there are no changes in the `.foo` folder:

```
  foo:
      skip: git diff --name-only master | if grep --quiet ".foo"; then return false; else return true; fi
      run: echo "bar";
```

The `skip` command doesn't accept any form of the command above, e.g.: returning 0 or 1, not specifying `return`, echo-ing, or returning only true (for testing purposes).

The command returns the correct value locally.

What alternatives do we have?

**Comment by mrexox** [comment]
You can use the `files` option. It accepts the git command to run apply `foo` on. And if it returns no files, the command will be skipped.

Not completely sure it would work, but it might look like this:

```yaml
pre-push:
  commands:
    foo:
      files: git diff --name-only master | grep --quiet ".foo"
      run: echo "bar"
```

Or you can filter the files using `glob` option:

```yaml
pre-push:
  commands:
    foo:
      files: git diff --name-only  $(git merge-base origin/master HEAD)..HEAD
      glob: '.foo/*'
      run: echo "bar"
```
