### ISSUE TITLE
Is a package manager agnostic config possible?

### ISSUE THREAD

**Issue by lukeshiru** [evilmartians/lefthook#274]
Hi!

I was wondering if there's a way of running scripts with a "package agnostic" approach, so I can write something like this:

```yaml
pre-push:
    commands:
        lint:
            run: lint
#or

pre-push:
    commands:
        lint:
            run: run-s lint test
```

Instead of what I found so far...

```yaml
pre-push:
    commands:
        lint:
            run: pnpm lint && pnpm test
#or

pre-push:
    commands:
        lint:
            run: npm run lint && npm run test
#or

pre-push:
    commands:
        lint:
            run: yarn lint && yarn test
```

Thank you! ✨

**Comment by muuvmuuv** [comment]
How about a syntax like justfile or make where an env can be provided to extend PATH?

https://github.com/casey/just#nodejs-packagejson-script-compatibility

```shell
set dotenv-load

export PATH := "./node_modules/.bin:" + env_var('PATH')
```

In yaml maybe:

```yaml
env:
  dotenv: true # or a path `.env.prod`
  path: ["./node_modules/.bin/"] # appended to $PATH
```

**Comment by lukeshiru** [comment]
What I ended up doing is kinda similar to your sugestion:

```yml
# lefthook.yml
pre-push:
    commands:
        "git:pre-push":
            run: $(pwd)/node_modules/.bin/run-s git:pre-push
```
```json5
// package.json
"git:pre-push": "run-s --print-label clean compile lint test document"
```
This way I can configure what I want to run before pushing in `package.json` directly, using other scripts I already have in place (like `clean`, `compile` and so on), and if I need to run them in parallel I use `run-p` from `npm-run-all` instead of the parallel feature of lefthook.

Is not ideal, but is the simplest approach I could think of to make use of the scripts I already have without having to use `npm`, `yarn` or `pnpm` and without duplicating code between `lefthook.yml` and `package.json` (closer to what we used to have with husky@4).
