### ISSUE TITLE
Skip command in `rebase` not working in interactive rebases

### ISSUE THREAD

**Issue by p4checo** [evilmartians/lefthook#279]
I've recently upgraded to version 1.0.0 and enabled skip functionality on merges and rebases for my pre-commit hook, but the hook is still invoked when I do interactive rebases.

My `lefthook.yml`:
```yml
pre-commit:
  parallel: true
  commands:
    swiftlint:
      run: |
        swiftlint --fix;
        (cd FolderA && swiftlint --fix);
        (cd FolderB && swiftlint --fix)
      skip:
        - merge
        - rebase
```

however when I do a `git rebase -i` I still get messages like these:

```
> git rebase -i HEAD~1
Lefthook v1.0.0
RUNNING HOOK: pre-commit
⠙ waiting
```

And I also get messages like this in between rebase commits, despite not having any `prepare-commit-msg` hook configured in `lefthook.yml`...

```
Lefthook v1.0.0
RUNNING HOOK: prepare-commit-msg
```

Can you please help? Thanks! 🙏🏼
