### ISSUE TITLE
LEFTHOOK_EXLUDE environment variable is ignored

### ISSUE THREAD

**Issue by masukomi** [evilmartians/lefthook#295]
see attached screenshot below. I've tried in bash and fish with the same result. I've tried it with 1 hook and multiple separated with a comma. 

excluding via putting `skip: true` in the YAML does work. 

following screenshot is bash. the first line showing that setting the env var for a command is working as expected. the second line shows that it's being ignored. 

![CleanShot 2022-07-10 at 09 56 02@2x](https://user-images.githubusercontent.com/2829/178147958-e833c4ad-7f2b-491d-ac23-48f16e9cdd74.png)

**Comment by mrexox** [comment]
Hey! Could you provide your `lefthook.yml`?

`LEFTHOOK_EXCLUDE` works for tags. For example:

```yaml
pre-commit:
  commands:
    bad_words:
      tags: bad_words # <- This is important
      run: ...
```

Without `tags` LEFTHOOK_EXCLUDE=bad_words won't take an effect.
