### ISSUE TITLE
prepush runs all on setting upstream

### ISSUE THREAD

**Issue by mhozhynewscorp** [evilmartians/lefthook#302]
I will not say that the problem is with Lefthook.
But the examples you can find in the documentation are just that.

I would like to ask for advice or a solution to this situation.

-----------

Suppose we have a mono repository.

We have set up something like this

```yml
pre-push:
  commands:
    a:
      root: "libs/a/"
      files: git diff --name-only HEAD @{push}
      run: npm run test
    b:
      root: "libs/b/"
      files: git diff --name-only HEAD @{push}
      run: npm run test
```

The problem is that when I create a new branch and make changes only for `a` and push it, all the tests run.
In subsequent pushes, this behavior is not observed.

Perhaps there is a more robust way to get the names of the changed files then `git diff --name-only HEAD @{push}`, taking into account `root`.

**Comment by mrexox** [comment]
Hey! Try passing the files to the `npm` if the `test` script supports arguments

```yaml
pre-push:
  commands:
    a:
      root: "libs/a/"
      files: git diff --name-only HEAD @{push}
      run: npm run test {files}
    b:
      root: "libs/b/"
      files: git diff --name-only HEAD @{push}
      run: npm run test {files}
```

**Comment by mhozhynewscorp** [comment]
hey!
that is an extremely specific option. what if I only changed `package.json`?

**Comment by mhozhynewscorp** [comment]
my current sketch is

```sh
if [[ $(git name-rev @{u}) ]]; then return  return $(git diff --name-only HEAD @{push}); else echo "to do"; fi
```

**Comment by mhozhynewscorp** [comment]
Ok, so I came up with such inline bash

```yml
a:
  root: "lib/any"
  files: if [[ $(git name-rev @{u}) ]]; then return $(git diff --name-only HEAD @{push}); else return $(git diff --name-only origin/HEAD HEAD); fi
  run: npm test
```

but it isn't working and seems not running
Is this allowed to put bash here?

**Comment by mrexox** [comment]
Hey!

1. No, you can use sh syntax, but not bash here. 
2. This sounds cool but I find it a bit complicated :thinking: 

What if you try this `git diff` filter? Would it help?

```yaml
pre-push:
  commands:
    a:
      root: "lib/a/"
      files: git diff-tree -r --name-only --diff-filter=CDMR HEAD origin/master # the changed files
      run: npm test {files} # this is important, otherwise it will just run tests without arguments
```
