### ISSUE TITLE
Git submodules doesn't appear in changed files

### ISSUE THREAD

**Issue by BasixKOR** [evilmartians/lefthook#313]
```yml
post-checkout:
  # Update the artifacts of the submodules.
  parallel: true
  commands:
    update-submodules:
      run: printf '%s\n' {all_files}
```

I expected the submodules we're using to appear in the `{all_files}` but it wasn't the case. I think it should display the submodules as well.

**Comment by BasixKOR** [comment]
Perhaps the more reliable way to test this could be:

```yml
post-checkout:
  commands:
    update-submodules:
      files: git submodule foreach --recursive --quiet 'echo $displaypath' # Assuming it runs on the root
      run: printf '%s\n' {all_files}
```
