### ISSUE TITLE
How do I force lefthook to run all hooks on all files?

### ISSUE THREAD

**Issue by tspearconquest** [evilmartians/lefthook#326]
Hi,

New user here. I've been a user of `pre-commit` for some time now and I wanted to try to adapt some third party `pre-commit` hooks for use internally at work via `lefthook` because my team uses `lefthook`.

I'm looking for a command similar to `pre-commit run -a` but for `lefthook` which makes it run all of the hooks on all files in the repo. I use this command with `pre-commit` when I'm adding the pre-commit config to a repo for the first time. This is to ensure that any files already existing in the repo are checked when the hooks are first added.

In the repo where I'm working right now, we already have a `lefthook.yml` and so when I run `lefthook install && lefthook run pre-commit`, I get the below instead of seeing the hooks run:

```
Lefthook v1.1.1
RUNNING HOOK: pre-commit
1_gofmt: (SKIP. NO FILES FOR INSPECTION)
2_goimports: (SKIP. NO FILES FOR INSPECTION)
3_prettier: (SKIP. NO FILES FOR INSPECTION)

SUMMARY: (SKIP EMPTY)
```

I'd like to force the hooks to run without having to stage files for commit or edit the `lefthook.yml`

How can this be accomplished?

**Comment by mrexox** [comment]
Hey! Can you provide your `lefthook.yml` content? I think you have either `files`, or `glob`, or maybe `{staged_files}` template in `run` option. Lefthook checks if there are matching files and skips processing if there are no files.

If you want a workaround for only manual runs, you can have your own "hook", like this:

```yml
pre-commit:
  ...

lints:
  commands:
    gofmt: 
      run: <gofmt command for all files>
```

Then just run `lefthook run lints`

**Comment by tspearconquest** [comment]
Yes, the config does have `{staged_files}` for all 3 hooks.

One hook, the last one, looks like this, and I'm not sure how to adjust it.

```
    3_prettier:
      glob: "*.{js,md,graphql}"
      run: echo {staged_files} | xargs npx prettier --ignore-unknown --write
```

I would normally try to replace the echo with `find .` so that it will match all files but I want to respect the glob expression. How can I make `lefthook` and `find` work together in this case?

**Comment by tspearconquest** [comment]
I did some testing and figured this out.

```
lints:
  parallel: false
  commands:
    1_gofmt:
      glob: "*.go"
      run: gofmt -l -w . {all_files}
    2_goimports:
      glob: "*.go"
      run: goimports -l -w . {all_files}
    3_prettier:
      glob: "*.{js,md,graphql}"
      run: echo {all_files} | xargs npx prettier --ignore-unknown --write
```
