### ISSUE TITLE
Project structure with node_modules on sub directory

### ISSUE THREAD

**Issue by LucianoVandi** [evilmartians/lefthook#331]
I have several projects where the node_modules folder doesn't live in the root of the project, but it's inside a sub-folder called "src".

While debugging I found that the call_lefthook method sets the `$dir` variable with `git rev-parse --show-toplevel`. This would look for `node_modules` inside the root, and if won't find it try to install it globally with npx.

Maybe I'm wrong, but wouldn't it be more appropriate to search directly for the `node_modules` folder?

**Comment by mrexox** [comment]
Hey, there is a `root` option for commands and scripts, and it was make for these situations. 

Assuming you have the following structure:

```
├── lefthook.yml
└── src
    ├── index.js
    └── node_modules
```

The configuration will look like this:

```yaml
# lefthook.yml
pre-commit:
  commands:
    lint:
      root: "src/"
      run: npx eslint --fix {staged_files} && git add {staged_files}
```

You can provide your lefthook.yml, and I can debug it if something doesn't work.

**Comment by LucianoVandi** [comment]
Thanks @mrexox! I didn't notice this option, but it seems to refer to the execution of a specific command or script. 

In my case, I would like to add lefthook as a project dependency, where dependencies live in `/src/node_modules`. 

Since the git toplevel directory is /, when the git-hook runs lefthook, it doesn't find the executable (in / there is no node_modules folder) and therefore reaches the last elif where npx install lefthook globally.

```
├── .git/
├── lefthook.yml
└── .lefthook/pre-commit
    ├── test.sh
└── src
    ├── index.js
    └── node_modules
        ├── .bin/lefthook
        ├── lefthook/
        ├── lefthook-darwin-x64/
```

I hope I have explained. Here is the lefthook.yml file:

```yml
pre-commit:
  scripts:
    "test.sh":
      runner: bash
```
