### ISSUE TITLE
Error using {push_files}

### ISSUE THREAD

**Issue by cloudmatt** [evilmartians/lefthook#374]
### Summary

Whenever I pass the `{push_files}` argument to a `run:` in the `pre-push` section I just get this error message that says `error replacing {push_files}: exit status 128`

### Steps to reproduce

Here's the relevant sections my `lefthook.yaml` file:
```yaml
---
skip_output:
  - meta       # Skips lefthook version printing
  - success    # Skips successful steps printing
pre-push:
  parallel: true
  commands:
    shellcheck:
      tags: sast
      glob: "*.sh"
      run: scripts/shellcheck.sh {push_files}
```

Contents of `shellscheck.sh` though I'm sure it doesn't matter because it happens no matter what I use but adding for completeness sake:
```shell
#!/usr/bin/env bash
set -euo pipefail

if ! command -v shellcheck > /dev/null; then
  echo "WARN: shellcheck is not installed. Installing....."
  if [[ "$(uname)" == "Darwin" ]]; then
    if ! command -v brew > /dev/null; then
      echo "ERROR: Homebrew isn't installed. Please see https://docs.brew.sh/Installation for instructions."
      exit 1
    else
      brew install -q shellcheck
    fi
  else
    echo "ERROR: Non macOS operating systems not supported at this time. Feel free to open a PR and extend this check :)"
  fi
fi

for file in "$@"
do
  shellcheck -o all "${file}"
done
```
### Expected results

I expect it to not error? lol. I know the file i'm testing should cause an error to return from my script. I've also tried other scripts in the `run` directive and the same results.. anytime I reference the `{push_files}` I get that same error.

### Actual results

I make adjustments to a `*.sh` file and when I try to push up the change to remote up I get the error [snipped branch name details]:
```shell
➜  git push origin BRANCH_NAME
error replacing {push_files}: exit status 128
shellcheck: (SKIP. ERROR)

refs/heads/style/BRANCH_NAME branch_sha refs/heads/style/BRANCH_NAME branch_sha

SUMMARY: (done in 0.09 seconds)
```

### Possible Solution

🤷🏻
