### ISSUE TITLE
Prettier works incorrectly with lefthook

### ISSUE THREAD

**Issue by alexandrsashin** [evilmartians/lefthook#415]
### :wrench: Summary

I have lefthook.yml
```
pre-commit:
  piped: true
  commands:
    prettier:
      glob: "*.js"
      run: npx prettier {staged_files} --ignore-unknown --write
    eslint:
      glob: "*.js"
      run: npx eslint {staged_files} --fix
```
with such file stucture:
```
lefthook.yml
/frontend
-prettierrc.js
-eslintrc.js
-package.json
-example.js
```
`eslint` works perfectly, but `prettier` works endlessly.

https://github.com/alexandrsashin/lefthook-config

### Lefthook version

Lefthook v1.2.6

### Steps to reproduce

Read above.

### Expected results

Prettier should work correctly, fits code on rules and stops after several ms / s.

**Comment by mrexox** [comment]
Hey! Thank you for the issue. I tried it myself, and I noticed that npx suggests me to install those utilities (and waits for the input `y`), so that's why it waits endlessly. You can see this if you slightly change the config:

```yml
pre-commit:
  piped: true
  commands:
    prettier:
      glob: "*.js"
      interactive: true # don't suppress output and connect to the terminal STDIN
      run: npx prettier {staged_files} --ignore-unknown --write
    eslint:
      glob: "*.js"
      interactive: true
      run: npx eslint {staged_files} --fix
```

Lefthook doesn't work interactively by default and suppresses all the output until the command finishes. That's why it looks like it runs endlessly.

Once you install the `prettier` it won't ask again. But I recomment adding those packages as dependencies to your package.json, and execute them via `npm run` or `yarn run`.

Big thanks for providing a repo with an example! This is really helpful!

I am not sure this is a bug of lefthook, but there might be a room for a feature, like some execution timeout, or STDIN detection. WDYT?

**Comment by alexandrsashin** [comment]
There was a mistake in `root` property value. Such config works correctly => I close this issue.
```
pre-commit:
  piped: true
  commands:
    prettier:
      root: frontend/
      glob: "*.js"
      interactive: true
      run: yarn prettier {staged_files} --ignore-unknown --write
    eslint:
      root: frontend/
      glob: "*.js"
      interactive: true
      run: yarn eslint {staged_files} --fix
```
@mrexox, thanks for help.)
