### ISSUE TITLE
Memory leak if run `lefthook run` inside command

### ISSUE THREAD

**Issue by strpc** [evilmartians/lefthook#425]
### :wrench: Summary

Hi! I'm see a memory leak if run `lefthook run` inside lefthook command.

### Lefthook version

1.2.7, 1.2.8

### Steps to reproduce

Example config:
```yml
pre-commit:
  commands:
    format:
      run: lefthook run format

format:
  piped: true
  parallel: false
  commands:
    # number prefix used to save ordering
    1_autoflake:
      glob: "*.py"
      run: autoflake --recursive --ignore-init-module-imports --remove-all-unused-imports --remove-unused-variables --in-place {staged_files}
    2_isort:
      glob: "*.py"
      run: isort --color --quiet {staged_files}
    3_black:
      glob: "*.py"
      run: black {staged_files}
    4_pyup_dirs:
      glob: "*.py"
      run: pyup_dirs --py311-plus {staged_files} | true
    4_black_check:
      glob: "*.py"
      run: black --check {staged_files}
```

### Expected results

Low memory usage 

### Actual results

High memory usage

### Screenshots (if appropriate)

1.2.6:
<img width="372" alt="Screenshot 2023-02-10 at 18 49 10" src="https://user-images.githubusercontent.com/56894629/218135082-bc90e615-7def-4367-a7b0-64b205ee06c4.png">

1.2.7:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/56894629/218137744-a06a94b2-8991-4c51-a283-5029557046a0.png">

1.2.8:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/56894629/218135820-febbc571-d651-412f-b318-055fd91c7c95.png">
