### ISSUE TITLE
Lefthook on windows can run powershell/pwsh as a runner

### ISSUE THREAD

**Issue by j-byrnes** [evilmartians/lefthook#428]
### :wrench: Summary

When attempting to run Lefthook on Windows, it doesn't seem to identify/see the config file.

### Lefthook version

1.2.9 0e6aa810510174063b6040b07e3cbdd9c78fba45

#### Install

 - Download [lefthook_1.2.9_Windows_x86_64.exe](https://github.com/evilmartians/lefthook/releases/download/v1.2.9/lefthook_1.2.9_Windows_x86_64.exe) > C:\Lefthook
 - Add to Path: 
```powershell
$Path = [Environment]::GetEnvironmentVariable("PATH", "User") + [IO.Path]::PathSeparator + "C:\Lefthook"
[Environment]::SetEnvironmentVariable( "Path", $Path, "User" )
```

#### Prepare Repo
```powershell
push-location c:\repo

lefthook_1.2.9_Windows_x86_64.exe install

lefthook_1.2.9_Windows_x86_64.exe add commit-msg

tree
C:\REPO
├───.lefthook
│   └───commit-msg
└───.lefthook-local
    └───commit-msg

```

#### Files

- **repo\lefthook.yml**
```yaml

# 'pwsh.exe -NoProfile -ExecutionPolicy Bypass -File ".\convcoGitHook.ps1 -MessagePath '$1'"'
commit-msg:
  conventional-commits-check:
    scripts:
      "convcoGitHook.ps1":
        runner: pwsh.exe -NoProfile -ExecutionPolicy Bypass -File
```
- **repo\.lefthook\commit-msg\convcoGitHook.ps1**
```powershell

Write-Host "convcoGitHook.ps1 EXECUTED!!!!"

```

### Expected results

```
> lefthook_1.2.9_Windows_x86_64.exe run commit-msg -v
Lefthook v1.2.9
SYNCING
SERVED HOOKS: commit-msg
RUNNING HOOK: commit-msg
convcoGitHook.ps1: (???Executing???)

convcoGitHook.ps1 EXECUTED!!!!

SUMMARY: (???NOT EMPTY???)

>
```

### Actual results

```
> lefthook_1.2.9_Windows_x86_64.exe run commit-msg -v
Lefthook v1.2.9
SYNCING
SERVED HOOKS: commit-msg
RUNNING HOOK: commit-msg
convcoGitHook.ps1: (SKIP BY NOT EXIST IN CONFIG)

SUMMARY: (SKIP EMPTY)

>
```
### Possible Solution

It is as if the config file isn't getting picked up/read/processed. The file `lefthoook.yml` is located in the root of the repo `c:\repo` which was the location it was created during `install.`

`-v` argument doesn't seem to include any additional output, 

Per [usage](https://github.com/evilmartians/lefthook/blob/master/docs/usage.md#local-config) and [configuration](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md), I haven't been able to validate all the configuration file names/locations it would check.

While I'm not a Go programmer, I'm happy to do the heavy lifting on any/all testing for Windows since I know it's not the main focus.

- at the end of the day, I'm trying to use pwsh.exe as a runner (possibly with some parameters)
- validate the correct configuration file location that is expected.

**Comment by j-byrnes** [comment]
Yeah, I included it above, **`repo\lefthook.yml`**

But here it is (in it's entirety;I did remove the default content)

```yaml
# 'pwsh.exe -NoProfile -ExecutionPolicy Bypass -File ".\convcoGitHook.ps1 -MessagePath '$1'"'
commit-msg:
  conventional-commits-check:
    scripts:
      "convcoGitHook.ps1":
        runner: pwsh.exe -NoProfile -ExecutionPolicy Bypass -File
```

I get the same result if I use the above runner or one of the following:

```yaml
        runner: pwsh.exe

#OR

        runner: pwsh

```

**Comment by mrexox** [comment]
Hey! I guess you've misconfigured `lefthook.yml`. Could you try this?
```yml

# 'pwsh.exe -NoProfile -ExecutionPolicy Bypass -File ".\convcoGitHook.ps1 -MessagePath '$1'"'
commit-msg:
  scripts:
    "convcoGitHook.ps1":
      runner: pwsh.exe -NoProfile -ExecutionPolicy Bypass -File
```

There is `conventional-commits-check:` key that breaks the config format (although no error is thrown :thinking:)

**Comment by j-byrnes** [comment]
Ok, Made the change to lefthook.yml
```yml
# 'pwsh.exe -NoProfile -ExecutionPolicy Bypass -File ".\convcoGitHook.ps1 -MessagePath '$1'"'
commit-msg:
  scripts:
    "convcoGitHook.ps1":
      runner: pwsh.exe -NoProfile -ExecutionPolicy Bypass -File
```
Results: No change

```
> lefthook_1.2.9_Windows_x86_64.exe run commit-msg -v
Lefthook v1.2.9
SYNCING
SERVED HOOKS: commit-msg
RUNNING HOOK: commit-msg
convcoGitHook.ps1: (SKIP BY NOT EXIST IN CONFIG)

SUMMARY: (SKIP EMPTY)
```
