### ISSUE TITLE
Since v1.3.0 the files command seems to not parse correctly anymore (error replacing {files}: exit status 128)

### ISSUE THREAD

**Issue by toebgen** [evilmartians/lefthook#433]
### :wrench: Summary

Since v1.3.0 the [files command](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#files-global) seems to not parse correctly anymore. It yields `error replacing {files}: exit status 128` instead.

### Lefthook version

`1.3.0`

### Steps to reproduce

Make use of the `files` command in `lefthook.yaml`, as in this minimal example:

```
pre-commit:
  commands:
    using_files:
      # Skip this in case there are changes in packages/ folder only
      files: git diff --staged --name-only | awk '!/packages/' || echo ''
      run: lefthook run other_hook
```

### Expected results

With version `1.2.9` I receive the following result, which is expected:

```
⇒  lefthook run pre-commit --verbose
Lefthook v1.2.9
RUNNING HOOK: pre-commit
using_files: (SKIP. NO FILES FOR INSPECTION)

SUMMARY: (SKIP EMPTY)
```

### Actual results

The latest release `1.3.0` yields the following result:

```
⇒  lefthook run pre-commit --verbose
[lefthook] cmd: [git rev-parse --show-toplevel]
[lefthook] err: <nil>
[lefthook] out: /[...]/lefthook_demo

[lefthook] cmd: [git rev-parse --git-path hooks]
[lefthook] err: <nil>
[lefthook] out: .git/hooks

[lefthook] cmd: [git rev-parse --git-path info]
[lefthook] err: <nil>
[lefthook] out: .git/info

[lefthook] cmd: [git rev-parse --git-dir]
[lefthook] err: <nil>
[lefthook] out: .git

Lefthook v1.3.0
RUNNING HOOK: pre-commit
[lefthook] cmd: [git status --short]
[lefthook] err: <nil>
[lefthook] out:
[lefthook] cmd: [git diff --staged --name-only | awk '!/packages/' || echo '']
[lefthook] err: exit status 128
[lefthook] out: fatal: ambiguous argument '|': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

error replacing {files}: exit status 128
using_files: (skip) error
[lefthook] cmd: [git stash list]
[lefthook] err: <nil>
[lefthook] out:

SUMMARY: (SKIP EMPTY)
```
