### ISSUE TITLE
Exclude option not working if no staged_files use

### ISSUE THREAD

**Issue by ctjhoa** [evilmartians/lefthook#441]
### :wrench: Summary

I want to exclude files from a lefthook command but I do not use files variable in my `run` command line. 

### Lefthook version

`1.2.7 c88a009cfa095e97ce47f8c5d5e1db5e6c844341`

### Steps to reproduce

```yml
# lefthook.yml
pre-commit:
  parallel: true
  commands:
    lint:
      tags: lint projects
      exclude: 'apps/memory-360.*'
      glob: '*.{ts,tsx,js,jsx,rb,ru}'
      run: yarn affected:lint --uncommitted
```

### Expected results

`run` should not be executed when an excluded file is affected.

### Actual results

`run` is always executed.

### Possible Solution

I found a workaround by turning my lefthook config into this
```yml
# lefthook.yml
pre-commit:
  parallel: true
  commands:
    lint:
      tags: lint projects
      exclude: 'apps/memory-360.*'
      glob: '*.{ts,tsx,js,jsx,rb,ru}'
      run: yarn affected:lint --uncommitted && echo {staged_files} > /dev/null
```

### Screenshots (if appropriate)

Actual results
![2023-03-03-170524_1278x113_scrot](https://user-images.githubusercontent.com/1716173/222768911-7ea2c31d-32d1-4fe9-b043-417af91b20d6.png)

With workaround

![2023-03-03-170501_1269x335_scrot](https://user-images.githubusercontent.com/1716173/222768907-23e29b7f-425d-4f4e-8e2a-3c99564e5c0d.png)
