### ISSUE TITLE
Add a option to skip the command if the file list is empty

### ISSUE THREAD

**Issue by robsonpeixoto** [evilmartians/lefthook#446]
### :zap: Summary

Sometimes is very annoying compile the project just because you change the Dockerfile or a README.
Now the Command is only skipped if the `{files}` template is used, but sometimes is not possible to use it on the `run` configurations.

### Behavior and configuration changes

Add a configuration to skip the command if the list of files is empty. Example:
```yml
pre-commit:
  parallel: true
  commands:
    compile_1st_suggestion:
      glob: "*.{ex,exs}"
      run: mix compile
      skip_empty: {staged_files}
      env:
        MIX_ENV: prod
    compile_2nd_suggestion:
      glob: "*.{ex,exs}"
      run: mix compile
      skip:
        - is_empty: {staged_files}
      env:
        MIX_ENV: prod
```
