### ISSUE TITLE
The stage_fixed option doesn't work when combined with the root option

### ISSUE THREAD

**Issue by kombucha** [evilmartians/lefthook#447]
### Lefthook version

`1.3.5`

### Steps to reproduce

Given the following `lefthook.yml`

```yml
pre-commit:
  commands:
    optimize-svgs:
      root: project-a/
      glob: '*.svg'
      stage_fixed: true
      run: yarn svgo {staged_files}
```

### Expected results

`svgo` runs on my svgs which are then automatically added to the commit

### Actual results

I'm getting the following error

```
Couldn't stage fixed files:exit status 128
```

### Possible Solution

I think it's due to the fact that `staged_files` are relative to the `root` option, but the `git add` command is ran from the root folder.

So say this file was part of the fixed staged_files:
`project-a/assets/some.svg`

`lefthook` tries to run the following command

```
# from /
git add ./assets/some.svg
```

Since the file doesn't exist, git returns the error code `128`

A possible solution would be to fix the paths passed to [`Repository#addFiles`](https://github.com/evilmartians/lefthook/blob/ce9930f73e80af2b65b6f3465422b0c91f3ff0ee/internal/git/repository.go#L275) beforehand.

### Screenshots (if appropriate)

N/A
