### ISSUE TITLE
Split `skip_output.execution` into two options 

### ISSUE THREAD

**Issue by hustcer** [evilmartians/lefthook#473]
### :zap: Summary

```yaml
# lefthook.yml

skip_output:
  - execution  # Skips printing successfully executed commands and their output (but still prints failed executions)
```
As the config comment says `skip_output.execution` will skip printing successfully executed commands and their output, can this config option be split into two parts, something like:

```yaml
# lefthook.yml

skip_output:
  - execution      # Skips printing successfully executed commands
  - cmd_output     # Skips printing successfully executed commands' output (but still prints failed executions)
```

### Value

I don't want to know what has been executed, as if I saw the output I will know what's happenning.

**Comment by hustcer** [comment]
I think this option will allow the user to decide by themselves what can be output and will make this tool more user friendly

**Comment by mrexox** [comment]
Hey! Thank you for the feature request. I decided to slightly change the option - `execution_out`. Does it feel OK for you?

**Comment by hustcer** [comment]
Yes, Great, Thanks for the quick fix

**Comment by hustcer** [comment]
It's weird that it does not work as expected after upgrade to the latest version:
```yaml
min_version: 1.3.11
color: false
no_tty: false
skip_output:
  - meta              # Skips lefthook version printing
  - skips             # Skips "skip" printing (i.e. no files matched)
  - summary           # Skips summary block (successful and failed steps) printing
  - success           # Skips successful steps printing
  - failure           # Skips failed steps printing
  - execution         # Skips printing successfully executed commands
  # - execution_out   # Skips printing successfully executed commands' output (but still prints failed executions)
pre-push:
  follow: true # need to use follow to get stdin from git push
  scripts:
    'sync.sh':
      runner: sh
```
For me when I set skip `execution` then the execution output be skipped too.
When I disable skip `execution` and enable skip `execution_out` everything works as 1.3.10 with skip `execution` disabled: the executed commands and it's output been displayed

**Comment by mrexox** [comment]
Hmm I guess I haven't handled the case when you use `follow`/`interactive` option. Let me fix that.

**Comment by hustcer** [comment]
Hi, thanks for the new release, I have just tried `1.3.12`, but still no luck.

**Comment by mrexox** [comment]
I've tried your config, and it worked for me:

```yml
skip_output:
  # - meta              # Skips lefthook version printing
  # - skips             # Skips "skip" printing (i.e. no files matched)
  # - summary           # Skips summary block (successful and failed steps) printing
  # - success           # Skips successful steps printing
  # - failure           # Skips failed steps printing
  # - execution         # Skips printing successfully executed commands
  - execution_out   # Skips printing successfully executed commands' output (but still prints failed executions)
pre-push:
  follow: true # need to use follow to get stdin from git push
  scripts:
    'sync.sh':
      runner: sh
```

```bash
$ cat .lefthook/pre-push/sync.sh
echo waiting...
sleep 1
echo done
sleep 1

$ lefthook run pre-push
Lefthook v1.3.12
RUNNING HOOK: pre-push

  EXECUTE >  sync.sh

SUMMARY: (done in 2.02 seconds)
✔️  sync.sh
```

What do you see if you remove all `skip_output` settings?

**Comment by hustcer** [comment]
My sync.sh:
```bash
#!/bin/sh
# Author: hustcer <hustcer@outlook.com>
# Date:   2021/09/29 17:52:58 +0800
# Git pre push hooks, need just/nu and related nu scripts to run.

# set -exo pipefail

while read -t 2 -s local_ref local_oid remote_ref remote_oid
do
  echo waiting...
  echo $local_ref
  sleep 1
  echo done
  sleep 1
done

exit 0
```
Config:
```yaml
min_version: 1.3.12
color: false
no_tty: false
# skip_output:
#   - meta              # Skips lefthook version printing
#   - skips             # Skips "skip" printing (i.e. no files matched)
#   - summary           # Skips summary block (successful and failed steps) printing
#   - success           # Skips successful steps printing
#   - failure           # Skips failed steps printing
#   - execution         # Skips printing successfully executed commands
  # - execution_out   # Skips printing successfully executed commands' output (but still prints failed executions)
pre-push:
  follow: true        # need to use follow to get stdin from git push
  scripts:
    'sync.sh':
      runner: sh
```
Output:
```console
Lefthook v1.3.12
RUNNING HOOK: pre-push

  EXECUTE >  sync.sh
refs/heads/feature/sync 98c0a7490b34d901573ce709dcfe612beec4854c refs/heads/feature/sync 5498b11eb3a7ea2a17ef215914591f3ef5d4f396
waiting...
refs/heads/feature/sync
done

SUMMARY: (done in 4.04 seconds)
✔️  sync.sh
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 332 bytes | 166.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
To https://...............
```

**Comment by hustcer** [comment]
With this config:
```yaml
min_version: 1.3.12
color: false
no_tty: false
skip_output:
  - meta              # Skips lefthook version printing
  - skips             # Skips "skip" printing (i.e. no files matched)
  - summary           # Skips summary block (successful and failed steps) printing
  - success           # Skips successful steps printing
  - failure           # Skips failed steps printing
  - execution         # Skips printing successfully executed commands
  # - execution_out   # Skips printing successfully executed commands' output (but still prints failed executions)
pre-push:
  follow: true        # need to use follow to get stdin from git push
  scripts:
    'sync.sh':
      runner: sh
```
Got output:
```console
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 322 bytes | 80.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
To https://................
   98c0a749..6fd2c285  feature/sync -> feature/sync
```

BTW: I'm using `git push` to do a real push

**Comment by mrexox** [comment]
Ok, and what do you see with this config?

```
min_version: 1.3.12
color: false
no_tty: false
skip_output:
  - meta              # Skips lefthook version printing
  - skips             # Skips "skip" printing (i.e. no files matched)
  - summary           # Skips summary block (successful and failed steps) printing
  - success           # Skips successful steps printing
  - failure           # Skips failed steps printing
  # - execution         # Skips printing successfully executed commands
  - execution_out   # Skips printing successfully executed commands' output (but still prints failed executions)
pre-push:
  follow: true        # need to use follow to get stdin from git push
  scripts:
    'sync.sh':
      runner: sh
```
