### ISSUE TITLE
Add "no_skip" whitelist/additive option for hooks and commands

### ISSUE THREAD

**Issue by istrasci** [evilmartians/lefthook#477]
### :zap: Summary

Create a `no_skip` (`"enforce"`?) whitelist/additive option for hooks and commands.

### Value

Currently there is only a `skip` option for [hooks](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#skip) and [commands](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#skip) which is blacklist/subtractive behaviour.  I often have commands that I want to execute _**only**_ on particular branches.  Since there is only a subtractive option, I have to implement additive behaviour myself by writing a custom script that checks the current git branch, and executes the command if I'm on one of the allowed branches.  I'd rather not have to do that.

Common use case would be that I want to execute my test suite in a pre-commit hook _**only**_ if I'm on `master` or `hotfix/*` branches.  I cannot blacklist every other possible branch name, so I must create the workaround myself.

### Behavior and configuration changes

Add a `no_skip` (or another word, but I can't find a good antonym for "skip") option that implements additive behaviour for hooks and commands.

**Comment by mrexox** [comment]
Hey! Thank you for the feature request. I like the word `only`, does it make sense to you?

So, you suggest to add something like this, right?

```yml
# lefthook.yml

pre-commit:
  only:
    - ref: master
    - ref: hotfix/*
  commands:
    test:
      only: 
        - ref: hotfix/*
      run: make test
    lint:
      run: make lint
```

I think this option should accept all possible `skip` values, but apply them the opposite way. 

If you confirm, I will start working on this feature.
