### ISSUE TITLE
Breaking changes in 1.3.9

### ISSUE THREAD

**Issue by arrilot** [evilmartians/lefthook#479]
### :wrench: Summary

### Lefthook version

1.3.9 - 1.3.12

### Steps to reproduce

```bash
post-merge
  commands:
    010_composer_i:
      files: "git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD"
      glob: "composer.lock"
      skip:
        - rebase
        - merge
      run: "echo {files} | composer install"
post-checkout:
  commands:
    010_composer_i:
      files: "git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD"
      glob: "composer.lock"
      skip:
        - merge
        - rebase
      run: "echo {files} | composer install"
```

It works great in 1.3.8, but 1.3.9 introduces a breaking change [there](https://github.com/evilmartians/lefthook/commit/03648fc2ca5426efb28f8ff0555e4266d3f30658) resulting in an error 128

```bash
LEFTHOOK_VERBOSE=1 git checkout -b test-h5
Switched to a new branch 'test-h5'
Lefthook v1.3.12
SYNCING
SERVED HOOKS: pre-commit, post-merge, post-checkout, prepare-commit-msg
RUNNING HOOK: post-checkout
[lefthook] cmd: [sh -c git diff-tree -r --name-only --no-commit-id HEAD@49c5332d4d16feb7837269813a5ee3956b134b36 HEAD]
[lefthook] err: exit status 128
[lefthook] out: fatal: ambiguous argument 'HEAD@49c5332d4d16feb7837269813a5ee3956b134b36': unknown revision or path not in the working tree.
error replacing {files}: exit status 128
```                                                                                 
                                                                                                                                           

### Possible Solution

I COULD possibly switch to a new proposed syntax

```bash
post-merge:
  commands:
    010_composer_i:
      files: "git diff --name-only {1} {2}"
      glob: "composer.lock"
      skip:
        - merge
        - rebase
      run: "composer install"
post-checkout:
  commands:
    010_composer_i:
      files: "git diff --name-only {1} {2}"
      glob: "composer.lock"
      skip:
        - rebase
        - merge
      run: "composer install"
```
It works fine for `post-checkout`, but unfortunately in fails for `post-merge`

```bash
LEFTHOOK_VERBOSE=1 git checkout -b test-h6 #everything is fine
#change composer.lock and commit changes
LEFTHOOK_VERBOSE=1 git checkout test-h5 #everything is fine
LEFTHOOK_VERBOSE=1 git merge test-h6
Updating 49c5332d4..19edb0eda
Fast-forward
 composer.lock | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
Lefthook v1.3.12
RUNNING HOOK: post-merge
[lefthook] cmd: [sh -c git diff --name-only 0 {2}]
[lefthook] err: exit status 128
[lefthook] out: fatal: ambiguous argument '0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:                                           
'git <command> [<revision>...] -- [<file>...]'                                                  
                                                                                                
error replacing {files}: exit status 128
010_composer_i: (skip) error
```

Am i missing smth?

**Comment by mrexox** [comment]
Hey! I remember this change and I'm sorry it broke your configuration. This feature makes sense since we used to have arguments references in `run` option, so it feels OK to have it in `files`. I guess that I can add a special check to skip replacement if there's a leading `HEAD` before the brackets. I'll put this issue on my radar.

I'd like to provide some workarounds in case you want a quick solution:

#### Use HEAD~1

I think this variant is preferred. 

```yml
post-checkout:
  commands:
    010_composer_i:
      files: "git diff-tree -r --name-only --no-commit-id HEAD~1 HEAD"
      ...
```

#### Use HEAD^1

```yml
post-checkout:
  commands:
    010_composer_i:
      files: "git diff-tree -r --name-only --no-commit-id HEAD^1 HEAD"
      ...
```

**Comment by arrilot** [comment]
Thank you for your quick response.

I ended with the following configuration and it seems to work fine.

```yaml
post-merge:
  commands:
    010_composer_i:
      files: "git diff-tree -r --name-only --no-commit-id HEAD^1 HEAD"
      glob: "composer.lock"
      skip:
        - merge
        - rebase
      run: "composer install"
post-checkout:
  commands:
    010_composer_i:
      files: "git diff --name-only {1} {2}"
      glob: "composer.lock"
      skip:
        - rebase
        - merge
      run: "composer install"
```

Closing it for now
