### ISSUE TITLE
Extends from remote config are merged via local path

### ISSUE THREAD

**Issue by mrexox** [evilmartians/lefthook#528]
I'm using v1.4.6 and am getting the same problem.. here's my setup: https://github.com/carhartl/lefthook-config

Using for instance

```yaml
# lefthook.yml
remote:
  git_url: https://github.com/carhartl/lefthook-config
  config: go.yml
```

```yaml
# go.yml in remote config
extends:
  - base.yml
pre-commit:
  parallel: true
  commands:
    golangci-lint:
      tags: lint go
      glob: "*.go"
      run: for file in {staged_files}; do golangci-lint run $file; done
pre-push:
  parallel: true
  gotest:
    tags: test go
    glob: "*.go"
    run: gotest ./...
```
I'm getting "Error: open /Users/klaus/Workspace/sandbox/base.yml: no such file or directory". I must be overlooking something?

_Originally posted by @carhartl in https://github.com/evilmartians/lefthook/discussions/420#discussioncomment-6515355_
