### ISSUE TITLE
pre-commit fails when {files} is empty

### ISSUE THREAD

**Issue by q0w** [evilmartians/lefthook#558]
### Lefthook version
1.5.0

### Steps to reproduce
requirements-txt-fixer is from https://github.com/pre-commit/pre-commit-hooks
```yaml
pre-commit:
  parallel: true
  commands:
    requirements-txt-fixer:
      files: "git diff --name-only --cached --diff-filter=ACMR | grep -E \"requirements/(.*\\.in)|(dev.txt)$\""
      run: "requirements-txt-fixer {files}"
      stage_fixed: true
```
### Expected results
requirements-txt-fixer does not fail when `{files}` is empty.
### Actual results
```
error replacing {files}: exit status 1
```

### Possible Solution
Use `|| true`
```yaml
pre-commit:
  parallel: true
  commands:
    requirements-txt-fixer:
      files: "git diff --name-only --cached --diff-filter=ACMR | grep -E \"requirements/(.*\\.in)|(dev.txt)$\" || true"
      run: "requirements-txt-fixer {files}"
      stage_fixed: true
```

### Logs / Screenshots

```bash
lefthook run pre-commit --all-files --verbose
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: /tmp/t

│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks

│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info

│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git

│ [lefthook] cmd: [sh -c git status --short]
│ [lefthook] dir: /tmp/t
│ [lefthook] err: <nil>
│ [lefthook] out:
│ [lefthook] cmd: [sh -c git diff --name-only --cached --diff-filter=ACMR | grep -E "requirements/(.*\.in)|(dev.txt)$"]
│ [lefthook] dir: /tmp/t
│ [lefthook] err: exit status 1
│ [lefthook] out:
error replacing {files}: exit status 1
│ [lefthook] cmd: [sh -c git stash list]
│ [lefthook] dir: /tmp/t
│ [lefthook] err: <nil>
│ [lefthook] out:
```

**Comment by mrexox** [comment]
Hey! I don't think this is a good idea to append `|| true` to all `files` commands. Users may mistaken when writing the command and they will never notice that, but the command won't show an error. 

The problem is that `grep` exits with `1` if nothing was returned after filters applied. I'd suggest you to look at the [`glob`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#glob) option that does exactly what you want, but without using `grep` command. In your case it will be something like this:

```yml
pre-commit:
  parallel: true
  commands:
    requirements-txt-fixer:
      glob: "requirements/{.*\\.in,dev.txt}"
      run: "requirements-txt-fixer {files}"
      stage_fixed: true
```

The glob will be applied to the `{staged_files}` which is the [same command](https://github.com/evilmartians/lefthook/blob/master/internal/git/repository.go#L18) as in your `files`.

Please write if this was helpful 🙏

**Comment by q0w** [comment]
Your glob pattern does not handle `requirements/*.in` files, only `requirements/dev.txt`. Yes, grep returns 1, my alternative solution is to use git patterns like this:
```
git diff --name-only --cached --diff-filter=ACMR -- "requirements/*.in" "requirements/dev.txt"
```

**Comment by q0w** [comment]
There is another case:
```yaml
    just-fmt:
      glob: "Justfile"
      run: "just --fmt --unstable"
      stage_fixed: true
```
This does not work, because I dont use `{staged_files}`, so I need `{files}` anyway.

**Comment by mrexox** [comment]
Sorry, I have mistaken with the glob pattern. I forgot that globs behave differently from regexps. This must work:

```yml
pre-commit:
  parallel: true
  commands:
    requirements-txt-fixer:
      glob: "requirements/{*.in,dev.txt}"
      run: "requirements-txt-fixer {files}"
      stage_fixed: true
```

> This does not work, because I dont use {staged_files}, so I need {files} anyway.

What is your use case? Do you want to run `just --fmt --unstable` agains all files and stage them if `Justfile` has been changed? If so, you probably need to manually stage all files touched by `just --fmt --unstable`. Or if not, please explain and I will help to find the best solution.

```yml
pre-commit:
  parallel: true
  commands:
    just-fmt:
      glob: "Justfile"
      run: "just --fmt --unstable && git add -A"
      stage_fixed: true
```
