### ISSUE TITLE
`--files` path separator  not specified, whitespace doesn't work so it doesn't process globs

### ISSUE THREAD

**Issue by sanmai-NL** [evilmartians/lefthook#564]
### :wrench: Summary

`--files` is supposed to take a list of file paths, but it isn't specified what the separator between these paths should be. A pretty common use case is glob patterns in a shell. Those don't work, only the first path is taken. 
### Lefthook version

1.5.2

### Steps to reproduce

```yml
pre-push:
  commands: &pre-push
    bandit:
      files: git ls-files pyproject.toml
      glob: '*.py'
      run: echo bandit --configfile pyproject.toml --quiet -- {staged_files}
```

```console
$ echo **.py
src/__version__.py src/package/__main__.py src/package/__init__.py
```

```console
$ lefthook run pre-push --commands bandit --files src/**.py --force
╭────────────────────────────────────╮
│ 🥊 lefthook v1.5.2  hook: pre-push │
╰────────────────────────────────────╯
┃  bandit ❯ 

bandit --configfile pyproject.toml --quiet -- src/__version__.py
```

### Expected results

Bandit is being run with all paths matched by the glob.

### Actual results

Bandit is being run with the first path matched by the glob.

### Possible Solution

Reuse `$IFS` is the input separator under Unix, a similar variable or whitespace under Windows, and offer a `-0` option to use the null byte as file path separator instead.

### Logs / Screenshots

```bash
LEFTHOOK_VERBOSE=true git ...
```
