### ISSUE TITLE
Piped and parallel options have leftover console output 

### ISSUE THREAD

**Issue by skawaguchi-flipp** [evilmartians/lefthook#566]
### :wrench: Summary

Using lefthook as described in #66 leads to leftover characters in the console. Things are otherwise working really well.

### Lefthook version

1.5.2

### Steps to reproduce

Using this `lefthook.yml`:
```yml
pre-commit:
  piped: true
  commands:
    generate-protos:
      run: buf generate
      glob: "**/*.proto"
    generate-mocks:
      run: rm -rf ./mocks && mockery
      glob: "**/*.go"
    static-checks:
      run: lefthook run static-checks
      glob: "**/*.go"

static-checks:
  parallel: true
  commands: 
    fmt:
      run: go fmt ./...
      stage_fixed: true
    tidy:
      run: go mod tidy
      stage_fixed: true
    lint:
      run: golangci-lint run ./...
      stage_fixed: true
```

### Expected results

I expect my command prompt to be empty.

### Actual results

The first two commands run with no problems. If there is only a change to a `.proto` file, the console is clear. However, any time `static-checks` runs, this is the what's in my terminal:

```sh
summary: (done in 7.27 seconds)       
✔️  generate-mocks
✔️  generate-protos
✔️  static-checks
^[]11;rgb:2222/1a1a/0f0f^[\^[[15;1R[lefthook-update 005005f] chore: some git commit message
 2 files changed, 1 insertion(+), 4 deletions(-)
% 11;rgb:2222/1a1a/0f0f5;1R
```

I'm not expecting my command prompt to include `11;rgb:2222/1a1a/0f0f5;1R`.

### Possible Solution

It looks like the git processing module is exiting early.

### Logs / Screenshots

```sh
│ 🥊 lefthook v1.5.1  hook: pre-commit │
╰──────────────────────────────────────╯
┃  generate-mocks ❯ 


Generating Mocks 
rm -rf ./mocks
mockery
# mock output
Generate mocks - Done 

│  generate-protos (skip) no matching staged files
┃  static-checks ❯ 

│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: /<path-to-files>
                                                           
│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks
                          
│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info
                         
│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir: 
│ [lefthook] err: <nil>
│ [lefthook] out: .git
                    
╭─────────────────────────────────────────╮
│ 🥊 lefthook v1.5.1  hook: static-checks │
╰─────────────────────────────────────────╯
┃  tidy ❯ 


┃  fmt ❯ 


┃  lint ❯ 

go mod tidy
Running golangci-lint 
golangci-lint run ./...

                                      
  ────────────────────────────────────
summary: (done in 0.58 seconds)       
✔️  tidy
✔️  fmt
✔️  lint

                                      
  ────────────────────────────────────
summary: (done in 5.98 seconds)       
✔️  generate-mocks
✔️  static-checks
^[]11;rgb:2222/1a1a/0f0f^[\^[[15;1R[lefthook-update d0fd4b0] test
 1 file changed, 1 deletion(-)
 % 11;rgb:2222/1a1a/0f0f5;1R
```

**Comment by infotexture** [comment]
I'm also seeing weird control characters like `[1m`, `[0m`, `[2K`, & `[1G` in the log output:

```
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.5.5  hook: [1mpre-commit[0m │
╰──────────────────────────────────────╯
┃  prettier ❯ 

samples/css/style.css[2K[1Gsamples/css/style.css 22ms
```

**Comment by jackTabsCode** [comment]
Hey, I'm also experiencing this. This is my `lefthook.yml`:
```yml
pre-commit:
  commands:
    check:
      run: npx biome check --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
```

This is extremely frustrating so I'm hoping it can be fixed!

**Comment by mrexox** [comment]
Hey! Do you only get this when you execute lefthook from within a lefthook command? Or does it also appears when having simple configuration?

What terminal emulator do you use?

**Comment by mrexox** [comment]
I have a temporary solution for you. You should pass `use_stdin` option to the commands that call lefthook themselves. Like in this example:

```yml
pre-commit:
  piped: true
  commands:
    static-checks:
      use_stdin: true
      run: lefthook run static-checks
      glob: "**/*.go"
```

The problem I could identify is the following: https://github.com/creack/pty module that lefthook uses to get the output adds these sequences, and I'm not sure if there's a way to fix this. However when you specify `use_stdin` the command is being executed without pty wrapper. I will dig into this issue in more details to fix it. But by now I only have a workaround.
