### ISSUE TITLE
Space-separated tags are interpretted as a single tag

### ISSUE THREAD

**Issue by technicalpickles** [evilmartians/lefthook#569]
### :wrench: Summary

The [documentation on tags](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#tags) says:

> You can specify tags for commands and scripts. This is useful for [excluding](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#exclude_tags). You can specify more than one tag using comma or space.

I tried specifying commands with multiple tags, and then `exclude_tags` in my lefthook-local.yml, but they are still executed.

I tested with `lefthook dump`, and sure enough, the tags only have a single tag with spaces

### Lefthook version

1.5.2

### Steps to reproduce

Create a lefthook.yml with:

```yaml
pre-commit:
  commands:
    rubocop: 
      tags: backend style pre-commit-and-pre-push
      glob: "{Rakefile,Brewfile,Gemfile,*.{rb,rake,rabl,arb}}"
      run: .lefthook/rubocop {files}
      stage_fixed: true
```

Add to lefthook-local.yml:

```yaml
pre-commit:
  exclude_tags: pre-commit-and-pre-push
```

Try to commit, and see rubocop still run.

Confirm with `lefthook dump` that it is only one tag:

```yaml
❯ lefthook dump
pre-commit:
  commands:
    rubocop:
      run: .lefthook/rubocop {files}
      tags:
        - backend style pre-commit-and-pre-push
      glob: '{Rakefile,Brewfile,Gemfile,*.{rb,rake,rabl,arb}}'
      stage_fixed: true
```

Try changing it to comma separated, ie:

```yaml
pre-commit:
  commands:
    rubocop:
      tags: backend,style,pre-commit-and-pre-push
      glob: "{Rakefile,Brewfile,Gemfile,*.{rb,rake,rabl,arb}}"
      run: .lefthook/rubocop {files}
      stage_fixed: true
```

```
❯ lefthook dump
pre-commit:
  commands:
    rubocop:
      run: .lefthook/rubocop {files}
      tags:
        - backend
        - style
        - pre-commit-and-pre-push
      glob: '{Rakefile,Brewfile,Gemfile,*.{rb,rake,rabl,arb}}'
      stage_fixed: true
```

### Possible Solution

I could go two ways:

- add logic to `internal/config/command.go` to try to split on space
- update the docs refer to space separated lists
