### ISSUE TITLE
lefthook can swallow stdin from user typing at the terminal unexpectedly

### ISSUE THREAD

**Issue by technicalpickles** [evilmartians/lefthook#588]
### :wrench: Summary

consider a workflow like this:

```
$ git commit -m "She sells seashells by the sea shore"
<lefthook happens here>
$ git push
$ git checkout
```

Out of muscle memory, it's really easy to hit enter, and immediately start typing the next command while the first command is still running. It seems that lefthook ends up receiving that command you start typing though, so when the first command is finished, the input with the second command doesn't get to the shell.

For some additional context, I've gotten this complaint from a few people after migrating from [committer](https://github.com/gusto/committer) to lefthook.

### Lefthook version

1.5.2

### Steps to reproduce

`lefthook.yaml`:

```yaml
pre-commit:
  commands:
    sleep:
      run: sleep 2
```

- make some change
- type `git commit -a -m "test"<enter>`
- while lefthook is running, type: `git checkout main<enter>`

### Expected results

shell receives the input for the next command, ie `git checkout main<enter>`

### Actual results

input with second command, `git checkout main`, isn't received by the shell.

### Possible Solution

I think it should be possible to close stdin, so it doesn't receive any of the input from a user. I don't know if there are any cases where lefthook does read from stdin though.

### Logs / Screenshots

https://github.com/evilmartians/lefthook/assets/159/ed77fd94-9e1f-4a95-bf53-4292572d052d

**Comment by noaelad** [comment]
I also have this issue, been pretty annoyed with lefthook as a result

**Comment by att14** [comment]
Even with `no_tty` and a full `skip_output` I observe this issue.

```yml
no_tty: true

skip_output:
  - meta           # Skips lefthook version printing
  - summary        # Skips summary block (successful and failed steps) printing
  - empty_summary  # Skips summary heading when there are no steps to run
  - success        # Skips successful steps printing
  - failure        # Skips failed steps printing
  - execution      # Skips printing any execution logs (but prints if the execution failed)
  - execution_out  # Skips printing execution output (but still prints failed commands output)
  - execution_info # Skips printing `EXECUTE > ...` logging
  - skips          # Skips "skip" printing (i.e. no files matched)
  - meta           # Skips lefthook version printing

post-checkout:
  commands:
    sleep:
      run: sleep 2
```

```sh
$ git checkout
M       lefthook.yml
Your branch is up to date with 'origin/main'.
asdf asdf asdf asdf%
$ sdf asdf asdf
```

**Comment by mrexox** [comment]
I've tried to reproduce this issue, but couldn't do that. The example config:

```yml
pre-commit:
  commands:
    sleep:
      run: sleep 2
```

I am not sure what the problem is. I use lefthook version 1.5.3, zsh 5.9.

Could you please try [`follow`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#follow) option, add `LEFTHOOK_VERBOSE=1` and send the full log, so I could understand at what step the input is being swallowed. I tried to add `sleep` calls inside the hook too, but on my setup I don't have any input swallowed:

```yml
❯ git commit -m 'test'
[sleep called from hook script]
1234[sleep done]
5╭──────────────────────────────────────╮
│ 🥊 lefthook v1.5.3  hook: pre-commit │
╰──────────────────────────────────────╯
sync hooks: ✔️ (pre-commit)
6┃  sleep ❯

789
  ────────────────────────────────────
summary: (done in 2.50 seconds)
✔️  sleep
[main 3c7c0c1] test
 1 file changed, 1 insertion(+)
e
lh-test git:main  6s
❯ 123456789
```

**Comment by technicalpickles** [comment]
> I've tried to reproduce this issue, but couldn't do that.

I use fish on macOS in iTerm2. I've tested against zsh and bash, and get the same result.

Interestingly, I tried making a script to reproduce, but it does not reproduce:

```bash
#!/usr/bin/env bash
echo "# noise" >> lefthook.yml
printf "git commit -a -m 'test'\necho hello world" | bash
```

Might be having to do with it being one command and multiple lines, but I'll keep experimenting.

> Could you please try [follow](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#follow) option, add LEFTHOOK_VERBOSE=1 and send the full log, so I could understand at what step the input is being swallowed.

Sure, here you go! `echo sup` is the command I typed while it is running.
```
❯ LEFTHOOK_VERBOSE=1 git commit -a -m "test"
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: /Users/josh.nichols/workspace/lefthook-test

│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks

│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info

│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git

╭──────────────────────────────────────╮
│ 🥊 lefthook v1.5.2  hook: pre-commit │
╰──────────────────────────────────────╯
sync hooks: ✔️ (pre-commit)
│ [lefthook] cmd: [sh -c git status --short]
│ [lefthook] dir: /Users/josh.nichols/workspace/lefthook-test
│ [lefthook] err: <nil>
│ [lefthook] out: M  lefthook.yml
?? reproduce.sh

│ [lefthook] cmd: [sh -c git diff --name-only --cached --diff-filter=ACMR]
│ [lefthook] dir: /Users/josh.nichols/workspace/lefthook-test
│ [lefthook] err: <nil>
│ [lefthook] out: lefthook.yml

│ [lefthook] files before filters:
[lefthook.yml]
│ [lefthook] files after filters:
[lefthook.yml]
┃  sleep ❯

echo sup
│ [lefthook] cmd: [sh -c git stash list]
│ [lefthook] dir: /Users/josh.nichols/workspace/lefthook-test
│ [lefthook] err: <nil>
│ [lefthook] out:

  ────────────────────────────────────
summary: (done in 2.08 seconds)
✔️  sleep
│ [lefthook] cmd: [git rev-parse --show-toplevel]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: /Users/josh.nichols/workspace/lefthook-test

│ [lefthook] cmd: [git rev-parse --git-path hooks]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/hooks

│ [lefthook] cmd: [git rev-parse --git-path info]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git/info

│ [lefthook] cmd: [git rev-parse --git-dir]
│ [lefthook] dir:
│ [lefthook] err: <nil>
│ [lefthook] out: .git

╭──────────────────────────────────────────────╮
│ 🥊 lefthook v1.5.2  hook: prepare-commit-msg │
╰──────────────────────────────────────────────╯
│ [lefthook] skip: Hook prepare-commit-msg doesn't exist in the config
[test-branch 4fcb833] test
 1 file changed, 1 insertion(+)
```

**Comment by technicalpickles** [comment]
I was able to reproduce stdin not being swallowed when using a plain `.git/hooks/pre-commit`:

```bash
#!/usr/bin/env bash
echo "[sleep from $0]"
sleep 2
```

https://github.com/evilmartians/lefthook/assets/159/5e225869-5e08-4e73-8b5c-387df25427c2

--- 

Something I was wondering is, would it be possible to defer opening/attaching stdin until something explicitly uses it? ie `interactive: true` or `use_stdin: true`?

**Comment by mrexox** [comment]
@technicalpickles , so stdin still gets swallowed even if you run lefthook from the console? Like `lefthook run pre-commit`, right?

**Comment by technicalpickles** [comment]
Just tested, and it looks like it! One interesting observation though:

- `lefthook run pre-commit`, you see the input, and you see a copy the input echo'd back
- `git commit`, you see the input, but not a copy


![CleanShot 2023-11-30 at 09 07 10@2x](https://github.com/evilmartians/lefthook/assets/159/6addb5c1-cd37-4717-b617-f528e0e81637)

**Comment by mrexox** [comment]
The fix will be soon released in version **1.5.5**

**Comment by technicalpickles** [comment]
> It looks like you type echo sup<Enter>, and then it is being swallowed. I have typed echo sup without Enter, and the text was displayed after the lefthook call.

That's right, it includes hitting `<enter>`. However, I see the same behavior with or without `<enter>`.

I tried out 1.5.5, and still see the same behavior 🤔 My current test file:

```yaml
pre-commit:
  follow: true
  commands:
    sleep:
      interactive: false
      use_stdin: false
      run: sleep 2
```

I'm still working on an automated reproduction. Thinking to try something like [`expect`](https://www.geeksforgeeks.org/expect-command-in-linux-with-examples/). I'm also working on a reproduction case to show how `committer` works.
