### ISSUE TITLE
Pre-push: error getting files: exit status 128

### ISSUE THREAD

**Issue by allestaire** [evilmartians/lefthook#625]
Pre-push not running command, it will report `error getting files: exit status 128`

Here is the code:
```yml
pre-push:
  follow: true
  piped: true
  commands:
    1_test:
      run: yarn test 
    2_build:
      run: yarn build
```

<img width="365" alt="Screen Shot 2024-02-07 at 4 28 46 PM" src="https://github.com/evilmartians/lefthook/assets/68372409/cfa31560-d970-41f4-b7be-439d286ed8e4">
