### ISSUE TITLE
Commands are run from the current path when applying the commit 

### ISSUE THREAD

**Issue by maxdinech** [evilmartians/lefthook#629]
### :wrench: Summary

If I run a commit in `./` or `./backend/`, the results differ. In this case, with Pyright (but other commands are affected too)
The python venv is attached to the backend folder.

### Lefthook version

1.6.1

### Steps to reproduce

```
pre-commit:
  commands:
    backend-pyright:
      root: "backend/"
      run: pyright .
```

```
cd ./
git commit -m "test from root"
cd backend/
git commit -m "test from backend"
```

### Expected results

Pyright (including config) loaded from the backend in both cases

### Actual results

A lot of pyright errors such as `Unable to resolve import X` in the first case but not in the second

### Possible Solution

Make the command run from the path specified in root.

**Comment by mrexox** [comment]
Hey! Actually with 1.6.0 release I've mad an effort to make lefthook commands run inside the root. Like in this example

```yml
test:
  commands:
    ls:
      run: echo $(ls)
```

`lefthook run test` prints files in project root, and if you add some `root: subfolder` to the `ls` command it will list files in this subfolder.

Could you please provide some logs and config example, so I could reproduce your issue. An example repo would be even better.
