### ISSUE TITLE
Update JSON Schema on schemastore.org

### ISSUE THREAD

**Issue by reitzig** [evilmartians/lefthook#632]
### :wrench: Summary

The JSON Schema published on schemastore.org is out of date.

(re #288, cc @hyperupcall )

### Lefthook version

1.6.1

### Steps to reproduce

Create a config like this:

```yaml
pre-commit:
  piped: true
  commands:
    formatter:
      priority: 1
      glob: "*.go"
      run: go fmt ./...
      stage_fixed: true
    vet:
      priority: 1
      glob: "*.go"
      run: for f in {staged_files}; do go vet "${f}"; done
```

### Expected results

No schema violations

### Actual results

`*.commands.*.priority` not supported:

![image](https://github.com/evilmartians/lefthook/assets/4246780/dbd25a0e-5ae2-46a8-874c-7eab74776f7b)

### Possible Solution

- Update the schema to the current state.
- Source the schema in this repository and include tests against it in the build; re-submit to schemastore on releases.
  - Would the schema need versioning?
