### ISSUE TITLE
`The command line is too long` on Windows

### ISSUE THREAD

**Issue by ValentinGurkov** [evilmartians/lefthook#655]
### :wrench: Summary

Hello,

I am testing the project with leftook instead of husky + lint-staged. I happen to have another formatting changes and the list of staged files is 365.

This seems to be already discussed inhttps://github.com/evilmartians/lefthook/issues/471 and fixed in https://github.com/evilmartians/lefthook/pull/541 but chunking of the input files did not happen.

I am currently testing with a very simple configuration like:

```yml
pre-commit:
    #piped: true
    #parallel: true
    commands:
        spellcheck:
            #priority: 1
            #glob: '*.{ts}'
            run: pnpm cspell --files {staged_files}
```

`cspell` can be replaced with another package like `prettier` for example. As long as `staged_files` are used and the number of files are long enough (I don't know where is the breaking point), this issue will occur.

Have I missed something to trigger the chunking?

Thanks.

### Lefthook version

`1.6.4`

### Steps to reproduce

1.  Be on windows
2. Have a lot of files staged (in my example 365)
3. Pass the staged files to a formatted or something similar in lefthook
4. Observe the result

### Expected results

The command should be split into multiple commands with each with a chunk of files.

### Actual results

The command line is too long.

### Logs / Screenshots

Here is the error from `pnpm lefthook run pre-commit --verbose`. I have omitted the list of files, the project, and stashes. I did not see anything else in the log but it is possible it got trimmed in my terminal due to the long output.

```
⠴ waiting: spellcheckThe command line is too long.
┃  spellcheck ❯       


│ [lefthook] cmd: [git stash list]
│ [lefthook] dir: <project>
│ [lefthook] err: <nil>
│ [lefthook] out: <stashes here>
```
