### ISSUE TITLE
Installation command creates a folder named --help

### ISSUE THREAD

**Issue by sawa-ko** [evilmartians/lefthook#769]
### :wrench: Summary

When I run the command `lefthook install` (using pnpm exec) a folder named `--help` is created.

### Lefthook version

1.7.2

### Steps to reproduce

1. Install `lefthook`
2. Use the command `lefthook install`
3. See the `--help` folder created by lefthook

### Expected results

Some `.lefthook` folder or something like that and not a folder named `--help`.

### Actual results

A folder named `--help`

### Logs / Screenshots

https://github.com/user-attachments/assets/f6904342-a17c-4b7a-967a-21d282395dda

```bash
LEFTHOOK_VERBOSE=true git ...
```

**Comment by mrexox** [comment]
Hey! Could you share your `lefthook.yml` config?

**Comment by sawa-ko** [comment]
Hi @mrexox, here my `lefhook.yml` file

```yml
pre-commit:
  parallel: true
  commands:
    check:
      glob: "*.{ts,tsx}"
      run: npx lint-staged --allow-empty && git update-index --again

commit-msg:
  scripts:
    "commitlint.sh":
      runner: bash

post-commit:
  commands:
    git-update-index:
      run: git update-index --again
```
