### ISSUE TITLE
Skip hook/command when commit message matches a pattern

### ISSUE THREAD

**Issue by reitzig** [evilmartians/lefthook#780]
### :zap: Summary

Allow to skip a hook (or individual command) if the commit message matches a certain pattern.

### Value

I like using `cog verify` (cf. [cocogitto/cocogitto](https://github.com/cocogitto/cocogitto)) as part of a `commit-msg` hook. I also like creating fixup commits (in IDEA, if that matters) which end up vanishing after rebasing with `autosquash`.

Sadly, the two do not mix well: cocogitto forbids the ephemeral commit messages of such commits, as they don't conform to conventional commits.

What I would like is to configure lefthook to ignore fixup commits: 

```yaml
commit-msg:
  skip:
    - ref: "wip/*"
    - msg: "^fixup! "
  commands:
    cog:
      run: cog verify --file {1}
```

### Behavior and configuration changes

The change seems additive to me.

**Comment by reitzig** [comment]
FWIW: [cocogitto/cocogitto#403](https://github.com/cocogitto/cocogitto/issues/403)

Either feature fixes _my_ use case, but I do think that this proposal has merit in its own right for lefthook.

**Comment by reitzig** [comment]
Workaround:

```
commit-msg:
  skip:
    - ref: "wip/*"
  commands:
    cog:
      run: sh -c "if grep -qv '^fixup!' {1}; then cog verify --file {1}; fi"
```

**Comment by mrexox** [comment]
There is also another workaround:

```yml
commit-msg:
  skip:
    - run: cat .git/COMMIT_EDITMSG | grep "^fixup! "
  jobs:
    - run: cog verify --file {1}
```

I will close this issue since there are workarounds and `msg: ''` matcher only makes sense for `commit-msg` hook.
