### ISSUE TITLE
Provide a default branch for {push_files} 

### ISSUE THREAD

**Issue by mrexox** [evilmartians/lefthook#785]
### :zap: Summary

```yml
base_branch: develop

pre-push:
  commands:
    lint:
      run: yarn lint {push_files}
```
### Value

1. Default branch is develop
2. You create a new branch from develop
3. You try to push and `{push_files}` contains files not agains the `develop`, but against `main`

This is confusing. This should be controlled by some setting in lefthook, since it's impossible to control the other way.

**Comment by mrexox** [comment]
For now you can use a workaround:

```yml
pre-push:
  only:
    - run: git remote set-head origin develop
  commands:
    ...
```

This will set your `origin/HEAD` pointing to `develop` branch before the `{push_files}` get queried.
