### ISSUE TITLE
Can't exclude multiple files.

### ISSUE THREAD

**Issue by Florian-crg** [evilmartians/lefthook#805]
### :wrench: Summary

We cannot exclude multiple files.

### Lefthook version

1.3.0 

### Steps to reproduce

Add multiple files to the exclude property.

### Expected results

To exclude all files listed below the exclude property.

### Actual results

Error: 1 error(s) decoding:
* '[linter].exclude' expected type 'string', got unconvertible type '[]interface {}', value: '[file_1.ts file_2.js]'

### Possible Solution

This might not be implemented. Though while looking the documentation it seems that it should.

https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#exclude

```
# lefthook.yml

pre-commit:
  commands:
    lint:
      glob: "*.rb"
      exclude:
        - config/routes.rb
        - config/application.rb
        - config/initializers/*.rb
        - spec/rails_helper.rb
      run: bundle exec rubocop --force-exclusion {staged_files}
```
