### ISSUE TITLE
stage_fixed (or equivalent) for changed files not originally staged

### ISSUE THREAD

**Issue by isturdy** [evilmartians/lefthook#806]
### :zap: Summary

IIUC, currently stage_fixed only affects the files originally in the glob. I'm trying to use lefthook for code/documentation generation, and so some steps create/modify files not part of the original staged set/glob results.

### Value

Allows using pre-commit for generated files (e.g. documentation)

### Behavior and configuration changes

For a silly example, consider a hook that duplicates files:
```
pre-commit:
  commands:
    clone:
      stage_fixed: true
      glob: "*.txt"
      run: cp {staged_files} backup
 ```
 I initially expected that this would commit both the manually-created file and its backup, but instead it commits the original file and creates the backup but does not stage/commit it. I've tried adding a git add to the command but it frequently fails due to git lock contention. (I haven't been able to replicate it with a toy example; the actual use case can touch hundreds of files.) I would like to see a variant of stage_fixed that also adds any files not originally staged for the commit that change during the command. (And can probably spare time to implement it if we can agree on a design.)

**Comment by isturdy** [comment]
Update: I had thought of using `git add` within the command but found it unreliable; apparently that stemmed from running it inside docker, and moving it outside fixed that. (On the other hand, I've also found that `stage_fixed` doesn't seem to work reliably for files changed by something running in Docker.)

**Comment by mrexox** [comment]
I suggest you to use `git add` in your command, like this:

```yml
pre-commit:
  commands:
    clone:
      glob: "*.txt"
      run: cp {staged_files} backup && git add backup/*
```

Staging everything in lefthook is hard to control and you may surprise to commit something you didn't want to. So, explicitly adding files with `&& git add ...` is an options. What issues did you meet when using it?
