### ISSUE TITLE
Skip option does not work for pre-push hooks

### ISSUE THREAD

**Issue by PidgeyBE** [evilmartians/lefthook#817]
### :wrench: Summary

The option to skip some hooks does not work correctly for `pre-push` hooks.
[The check](https://github.com/evilmartians/lefthook/blob/v1.7.15/internal/git/state.go#L69) to determine if a branch is in merge state only works for `pre-commit` hooks.
One of the ways to check the state correctly for `pre-push` hooks is e.g. `$(git log -1 --pretty=%P | wc -w) -gt 1`.

### Lefthook version

`v1.7.15`

### Steps to reproduce
1. Have a `pre-push` hook that should be skipped for `merge` and `rebase`
```
pre-push:
  parallel: true
  commands:
    lint-yaml:
      glob: '*.{yml,yaml}'
      run: yamllint -d relaxed {push_files}
      skip:
        - merge
        - rebase
```
2. Check out a certain branch `branch-x`
3. Merge master, `git merge master`
4. Run pre-push hooks

### Expected results

Because of `skip: merge`, the hook should be skipped

### Actual results

The hook is not skipped.

### Possible Solution

Instead of checking the presence of `.git/MERGE_HEAD`, in case of a pre-push hook, lefthook should check if the last commit was a merge commit or not. E.g. via `$(git log -1 --pretty=%P | wc -w) -gt 1` in bash
