### ISSUE TITLE
Option "skip" is not properly merged

### ISSUE THREAD

**Issue by madeofsun** [evilmartians/lefthook#837]
### :wrench: Summary

Option "skip" is not properly merged

### Lefthook version

1.7.18

### Steps to reproduce

Create some package with

```jsonc
// package.json
{
  "dependencies": {
    "lefthook": "1.7.18"
  }
}

```

```yaml
# some-lefthook.yml
pre-commit:
  commands:
    my-cmd:
      skip: true
      run: exit 1

```

```yaml
# lefthook.yml
extends:
  - ./some-lefthook.yml

pre-commit:
  commands:
    my-cmd:
      skip: false
```

### Expected results

Hook must run and `npx lefthook -v dump` must output

```yaml
extends:
  - ./some-lefthook.yml
pre-commit:
  commands:
    my-cmd:
      run: exit 1
      skip: false
```

### Actual results

Hook is skipped and `npx lefthook -v dump` outputs

```yaml
extends:
  - ./some-lefthook.yml
pre-commit:
  commands:
    my-cmd:
      run: exit 1
      skip: true
```

### Logs / Screenshots

```bash
LEFTHOOK_VERBOSE=true git commit -m tmp
+ '[' '' = 0 ']'
+ call_lefthook run pre-commit
+ test -n ''
+ lefthook -h
++ git rev-parse --show-toplevel
+ dir=/Users/nikita/Documents/code/test-lefthook
++ uname
++ tr '[:upper:]' '[:lower:]'
+ osArch=darwin
++ uname -m
++ sed 's/aarch64/arm64/;s/x86_64/x64/'
+ cpuArch=arm64
+ test -f /Users/nikita/Documents/code/test-lefthook/node_modules/lefthook-darwin-arm64/bin/lefthook
+ /Users/nikita/Documents/code/test-lefthook/node_modules/lefthook-darwin-arm64/bin/lefthook run pre-commit
│ [lefthook] cmd:    [git rev-parse --show-toplevel]
│ [lefthook] stdout: /Users/nikita/Documents/code/test-lefthook
                                                             
│ [lefthook] cmd:    [git rev-parse --git-path hooks]
│ [lefthook] stdout: .git/hooks
                             
│ [lefthook] cmd:    [git rev-parse --git-path info]
│ [lefthook] stdout: .git/info
                            
│ [lefthook] cmd:    [git rev-parse --git-dir]
│ [lefthook] stdout: .git
                       
│ [lefthook] cmd:    [git hash-object -t tree /dev/null]
│ [lefthook] stdout: 4b825dc642cb6eb9a060e54bf8d69288fbee4904
                                                           
╭───────────────────────────────────────╮
│ 🥊 lefthook v1.7.18  hook: pre-commit │
╰───────────────────────────────────────╯
│ [lefthook] cmd:    [git status --short --porcelain]
│ [lefthook] dir:    /Users/nikita/Documents/code/test-lefthook
│ [lefthook] stdout: 
│  my-cmd (skip) settings
│ [lefthook] cmd:    [git stash list]
│ [lefthook] dir:    /Users/nikita/Documents/code/test-lefthook
│ [lefthook] stdout: 
                                      
  ────────────────────────────────────
summary: (done in 0.01 seconds)       
On branch master
nothing to commit, working tree clean
```

<img width="455" alt="Screenshot 2024-10-08 at 23 11 20" src="https://github.com/user-attachments/assets/42ed1411-3355-4306-8e0a-d5e88ec68fbc">

**Comment by mrexox** [comment]
Hey @madeofsun! Why do you expect extends to be merged before the main config? I think this is a problem with documentation because it's not clear from it, but all extends, remotes and local config get merged after the settings in the main config file.

I think I get the idea of your configuration, but changing the order of merging may break behavior for other users.

**Comment by madeofsun** [comment]
Oh, sorry, I will check the docs again. I was expecting that it works similar to other tools (eslint / jest / babel / etc.), where you override configs that are extended.

Also, maybe there is another way to do what I need. I wish to have a config with some hooks enabled by default and some "optional" hooks that are skipped by default and the end user can enable such "optional" hooks if they want.

**Comment by mrexox** [comment]
There is an option to use `lefthook-local.yml` which is merged at the end and will do the override. This is the order of merges:

1. Main settings in `lefthook.yml`
2. Settings from `extends`
3. Settings from `remotes`
4. Settings from `lefthook-local.yml`

Does it work for your case? I guess this might be a bit inconvenient to have two configs 🤔 WDYT?

**Comment by mrexox** [comment]
I can suggest you the following structure:

```yml
extends:
  - ./some-lefthook.yml
  - ./main-lefthook.yml
```

```yml
# some-lefthook.yml
pre-commit:
  commands:
    my-cmd:
      skip: true
      run: exit 1
```

```yml
# main-lefthook.yml
pre-commit:
  commands:
    my-cmd:
      skip: false
```

In this case only the order of `extends` matters and the settings from the last config will override the previous settings.
