### ISSUE TITLE
Make `parallel: true` work with priorities

### ISSUE THREAD

**Issue by scop** [evilmartians/lefthook#846]
### :zap: Summary

Would good to have `parallel: true` work with priorities.

### Value

Faster runs containing priorities (~ dependencies).

### Behavior and configuration changes

For example:
```yaml
foo:
  parallel: true
  commands:
    cmd-a:
      priority: 1
    cmd-b:
      priority: 2
    cmd-c:
      priority: 3
    cmd-d:
      # no priority set
    cmd-e:
      priority: 1
    cmd-f:
      priority: 3
```
...and `lefthook run foo` would result in the commands to be run in parallel _within groups determined by priority_.

So the order of execution would go in sequence
1. priority 1: cmd-a and cmd-e in parallel
2. priority 2 (after prio 1 jobs complete): cmd-b alone
3. priority 3 (after prio 2 jobs complete): cmd-c and cmd-f in parallel
4. priority +Infinity (after prio 3 jobs complete): cmd-d alone
