### ISSUE TITLE
Lefthook skips a file if folder name contain mixed cyrillic and latin symbols

### ISSUE THREAD

**Issue by kiskv** [evilmartians/lefthook#872]
### :wrench: Summary

Lefthook skips a file if folder name contain mixed cyrillic and latin symbols

### Lefthook version

1.8.2

### Steps to reproduce

I have this lefthook config:

```
pre-commit:
    parallel: true
    commands:
        check-scripts:
            glob: '*.{js,ts,jsx,tsx,mts,mjs,cjs,cts}'
            run: npx --no-install prettier --write {staged_files} --cache && npx --no-install eslint {staged_files} --cache --cache-location="./node_modules/.cache/eslint/.eslintcache" && git add {staged_files}
        check-styles:
            glob: '*.{css}'
            run: npx --no-install prettier --write {staged_files} --cache && npx --no-install stylelint {staged_files} --cache --cache-location="./node_modules/.cache/stylelint/.stylelintcache" && git add {staged_files}
        check-json:
            glob: '*.{json}'
            run: npx --no-install prettier --write {staged_files} --cache && git add {staged_files}

```

And have file in this folder:
./cypress/e2e/сities/cities.cy.ts (first symbol in `сities` folder - cyrillic)

After make changes in this file, and run pre-commit hook print this message:

``` check-scripts (skip) no files for inspection ```,
which is wrong, since the file corresponds to glob pattern in check-scripts command

After renaming the folder and removing the cyrillic character, pre-commit works correctly and the file is included in the check-scripts command

### Logs / Screenshots

```bash
: aaa'
+ '[' '' = 0 ']'
+ call_lefthook run pre-commit
+ test -n ''
+ lefthook -h
++ git rev-parse --show-toplevel
+ dir=/Users/ki/Desktop/sample-project
++ uname
++ tr '[:upper:]' '[:lower:]'
+ osArch=darwin
++ uname -m
++ sed 's/aarch64/arm64/;s/x86_64/x64/'
+ cpuArch=arm64
+ test -f /Users/ki/Desktop/sample-project/node_modules/lefthook-darwin-arm64/bin/lefthook
+ /Users/ki/Desktop/sample-project/node_modules/lefthook-darwin-arm64/bin/lefthook run pre-commit
│ [lefthook] cmd:    [git rev-parse --show-toplevel]
│ [lefthook] stdout: /Users/ki/sample-project
                                                              
│ [lefthook] cmd:    [git rev-parse --git-path hooks]
│ [lefthook] stdout: .git/hooks
                             
│ [lefthook] cmd:    [git rev-parse --git-path info]
│ [lefthook] stdout: .git/info
                            
│ [lefthook] cmd:    [git rev-parse --git-dir]
│ [lefthook] stdout: .git
                       
│ [lefthook] cmd:    [git hash-object -t tree /dev/null]
│ [lefthook] stdout: 4b825dc642cb6eb9a060e54bf8d69288fbee4904
                                                           
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.8.2  hook: pre-commit │
╰──────────────────────────────────────╯
│ [lefthook] cmd:    [git status --short --porcelain]
│ [lefthook] dir:    /Users/ki/Desktop/sample-project
│ [lefthook] stdout: 
│ [lefthook] cmd:    [git diff --name-only --cached --diff-filter=ACMR]
│ [lefthook] dir:    /Users/ki/Desktop/sample-project
│ [lefthook] cmd:    [git diff --name-only --cached --diff-filter=ACMR]
│ [lefthook] cmd:    [git diff --name-only --cached --diff-filter=ACMR]
│ [lefthook] cmd:    [git diff --name-only --cached --diff-filter=ACMR]
│ [lefthook] cmd:    [git diff --name-only --cached --diff-filter=ACMR]
│ [lefthook] dir:    /Users/ki/Desktop/sample-project
│ [lefthook] dir:    /Users/ki/Desktop/sample-project
│ [lefthook] dir:    /Users/ki/Desktop/sample-project
│ [lefthook] cmd:    [git diff --name-only --cached --diff-filter=ACMR]
│ [lefthook] dir:    /Users/ki/Desktop/sample-project
│ [lefthook] dir:    /Users/ki/Desktop/sample-project
│ [lefthook] stdout: 
│ [lefthook] stdout: 
│  check-json (skip) no files for inspection
│  check-scripts (skip) no files for inspection
│ [lefthook] stdout: 
│  check-styles (skip) no files for inspection
│ [lefthook] cmd:    [git stash list]
│ [lefthook] dir:    /Users/ki/Desktop/sample-project
│ [lefthook] stdout: 
                                      
  ────────────────────────────────────
summary: (done in 0.04 seconds)       
On branch master
Your branch is up to date with 'origin/master'.
```

**Comment by mrexox** [comment]
This issue seems to be fixed. Please, reopen if it doesn't.

```yml
# lefthook.yml

test:
  jobs:
    - run: echo {staged_files}
      glob: "*.ts"
```

```bash
$ git status --short
A  lefthook.yml
A  кasd/гшшasd.ts
A  фola.ts

$ lefthook run test
╭─────────────────────────────────╮
│ 🥊 lefthook v1.13.6  hook: test │
╰─────────────────────────────────╯
┃  echo {staged_files} ❯

кasd/гшшasd.ts фola.ts


  ────────────────────────────────────
summary: (done in 0.01 seconds)
✔️ echo {staged_files} (0.01 seconds)

```
