### ISSUE TITLE
Lefthook doesn't find executables with Desktop Git Client - npx: not found

### ISSUE THREAD

**Issue by bennycode** [evilmartians/lefthook#887]
### :wrench: Summary

When I try to push with my Git Desktop client ([SmartGit](https://www.syntevo.com/smartgit/)) then lefthook doesn't find `npx`. If I push from within VS Code, it works.

Here is my `lefthook.yml`:

```yml
pre-commit:
  parallel: true
  commands:
    format:
      glob: '*.{css,html,json,less,md,scss,yml}'
      run: npx -c "cross-env NODE_OPTIONS=--max_old_space_size=4096 prettier --write --log-level error {staged_files}"
    lint:
      glob: '*.{js,jsx,ts,tsx}'
      run: npx eslint {staged_files} --fix
``` 

### Lefthook version

v1.9.0

### Steps to reproduce

- Use a Git Desktop client (like [SmartGit](https://www.syntevo.com/smartgit/))
- Use `nvm` to install and run Node.js

### Expected results

Lefthook finding `npx` and other tools

### Actual results

Lefthook failing to find `npx`:

> \u2503  lint \u276f 
> sh: 1: npx: not found
> exit status 127\u2503  format \u276f 
> sh: 1: npx: not found
> exit status 127   

### Possible Solution

- There was a workaround here: https://github.com/evilmartians/lefthook/issues/178#issuecomment-959862247
- Apparently it was fixed with https://github.com/evilmartians/lefthook/pull/391 by @mrexox but it doesn't seem like it

**Comment by mrexox** [comment]
@bennycode , do you start VSCode from terminal? It's surprising that it works without any extra configuration.

Lefthook inherits envs from the environment it was called from. If it's your terminal, you usually have all envs, but with a desktop app you probably miss some `PATH` adjustments.

Please, use [`rc`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#rc) option if you use some desktop app with lefthook (you can put it to `lefthook-local.yml`, see examples)

Fast fix: add a rc file with the line `export PATH=$PATH:<path where npx lives>`

```bash
which npx
```

But better solution is to repeat your shell rc file adjustments.

**Comment by bennycode** [comment]
Hi @mrexox and thank you for your fast feedback. It helped me to narrow down the problem...

I am using Windows 11 and the [Windows Subsystem for Linux](https://www.youtube.com/watch?v=bRW5r7TK6KM). My SmartGit is installed in the WSL as it supports GUI applications. There is indeed a difference in how I can start my SmartGit desktop client...

## Starting from Start Menu

![image](https://github.com/user-attachments/assets/76f5483f-f15f-4472-9bfc-70e1299bfd35)

If I run SmartGit from the Windows start menu, then the commit in combination with Lefthook fails as it cannot find `npx`:

> sh: 1: npx: not found

## Starting from Ubuntu App (Terminal)

![image](https://github.com/user-attachments/assets/d1bef04a-0ef8-4101-91ea-b35cd969270b)

When I initially launch my terminal using the Ubuntu app on Windows and run SmartGit (`~/smartgit/bin/smartgit.sh`), I don't encounter any issues with Lefthook. However, it seems that Lefthook is not executed at all on a pre-commit.

Actually, when committing through VS Code (launched from my Start menu), the `pre-commit` hook is not executed either.

**Comment by mrexox** [comment]
I see. Well, in this case I can suggest you to install lefthook via `winget`, so it is available from anywhere (does it work for Winget like this?). 

This is the first time I meet your use case and it's interesting if installation via `winget` can fix this.

**Comment by CRC32EX** [comment]
lefthook is not Windows friendly.
So, Just use `scripts`.

<b>lefthook.yml</b>
```yml
pre-commit:
  scripts:
    "hello.sh":
      runner: bash
```

<b>.lefthook\pre-commit\hello.sh</b>
```bash
echo "hello"
```
