### ISSUE TITLE
`fata: bad revision HEAD@{0}` through git diff on post-merge

### ISSUE THREAD

**Issue by DeeepDev** [evilmartians/lefthook#892]
### :wrench: Summary

I have this post-merge hook in my repo:
```
post-merge:
  commands:
    'install deps if yarn lock changed':
       run: git diff --exit-code --name-only HEAD@{1} HEAD -- yarn.lock > /dev/null || (echo -e "\033[1;34myarn.lock changed, installing dependencies...\033[0m" && yarn)
```
When I run the command `git pull`, I always get `fatal: bad revision 'HEAD@0'`:
![image](https://github.com/user-attachments/assets/ba42dd81-729b-47ea-897f-2c63095df487)
But when I run the hook manually through `yarn lefthook run post-merge`, I don't see this error anymore.

### Lefthook version

`"lefthook": "1.9.2"`

### Steps to reproduce

I think it is obvious.

### Expected results

I expect the git diff command work without any error.

### Actual results

Through running `git pull`, I get the `fatal: bad revision HEAD@{0}` error.

**Comment by mrexox** [comment]
Hey @DeeepDev , this is probably because `{0}` is considered as a special [template](http://localhost:3000/configuration/run.html#git-arguments) for git arguments. I can suggest you the following configuration:

```yml
# lefthook.yml
post-merge:
  commands:
    'install deps if yarn lock changed':
       skip: 
         - run: git diff --exit-code --name-only HEAD@{1} HEAD -- yarn.lock
       run: echo -e "\033[1;34myarn.lock changed, installing dependencies...\033[0m" && yarn
```

This will skip if `git diff --exit-code --name-only HEAD@{1} HEAD -- yarn.lock` returns 0 (which is true if the last commit didn't change yarn.lock, and will execute the run command otherwise.
