### ISSUE TITLE
lefthook 1.9 broke `use_stdin` for `pre-push`

### ISSUE THREAD

**Issue by dAnjou** [evilmartians/lefthook#893]
### :wrench: Summary

lefthook 1.9 broke `use_stdin` for `pre-push`.

### Lefthook version

Tested with:
✅ 1.8.5
❌ 1.9.0
❌ 1.9.1
❌ 1.9.2

### Steps to reproduce

```yaml
pre-push:
    commands:
        cat:
            run: cat -
            use_stdin: true
```
```shell
git push --dry-run
```

### Expected results

lefthook runs the hook, and `cat` shows me the input passed from `git push`.

### Actual results

`1.8.5` works. `1.9.*` hangs. 

### Logs / Screenshots

[lefthook_1.8.5_log.txt](https://github.com/user-attachments/files/18167372/lefthook_1.8.5_log.txt)
[lefthook_1.9.0_log.txt](https://github.com/user-attachments/files/18167371/lefthook_1.9.0_log.txt)
[lefthook_1.9.1_log.txt](https://github.com/user-attachments/files/18167370/lefthook_1.9.1_log.txt)
[lefthook_1.9.2_log.txt](https://github.com/user-attachments/files/18167369/lefthook_1.9.2_log.txt)
