### ISSUE TITLE
Allow hook commands to be reused

### ISSUE THREAD

**Issue by laura-turner-evolvemep** [evilmartians/lefthook#911]
### :zap: Summary

It would be useful to reuse a hook command across multiple hooks. For example, using the same command across both `post-checkout` and `post-merge`.

### Value

Some hooks need to run the same commands; copy and pasting these commands is more error prone, especially if these commands need to be changed in the future.

### Behavior and configuration changes

A way I've though of changing this is to be able to define a top-level `commands` map in `lefthook.yml`, and then be able to reference it in my hooks. For example:

Current config (simplified)

```
post-merge:
  commands:
    install-packages:
      run: yarn

post-checkout:
  commands:
    install-packages:
      run: yarn
```

Updated config

```
post-merge:
  commands:
    install-packages

post-checkout:
  commands:
    install-packages

commands:
  install-packages:
    run: yarn
```

**Comment by mrexox** [comment]
Hey! You can use YAML anchors for this 

```yml
# lefthook.yml

post-merge:
  commands: &commands
    install-packages:
      run: yarn

post-checkout:
  commands: 
    <<: *commands
```
