### ISSUE TITLE
pre-commit is skipped when commit contains only deleted files

### ISSUE THREAD

**Issue by wood-jp** [evilmartians/lefthook#919]
### :wrench: Summary

The `pre-commit` hook is skipped when commit contains only deleted files.

### Lefthook version

1.10.1

### Steps to reproduce

1. Have a `pre-commit` hook defined (eg echo "hello world")
```
pre-commit:
  commands:
    "hello":
      run: echo "hello world"
```

3. Delete a file. Add to staged (no other changes).
4. Commit change.

### Expected results

Pre-commit hook should run.

### Actual results

Pre-commit hook does not run.

### Possible Solution

I tried using `files` as defined [here](https://evilmartians.github.io/lefthook/configuration/files.html)

```
pre-commit:
  commands:
    "hello":
      files: git diff --staged --name-only
      run: echo "hello world"
```

But that did not change the outcome. Perhaps the pre-commit hook does not consider this option, but should.

### Logs / Screenshots

```
╭───────────────────────────────────────╮
│ 🥊 lefthook v1.10.1  hook: pre-commit │
╰───────────────────────────────────────╯
sync hooks: ✔️ (pre-commit)
│  hello (skip) no files for inspection
                                      
```
