### ISSUE TITLE
Hooks that run jobs in parallel are erasing terminal output

### ISSUE THREAD

**Issue by silvenon** [evilmartians/lefthook#943]
### :wrench: Summary

When running a hook with parallel jobs, for example `lefthook run pre-push --force`, I'm only end up with the summary, and part of what I had in my terminal until then gets erased.

This does not happen with commands, and it does not happen with sequential jobs.

### Lefthook version

1.10.10 f5e7084f02cce4a6710b3fad7f0a3f83ede7c6a5

### Steps to reproduce

```yml
pre-push:
  parallel: true
  jobs:
    - run: npx eslint .
    - run: npx prettier --check .
    - run: npx tsc --noEmit
    - run: npx vitest run
```

```
npx lefthook run pre-push --force
```

### Expected results

Output of my tasks executing in parallel, followed by their summaries, along with what was in the terminal before.

### Actual results

https://github.com/user-attachments/assets/f773cc77-faef-4695-9df4-bad29977809b
