### ISSUE TITLE
Basic config using `jobs` yields no config

### ISSUE THREAD

**Issue by TheDutchCoder** [evilmartians/lefthook#945]
### :wrench: Summary

Basic `jobs` config does not work. `lefthook dump` shows an empty config.

### Lefthook version

1.7.18 3291e7d70ceed607e6b905875214069c423a4411

### Steps to reproduce

Config:
```yaml
pre-push:
  jobs:
    - run: npm run cli-lint
```

run `lefthook dump`

### Expected results

The config.

### Actual results

```
pre-push: {}
```
