### ISSUE TITLE
How to run interactive commits intelligently

### ISSUE THREAD

**Issue by xiapi233** [evilmartians/lefthook#950]
### :zap: Summary

When configuring interactive commits (git-cz) with prepare-commit-msg, this forces users to commit their code using the terminal, and if they commit using the git tool, it will still run an interactive commit, causing the commit to hang. A smarter approach would be to skip the interactive commits if the user passes the `-m` parameter when running `git commit` and it's not null, which is now done with the help of a bash script, which is what I did:

```yaml
prepare-commit-msg:
  commands:
    commitzen:
      interactive: true
      run: |
        COMMIT_MSG=$(cat {1} | sed -e 's/#.*//' -e '/^$/d')

        if [ -n "$COMMIT_MSG" ]; then
          exit 0
        fi

        npx git-cz --hook
      runner: bash
      skip:
        - merge
        - rebase
      env:
        LEFTHOOK: 0
```

What the script does is get the commit information in the contents of the `.git/COMMIT_EDITMSG` file, and if it's empty, run git-cz. But the script is not tender to run in windows.

### Value

If this conditional judgment was built in, it would make interactive commits easier to use and cross-platform support would be better.

**Comment by ianzone** [comment]
if git param is available in the skip, then this should work, but in reality, it's not.
```yml
skip:
  - run: node -e 'process.argv[1] !== "message" && process.exit(1)' {2}
```

**Comment by JBlackCat** [comment]
@xiapi233 this helps me out; thank you.

I have been trying to figure out a solution for awhile. The documentation, https://lefthook.dev/examples/commitlint.html?highlight=commitlint#commitlint-and-commitzen, suggests lefthook should already be handling this case but it does not.

One thing, I don't think `runner` is a a valid option for `commands`. My linter flags it and it doesn't appear to be an option in the config docs https://lefthook.dev/configuration/index.html

**Comment by xiapi233** [comment]
> This is my workaround, and it works on Windows
> 
> prepare-commit-msg:
>   commands:
>     commit:
>       skip:
>         - run: node -e "require('fs').readFileSync('.git/COMMIT_EDITMSG','utf8').trim()||process.exit(1)"
>       interactive: true
>       run: pnpm git-cz --hook
>       env:
>         LEFTHOOK: "0"

nice, this working fine. thank you

**Comment by mrexox** [comment]
Since there is a workaround I'm closing this issue.

**Comment by PrimeDominus** [comment]
> This is my workaround, and it works on Windows
> 
> prepare-commit-msg:
>   commands:
>     commit:
>       skip:
>         - run: node -e "require('fs').readFileSync('.git/COMMIT_EDITMSG','utf8').trim()||process.exit(1)"
>       interactive: true
>       run: pnpm git-cz --hook
>       env:
>         LEFTHOOK: "0"

I've tried this in WSL, and when running `git commit` in the vscode terminal CLI, all it does for me is open the `.git/COMMIT_EDITMSG` file in nano in the vscode terminal.

My assumption was that this workaround would allow running `git commit` by itself would trigger the commitzen interactive prompts, and when running `git commit -am "some valid commit message"` it would skip the interactive prompts. Is my assumption incorrect?

```yaml
# .lefthook.yml

# Build commit messages
prepare-commit-msg:
  commands:
    commitizen:
      skip:
        - run: node -e "require('fs').readFileSync('.git/COMMIT_EDITMSG','utf8').trim()||process.exit(1)"
      interactive: true
      run: pnpm git-cz --hook
      env:
        LEFTHOOK: "0"

# Validate commit messages
commit-msg:
  commands:
    "lint commit message":
      run: pnpm commitlint --edit {1}

**Comment by PrimeDominus** [comment]
I solved this using the following. Works with both vscode git tool and terminal on windows and *nix.

```yaml
# Build commit messages
prepare-commit-msg:
  jobs:
    - name: commitizen-windows
      only:
        - run: powershell -Command "if ( ('$IsWindows' -eq 'True') -and (Test-Path '.git/COMMIT_EDITMSG') ) { exit 0 } else { exit 1 }"
      interactive: true
      run: npx cz --hook #`pnpx cz` doesn't work, and git-cz ignores config.commitlint.ts see https://github.com/commitizen/cz-cli/issues/994
      env:
        LEFTHOOK: "0"
    - name: commitizen-nix
      only:
        - run: uname
      interactive: true
      run: |
        COMMIT_MSG=$(cat {1} | sed -e 's/#.*//' -e '/^$/d')
        if [ -n "$COMMIT_MSG" ]; then
          exit 0
        fi
        npx cz --hook
        # `pnpm cz --hook` also works (at the moment) if in your local repo you've already run `pnpm add -D @commitlint/cz-commitlint commitizen inquirer@9 @commitlint/config-conventional @commitlint/cli` and added the `"config": { "commitizen": { "path": "@commitlint/cz-commitlint" } }` correctly to your `package.json`
        # `pnpx cz --hook` should also work (at the moment) if you run the above `pnpm add ...` command with the `-w` flag.
      env:
        LEFTHOOK: "0"

# Validate commit messages
commit-msg:
  jobs:
    - name: commitlint
      run: pnpx commitlint --verbose --edit {1}
```
