### ISSUE TITLE
stuck on 'waiting: fetching remotes'

### ISSUE THREAD

**Issue by gabr1elt** [evilmartians/lefthook#967]
### :wrench: Summary

issue with remotes. stuck on 'waiting: fetching remotes'

### Lefthook version

1.11.2 eeffc478a490d7c6937de59cbe6301c4b1376744

### Steps to reproduce

add remotes config to my .yaml file
lefthook install -v

### Expected results

clone the repo and install the hooks

### Actual results

stuck on 'waiting: fetching remotes'

### Possible Solution

lefthook seems to start the cloning process as I can see the beginnings of the cloned repo at .git/info/lefthook-remotes (.git folder only)
but it seem its it gets stuck after that (nothing is being downloaded)

### Logs / Screenshots

```bash
│ [lefthook] cmd:    [git version]
│ [lefthook] stdout: git version 2.34.1
                                     
│ [lefthook] cmd:    [git rev-parse --path-format=absolute --show-toplevel --git-path hooks --git-path info --git-dir]
│ [lefthook] stdout: /root/Development
/root/Development/.git/hooks        
/root/Development/.git/info         
/root/Development/.git              
                                    
│ Searching config in:/root/Development
│ Merging remote config: https://github.com/gabr1elt/system: /root/Development/.git/info/lefthook-remotes/system-dev/.lefthook.yaml
│ Cloning remote config repository: /root/Development/.git/info/lefthook-remotes/system-dev
│ [lefthook] cmd:    [git -C /root/Development/.git/info/lefthook-remotes clone --quiet --origin origin --depth 1 --branch dev https://github.com/gabr1elt/system system-dev]
│ [lefthook] dir:    /root/Development
⠦ waiting: fetching remotes^Z
[1]+  Stopped                 lefthook install -v
```

**Comment by gabr1elt** [comment]
update:

the issue seems to happen on 1.11.2 only. 1.11.x to 1.10.x seem ok.

Installed the python package instead and got this extra traceback (not available on bin install!

```

⠙ waiting: fetching remotes^CTraceback (most recent call last):
  File "/opt/venv/bin/lefthook", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.10/site-packages/lefthook/main.py", line 23, in main
    result = subprocess.run([executable] + sys.argv[1:])
  File "/usr/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

my config is simple

```
# .lefthook.yaml

assert_lefthook_installed: true

# BUG: does not seem to work on 1.11.2
remotes:
  - git_url: https://github.com/gabr1elt/system
    # TODO: change to main when ready
    # ref: main
    ref: dev
    refetch_frequency: 24h
    configs:
      - .lefthook.yaml

```

**Comment by NathanAlcantara** [comment]
I had this problem too, to solve i downgrade to 1.11.0.
I have a private repo with sharable templates and just use the remote property, here is my lefthook.yaml:

```yaml
remotes:
  - git_url: git@<private-repo>.git
    configs:
      - commitlint.lefthook.yml

```
