### ISSUE TITLE
Lefthook validate doesn't allow "env" in jobs

### ISSUE THREAD

**Issue by silvenon** [evilmartians/lefthook#968]
### :wrench: Summary

`lefthook validate` doesn't allow specifying `env` in `jobs`, even though `env` is documented in `jobs`, and I believe it works.

```yaml
pre-push:
  jobs:
    - run: npm run my-thing
      env:
        HELLO: world
```

### Lefthook version

v1.11.2

### Steps to reproduce

Create a `lefthook.yaml` with the content above and run `npx lefthook validate`. Remove the `env` and it will pass. I'm using Lefthook through npm.

### Expected results

Considering that `env` is documented as supported by jobs, and appearing to work, I expect them to be considered valid by the `validate` command.

### Actual results

```
pre-push:
  jobs: Item at index 4 does not match the schema
Error: Validation failed for main config
```
