### ISSUE TITLE
Infinite loop if using command "transloco-keys-manager find"

### ISSUE THREAD

**Issue by jase88** [evilmartians/lefthook#980]
### :wrench: Summary

If trying to wrap [transloco-keys-manager](https://github.com/jsverse/transloco-keys-manager) I get an infinite loop. If calling the same command directly everything works as expected.

Does work:
`transloco-keys-manager -h`

Does not work within lefthooks:
`transloco-keys-manager find`

Not sure if this is really a lefthook issue or maybe a `transloco-keys-manager` issue.

### Lefthook version

1.11.5

### Steps to reproduce

- `git clone git@github.com:jase88/lefthook-transloco-keys-manager.git`
- call `lefthook i18n`

### Expected results

the command should go through the same as it does if calling directly

### Actual results

the command is running infinitely
`waiting: transloco-keys-manager`

**Comment by mrexox** [comment]
I'm not sure why it works like this, but you can fix it with adding `interactive: true`

```yml
i18n:
  commands:
    transloco-keys-manager:
      interactive: true
      run: transloco-keys-manager find
```

Looks like `transloco-keys-manager` requires some stdin or queries the TTY

**Comment by jase88** [comment]
Thanks for your support - I will close this ticket.

I opened [a issue for transloco-keys-manager](https://github.com/jsverse/transloco-keys-manager/issues/219).

The hang seems to occur as soon as the npm package [ora](https://github.com/sindresorhus/ora) is used.

**Comment by mrexox** [comment]
By the way another workaround would be this:

```yml
i18n:
  commands:
    transloco-keys-manager:
      env: 
        TERM: dumb
      run: transloco-keys-manager find
```

It looks like `orb` uses `is-interactive` which checks for TERM env variable: https://github.com/sindresorhus/is-interactive/blob/main/index.js
